
[enu default]

STARTUP1 =                                                                                                  "\n"
			"\cm   \ck$$$$\cm    \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "                             "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm  \ck$$\cm \ck$$$\cm  \ck$$\cm  " "  " "  " "    \ci$$\cm  \ci$$\cm  \ci$$$$\cm    "        "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm   \ck$$$$ $\cm  \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "  "\n"
			   "   " "      " "  " "     \ck v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "You are playing Quake Champions: Doom Edition. \n"
			"Join our Discord to chat with other players, \n"
			"report bugs and enjoy multiplayer events!";
STARTUP4 = "\n"
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 = " ";



[rus ru] // Thanks to Revenatn, Dech and Excedentia!

STARTUP1 =                                               "\n"
			"\cc   $$$$    $$$$       $$$$$   $$$$$$  "  "\n"
			"\cj  $$  $$  $$  $$  $$  $$  $$  $$      "  "\n"
			"\cn  $$  $$  $$          $$  $$  $$$$    "  "\n"
			"\ch  $$ $$$  $$          $$  $$  $$      "  "\n"
			"\cg  $$  $$  $$  $$  $$  $$  $$  $$      "  "\n"
			"\cg   $$$$ $  $$$$       $$$$$   $$$$$$  "  "\n"
			"                \ca v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "Добро пожаловать в Quake Champions: Doom Edition. \n"
			"Заходи в Дискорд: у нас можно поиграть по сети, \n"
			"поболтать с игроками или доложить о багах авторам.";
STARTUP4 =  " \n"
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 =  " ";



[ita it] // Thanks to Ivory Duke!

STARTUP1 =                                                     "\n"
			"\cd   $$$$    $$\cj$$       $$$\cg$$   $$$$$$  "  "\n"
			"\cd  $$  $$  $$ \cj $$  $$  $$ \cg $$  $$      "  "\n"
			"\cd  $$ $$$  $$ \cj         $$ \cg $$  $$$$    "  "\n"
			"\cd  $$  $$  $$ \cj $$  $$  $$ \cg $$  $$      "  "\n"
			"\cd   $$$$ $  $$\cj$$       $$$\cg$$   $$$$$$  "  "\n"
			   "                \cj v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "Stai ora giocando Quake Champions: Doom Edition. \n"
			"Entra a far parte del nostro server Discord. Chatta con gli altri \n"
			"giocatori, segnala bugs, e partecipa agli eventi multiplayer!";
STARTUP4 =
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 =  " ";



[es esm] // Thanks to JD-513 and Elfriede!

STARTUP1 =                                           "\n"
			"\cm   \ck$$$$\cm    \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "  "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm  \ck$$\cm \ck$$$\cm  \ck$$\cm  " "  " "  " "    \ci$$\cm  \ci$$\cm  \ci$$$$\cm    "     "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm   \ck$$$$ $\cm  \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "  "\n"
			   "   " "      " "  " "     \ck v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "Estas jugando Quake Champions: Doom Edition. \n"
			"Unete a nuestra comunidad de Discord para disfrutar al maximo \n"
			"partidas online con otros jugadores, asistencia a las dudas que \n"
			"tengas acerca del mod, reportar bugs o simplemente para pasar el \n"
			"rato y disfrutar de diversas charlas con varios integrantes e \n"
			"inclusive dialogar con los creadores para estar al tanto de este \n"
			"excelente mod. Ten en cuenta que en el servidor solo se admite \n"
			"Ingles para la comodidad de todos los jugadores.";
STARTUP4 =  " \n"
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 =  " ";



[es] // Thanks to JD-513 and Elfriede!

STARTUP3 =  "Estas jugando Quake Champions: Doom Edition. \n"
			"Unete a nuestra comunidad de Discord para disfrutar al maximo \n"
			"partidas online con otros jugadores, asistencia a las dudas que \n"
			"tengas acerca del mod, reportar bugs o simplemente para pasar el \n"
			"rato y disfrutar de diversas charlas con varios integrantes e \n"
			"inclusive los creadores para estar al tanto de este excelente mod. \n"
			"Ten en cuenta que en el servidor solo se admite Ingles para la \n"
			"comodidad de todos los jugadores.";


// TO DO:

[cz] // Thanks to QuakedoomNukem!

STARTUP1 =                                                                                                  "\n"
			"\cm   \ck$$$$\cm    \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "                             "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm  \ck$$\cm \ck$$$\cm  \ck$$\cm  " "  " "  " "    \ci$$\cm  \ci$$\cm  \ci$$$$\cm    "        "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm   \ck$$$$ $\cm  \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "  "\n"
			   "   " "      " "  " "     \ck v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "Hrajete Quake Champions: Doom Edici."
      "\n"  "Pripojte se na nas Discord server s ostatnimi hraci,"
      "\n"  "oznamujte chyby a uzivejte si o patecnich vicehracskych udalostech."
      "\n"  "Udalosti se vzdy odehravaji v patek v 17 hodin vecer,"
      "\n"  "zacina se Co-Opem, po hodine je Deathmatch a nakonec Duel po dalsi hodine."
      "\n"  "Jake herni mody a mapy budou hrany jsou vzdy voleny den predem."
      "\n"  "Discord je pouze anglicky, jsou na nem take vyvojari a je se vsemi legrace.";
STARTUP4 =  "\n"
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 =  " ";



[pl] // Thanks to Hurykles!

STARTUP1 =                                                                                                  "\n"
			"\cm   \ck$$$$\cm    \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "                             "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm  \ck$$\cm \ck$$$\cm  \ck$$\cm  " "  " "  " "    \ci$$\cm  \ci$$\cm  \ci$$$$\cm    "        "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm   \ck$$$$ $\cm  \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "  "\n"
			   "   " "      " "  " "     \ck v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "Witaj w Quake Champions: Doom Edition!"
      "\n"  "Jesli masz jakies problemy z modyfikacja lub po porostu chcesz "
      "\n"  "pogadac z innymi graczami zapraszamy na nasz serwer na Discordzie "
      "\n"  "(na ktorym obowiazuje tylko jezyk angielski)."
      "\n"  "Pamietajcie ze co piatek organizujemy eventy od 17:00 GMT +2. "
      "\n"  "Do zobaczenia na arenie!";
STARTUP4 =  "\n"
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 =  " ";

[fr] // Thanks to 1 anonymous collaborator!

STARTUP1 =                                                                                                  "\n"
			"\cm   \ck$$$$\cm    \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "                             "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm  \ck$$\cm \ck$$$\cm  \ck$$\cm  " "  " "  " "    \ci$$\cm  \ci$$\cm  \ci$$$$\cm    "        "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm   \ck$$$$ $\cm  \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "  "\n"
			   "   " "      " "  " "     \ck v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "Vous jouez Quake Champions: Doom Edition."
      "\n"  "Rejoignez notre Discord pour vous contacter d'autres joueurs, "
      "\n"  "rapporer les bogues and profiter des evenements de jeu.";
STARTUP4 =  "\n"
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 =  " ";



[hu] // Thanks to kultasakaali!

STARTUP1 =                                                                                                  "\n"
			"\cm   \ck$$$$\cm    \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "                             "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm  \ck$$\cm \ck$$$\cm  \ck$$\cm  " "  " "  " "    \ci$$\cm  \ci$$\cm  \ci$$$$\cm    "        "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm   \ck$$$$ $\cm  \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "  "\n"
			   "   " "      " "  " "     \ck v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "Udvozol a Quake Champions: Doom Edition. \n"
			"Csatlakozz Discord szerverunkhoz es chatelj velunk, \n"
			"jelezd, ha hibat talaltal a jatekban, \n"
			"valamint ertesulj szervezett online jatszmakrol!";
STARTUP4 =  "\n"
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 = " ";



[fi] // Thanks to kultasakaali!

STARTUP1 =                                                                                                  "\n"
			"\cm   \ck$$$$\cm    \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "                             "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm  \ck$$\cm \ck$$$\cm  \ck$$\cm  " "  " "  " "    \ci$$\cm  \ci$$\cm  \ci$$$$\cm    "        "\n"
			"\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$$\cm  \ck$\ci$\cm  \ci$$\cm  \ci$$\cm  \ci$$\cm      "  "\n"
			"\cm   \ck$$$$ $\cm  \ck$$$$\cm       \ci$$$$$\cm   \ci$$$$$$\cm  "  "\n"
			   "   " "      " "  " "     \ck v3.1     "   ;
STARTUP2 =  " ";
STARTUP3 =  "Tervetuloa Quake Champions: Doom Editioniin. \n"
			"Liity Discordiimme ja chattaile muiden pelaajien kanssa, \n"
			"ilmoita bugeista ja osallistu moninpeli matseihin!";
STARTUP4 =  "\n"
			"\ci->  https://\ckdiscord.gg/u4ptaMk  \ci<-";
STARTUP5 = " ";
