#library "ABILITIS"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"
#import "WEAPCNST.bcs"


//=============================================================================
//
//	Cooldowns for Active Abilities
//	expressed in tics (x *35)
//
//=============================================================================

#define AD_COOLDOWN      0
#define AD_COOLDOWN_PVE  1
#define AD_DURATION      2
#define AD_DURATION_PVE  3
#define AD_MULTIUSE      4
#define AD_MULTIUSEDELAY 5
#define AD_MULTIUSEFAILSOUND 6
#define AD_COLUMNS       7
#define XYZ              1000 // oh my fucking god

//
//		WHEN CHANGING COOLDOWN VALUES, MAKE SURE TO UPDATE COOLDOWNS IN MENUDEF
//
int AbilityData[NUMBER_OF_CLASSES * AD_COLUMNS] = {
	// COOLDOWN PVP,  COOLDOWN PVE , DURATION         , DURATION PVE     , MULTIUSE     , MULTIUSE     , MULTIUSE
	//             ,               ,                  ,                  ,              , COOLDOWN     , FAIL SND
	  (25 *35) +XYZ, ( 60 *35) +XYZ, (17)         +XYZ, (17)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // RANGER
	  (60 *35) +XYZ, (150 *35) +XYZ, (83)         +XYZ, (83)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // DOOMSLAYER
	  (60 *35) +XYZ, ( 60 *35) +XYZ, ( 2 *35)     +XYZ, ( 5 *35)     +XYZ,   3      +XYZ,   2*35   +XYZ, "NoSoundHax"                        , // CORVUS
	  (40 *35) +XYZ, ( 35 *35) +XYZ, (30)         +XYZ, (30)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // KANE
	  (30 *35) +XYZ, ( 30 *35) +XYZ, ( 8 *35)     +XYZ, (15 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // CALEB
	  (50 *35) +XYZ, (120 *35) +XYZ, (17)         +XYZ, (17)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // MENELKIR
	  (45 *35) +XYZ, (135 *35) +XYZ, ( 3 *35)     +XYZ, ( 3 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // TERMINATOR
	  (35 *35) +XYZ, ( 35 *35) +XYZ, ( 1 *35)     +XYZ, ( 1 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // ZEDEK
	  (40 *35) +XYZ, ( 90 *35) +XYZ, ( 5 *35)     +XYZ, (15 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // INQUISITOR
	  (35 *45) +XYZ, ( 35 *35) +XYZ, ( 1 *35)     +XYZ, ( 1 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // BITTERMAN
	  (35 *35) +XYZ, ( 35 *35) +XYZ, (28)         +XYZ, (28)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // GALEN
	  (35 *35) +XYZ, ( 15 *35) +XYZ,(( 3 *35)-10) +XYZ,(( 3 *35)-10) +XYZ, no       +XYZ, no       +XYZ, no                                  , // NYX
	  (45 *35) +XYZ, ( 90 *35) +XYZ, ( 8 *35)     +XYZ, ( 8 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // SORGAUL
	  (45 *35) +XYZ, ( 80 *35) +XYZ,(( 4 *35)+17) +XYZ, (14 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // DUKENUKEM
	  (40 *35) +XYZ, (120 *35) +XYZ, (53)         +XYZ, (53)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // DURANDAL
	  (50 *35) +XYZ, ( 30 *35) +XYZ, ( 9)         +XYZ, ( 9)         +XYZ,   5      +XYZ,   9      +XYZ, "QC/UI/PlayerSounds/LowAmmoWarning" , // KEEL
	  ( 1 *35) +XYZ, (  1 *35) +XYZ, (99)         +XYZ, (99)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // SARGE
	  (25 *35) +XYZ, ( 25 *35) +XYZ, (30)         +XYZ, (30)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // LOWANG
	  (35 *35) +XYZ, (110 *35) +XYZ, (75)         +XYZ, (75)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // GRAYSON
	  (30 *35) +XYZ, ( 30 *35) +XYZ, (10 *35)     +XYZ, (10 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // ERADICATOR
	  (40 *35) +XYZ, (120 *35) +XYZ, (10 *35)     +XYZ, (20 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // BLAZKOWICZ
	  (50 *35) +XYZ, ( 35 *35) +XYZ, (14)         +XYZ, (14)         +XYZ,   5      +XYZ,   18     +XYZ, "NoSoundHax"                        , // FREEMAN
	  (25 *35) +XYZ, ( 25 *35) +XYZ, (20)         +XYZ, (20)         +XYZ, no       +XYZ, no       +XYZ, no                                  , // VORMATUR
	  (30 *35) +XYZ, ( 20 *35) +XYZ, ( 7 *35)     +XYZ, (15 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // ELEENA
	  (50 *35) +XYZ, ( 25 *35) +XYZ, ( 3 *35)     +XYZ, ( 3 *35)     +XYZ,   4      +XYZ,   3*35   +XYZ, "NoSoundHax"                        , // LUCIENNE
	  (45 *35) +XYZ, (135 *35) +XYZ, ( 4 *35)     +XYZ, ( 4 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // MAJOR
	  (40 *35) +XYZ, ( 60 *35) +XYZ, ( 7 *35)     +XYZ, (20 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // HUNTER
	  (35 *35) +XYZ, ( 80 *35) +XYZ, ((11 *35)+8) +XYZ, (20 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // SAM
	  (45 *35) +XYZ, ( 60 *35) +XYZ, (5 *35 )     +XYZ, ( 5 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // POSTAL
	  (40 *35) +XYZ, (120 *35) +XYZ, (10*35 )     +XYZ, (20 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // PAINKILLER
	  (45 *35) +XYZ, ( 90 *35) +XYZ, (12*35 )     +XYZ, (24 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // INTRUDER
	  (45 *35) +XYZ, ( 45 *35) +XYZ, (25*35 )     +XYZ, (25 *35)     +XYZ, no       +XYZ, no       +XYZ, no                                  , // ORBB
// ^ insert more classes here
};

function int GetCooldown (void)
{
	SanityCheck();
	int column = AD_COOLDOWN;
	if(IsPVE()) column = AD_COOLDOWN_PVE;
	return AbilityData[CheckInventory("ClassID") * AD_COLUMNS + column] -XYZ;
}
function int GetDuration(void)
{
	SanityCheck();
	int column = AD_DURATION;
	if(IsPVE()) column = AD_DURATION_PVE;
	return AbilityData[CheckInventory("ClassID") * AD_COLUMNS + column] -XYZ;
}
function int  GetMultiuse            (void){ SanityCheck(); return AbilityData[CheckInventory("ClassID") * AD_COLUMNS + AD_MULTIUSE         ]    -XYZ; }
function int  GetMultiuseDelay       (void){ SanityCheck(); return AbilityData[CheckInventory("ClassID") * AD_COLUMNS + AD_MULTIUSEDELAY    ]    -XYZ; }
function int  GetMultiuseFailSound   (void){ SanityCheck(); return AbilityData[CheckInventory("ClassID") * AD_COLUMNS + AD_MULTIUSEFAILSOUND]        ; } // no -XYZ here because this is a string

int              LastUse      [64];
function int  GetLastUse    (void){ SanityCheck(); return LastUse[PlayerNumber()]    ; }
function void SetLastUse   (int x){ SanityCheck();        LastUse[PlayerNumber()] = x; }

int MultiusePeriod[64];

function void SanityCheck(void)
{
	//if(!CheckInventory("ClassID") && !CheckInventory("Class_Ranger"))
	//	printbold(d:timer(), s:": ", s:GetActorClass(0), s:" ", n:0, s:" checks its ability stats.");
}

// Once classes are rewritten as objects, these scripts won't be needed anymore
Script "PVP CD" (int class) clientside { SetResultValue(AbilityData[class * AD_COLUMNS + AD_COOLDOWN    ]   -XYZ); }
Script "PVE CD" (int class) clientside { SetResultValue(AbilityData[class * AD_COLUMNS + AD_COOLDOWN_PVE]   -XYZ); }


//=============================================================================
//=============================================================================
//
//		Script that upon entering a level, cleans up flag/token changes
//		made by active ability used in the previous level
//
//=============================================================================
//=============================================================================

Script "QCDE_CleanUpAbilities" (void)
{
	ACS("QCDE_DoCleanUpAbilities");
	if (GetNetworkState() == NETSTATE_SERVER)
		ACS("QCDE_CleanUpAbilities_CLIENTSIDE");
}

Script "QCDE_CleanUpAbilities_CLIENTSIDE" (void) clientside
{
	ACS("QCDE_DoCleanUpAbilities");
}

Script "QCDE_DoCleanUpAbilities" (void)
{
	SetLastUse(-GetMultiuseDelay());

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		 if(CheckInventory("Class_Doomslayer"	))	GiveInventory("SlayerBFGCleanerProc",1); // removes possible residual BFG
	else if(CheckInventory("Class_Kane"			))	GiveInventory("InjectionCleanerProc",1); // removes the NoFire token
	else if(CheckInventory("Class_Caleb"		))	GiveInventory("DollCleanerProc",1); //removes the doll
	else if(CheckInventory("Class_Terminator"	))	GiveInventory("TerminatorCleanerProc",1);
	else if(CheckInventory("Class_Inquisitor"	))	{GiveInventory("ReflectiveCleanerProc",1);GiveInventory("BecomeShieldCleanerProc",1);}
	else if(CheckInventory("Class_Galen"		))	GiveInventory("TotemCleanerProc",1);	// removes the NoFire token
	else if(CheckInventory("Class_Nyx"			))	GiveInventory("GhostWalkCleanerProc",1);
	else if(CheckInventory("Class_Sorgaul"		))	GiveInventory("PrimalRageCleanerProc",1);
	else if(CheckInventory("Class_DukeNukem"	))	GiveInventory("DukeFreezerCleanerProc",1);
	else if(CheckInventory("Class_Blazkowicz"	))	GiveInventory("AkimboCleanerProc",1);
	else if(CheckInventory("Class_Hunter"		))	GiveInventory("HunterCleanerProc",1); // remove the cubes
	else if(CheckInventory("Class_Painkiller"	))	GiveInventory("PainkillerCleanerProc",1); // restore HUD elements
	else if(CheckInventory("Class_Intruder"		))	GiveInventory("WendigoOutProc",1); // Back to normal
	// ^ insert more classes here

	SetInventory("StrikesCounter"   , false);
	SetInventory("PowerShieldCharge", false);
	SetInventory("MultiuseCharge"   , false);

	ACS_NamedExecuteWithResult("QCDE_UpdateMultiusePeriod", 0, 0);

	// It's generic, so it makes sense for everyone
	GiveInventory("GenericActiveCleanerProc",1);
	extraAbilityData[PlayerNumber()] = 0;
	SetNetworkReplicationFlags( 0 );
}

//=============================================================================
//=============================================================================
//
//		ABILITY-RELATED SCRIPTS
//
//=============================================================================
//=============================================================================

// Startup script

Script "QCDE_PassiveAbility" (void)
{
	if(GetActorProperty(0,APROP_HEALTH) <= 0) terminate;

	if (GetNetworkState() == NETSTATE_SERVER)
		ACS("QCDE_PassiveAbility_CLIENTSIDE");

		 if(CheckInventory("Class_Corvus"		))	ACS("QCDE_Passive_Corvus"    );
	else if(CheckInventory("Class_Terminator"	))	ACS("QCDE_Passive_Terminator");
	else if(CheckInventory("Class_Zedek"		))	ACS("QCDE_Passive_Zedek"     );
	else if(CheckInventory("Class_Inquisitor"	))	ACS("QCDE_Passive_Inquisitor");
	else if(CheckInventory("Class_Bitterman"	))	ACS("QCDE_Passive_Bitterman" );
	else if(CheckInventory("Class_Keel"			))	ACS("QCDE_Passive_Keel"      );
	else if(CheckInventory("Class_Sarge"		))	ACS("QCDE_Passive_Sarge"     );
	else if(CheckInventory("Class_LoWang"		))	ACS("QCDE_Passive_LoWang"    );
	else if(CheckInventory("Class_Grayson"		))	ACS("QCDE_Passive_Grayson"   );
	else if(CheckInventory("Class_Eradicator"	))	ACS("QCDE_Passive_Eradicator");
	else if(CheckInventory("Class_Blazkowicz"	))	ACS("QCDE_Passive_Blazkowicz");
	else if(CheckInventory("Class_Freeman"		))	ACS("QCDE_Passive_Freeman"   );
	else if(CheckInventory("Class_VorMatur"		))	ACS("QCDE_Passive_VorMatur"  );
	else if(CheckInventory("Class_Eleena"		))	ACS("QCDE_Passive_Eleena"    );
	else if(CheckInventory("Class_Lucienne"		))	ACS("QCDE_Passive_Lucienne"  );
	else if(CheckInventory("Class_Hunter"		))	ACS("QCDE_Passive_Hunter"    );
	else if(CheckInventory("Class_Sam"			))	ACS("QCDE_Passive_Sam"       );
	else if(CheckInventory("Class_Postal"		))	ACS("QCDE_Passive_Postal"    );
	else if(CheckInventory("Class_Painkiller"	))	ACS("QCDE_Passive_Painkiller");
	else if(CheckInventory("Class_Intruder"		))	ACS("QCDE_Passive_Intruder"  );
	// ^ insert more classes here
}

Script "QCDE_PassiveAbility_CLIENTSIDE" (void) clientside
{
	if (PlayerNumber() != ConsolePlayerNumber())
		terminate;

		 if(CheckInventory("Class_Zedek"		))	ACS("QCDE_Passive_Zedek"     );
	else if(CheckInventory("Class_Inquisitor"	))	ACS("QCDE_Passive_Inquisitor");
	else if(CheckInventory("Class_Hunter"		))	ACS("QCDE_Passive_Hunter"    );
}

int tics[64];
bool cooldownActive[64];

// Ranger - tells whether the orb was used on client to ignore timeout message from server
// Menelkir - tracks Dave duration
// Keel - tells how many grenades were thrown compared to ability cooldown messages from server. Needs to ignore messages that tell wrong cooldown
int extraAbilityData[64];

// Trigger script
Script "QCDE_ActiveAbility" (int predicting, int justPressed, int justReleased, int buttons)
{
	if (justPressed) {
		int plr = PlayerNumber();

		if(CheckInventory("NoAbilitiesToken"))			terminate; // Forbidden?
		if(GetActorProperty(0,APROP_HEALTH) <= 0)		terminate; // Dead players can't activate ability
		if(CheckInventory("PowerTerminatorArtifact"))	terminate; // qc_elderssoul special case

		// CTF special case
		if(hasFlags())
		{
			ACS("QCDE_Ability_Flag", hasFlags());
			terminate;
		}

		if(GetLastUse() + GetMultiuseDelay() > Timer()) terminate; // Prevent spam

		if (predicting) {
			//log(s:"Predicting ability!");
			if(CheckInventory("Class_Ranger")) {
				if (GetPredictableValue(0, 0))
					ACS_NamedExecuteWithResult("QCDE_DireOrbPredictedUse", 0, 0);
			} else if(CheckInventory("Class_Eleena")) {
				if (GetPredictableValue(0, 0))
					ACS_NamedExecuteWithResult("QCDE_EleenaSwapPredictedUse", 0, 0);
			}
		} else if (!tics[plr]) { // abilities that activate only once
			//log(s:"Activated single use ability");
			SetLastUse(Timer());
			ACS_NamedExecuteWithResult("QCDE_UpdateMultiusePeriod", 0, 0);

				 if(CheckInventory("Class_Ranger"	))	ACS("QCDE_Ability_Ranger"    );
			else if(CheckInventory("Class_Doomslayer"))	ACS("QCDE_Ability_Doomslayer");
			else if(CheckInventory("Class_Corvus"	))	ACS("QCDE_Ability_Corvus"    );
			else if(CheckInventory("Class_Kane"		))	ACS("QCDE_Ability_Kane"      );
			else if(CheckInventory("Class_Caleb"	))	ACS("QCDE_Ability_Caleb"     );
			else if(CheckInventory("Class_Menelkir"	))	ACS("QCDE_Ability_Menelkir"  );
			else if(CheckInventory("Class_Terminator"))	ACS("QCDE_Ability_Terminator");
			else if(CheckInventory("Class_Zedek"	))	ACS("QCDE_Ability_Zedek"     );
			else if(CheckInventory("Class_Inquisitor"))	ACS("QCDE_Ability_Inquisitor");
			else if(CheckInventory("Class_Bitterman"))	ACS("QCDE_Ability_Bitterman" );
			else if(CheckInventory("Class_Galen" 	))	ACS("QCDE_Ability_Galen"     );
			else if(CheckInventory("Class_Nyx"		))	ACS("QCDE_Ability_Nyx"       );
			else if(CheckInventory("Class_Sorgaul"	))	ACS("QCDE_Ability_Sorgaul"   );
			else if(CheckInventory("Class_DukeNukem"))	ACS("QCDE_Ability_DukeNukem" );
			else if(CheckInventory("Class_Durandal"	))	ACS("QCDE_Ability_Durandal"  );
			else if(CheckInventory("Class_Keel"		))	ACS("QCDE_Ability_Keel"      );
			else if(CheckInventory("Class_LoWang"	))	ACS("QCDE_Ability_LoWang"    );
			else if(CheckInventory("Class_Grayson"	))	ACS("QCDE_Ability_Grayson"   );
			else if(CheckInventory("Class_Eradicator"))	ACS("QCDE_Ability_Eradicator");
			else if(CheckInventory("Class_Blazkowicz"))	ACS("QCDE_Ability_Blazkowicz");
			else if(CheckInventory("Class_Freeman"	))	ACS("QCDE_Ability_Freeman"   );
			else if(CheckInventory("Class_VorMatur"	))	ACS("QCDE_Ability_VorMatur"  );
			else if(CheckInventory("Class_Eleena"	))	ACS("QCDE_Ability_Eleena"    );
			else if(CheckInventory("Class_Lucienne"	))	ACS("QCDE_Ability_Lucienne"  );
			else if(CheckInventory("Class_Major"	))	ACS("QCDE_Ability_Major"     );
			else if(CheckInventory("Class_Hunter"	))	ACS("QCDE_Ability_Hunter"    );
			else if(CheckInventory("Class_Sam"		))	ACS("QCDE_Ability_Sam"       );
			else if(CheckInventory("Class_Postal"	))	ACS("QCDE_Ability_Postal"    );
			else if(CheckInventory("Class_Painkiller"))	ACS("QCDE_Ability_Painkiller");
			else if(CheckInventory("Class_Intruder"	))	ACS("QCDE_Ability_Intruder"  );
			else if(CheckInventory("Class_Orbb"		))	ACS("QCDE_Ability_Orbb"      );
			// ^ insert more classes here
		} else {
			//log(s:"Activated multi use ability");
			ACS_NamedExecuteWithResult("QCDE_UpdateMultiusePeriod", 0, 0);

				 if(CheckInventory("Class_Corvus"	))	ACS("QCDE_Ability_Corvus"    );
			else if(CheckInventory("Class_Keel"		))	ACS("QCDE_Ability_Keel"      );
			else if(CheckInventory("Class_Freeman"	))	ACS("QCDE_Ability_Freeman"   );
			else if(CheckInventory("Class_Eleena"	))	ACS("QCDE_Ability_Eleena"    );
			else if(CheckInventory("Class_Lucienne"	))	ACS("QCDE_Ability_Lucienne"  );
			// ^ insert more classes here if needed
		}
	}
}

// Shared counters

Script "QCDE_UpdateMultiusePeriod" (void)
{
	int multiuse = GetMultiuse();
	if(multiuse)
	{
		MultiusePeriod[PlayerNumber()] = (GetCooldown() / GetMultiuse())
				* GetCvar("sv_cooldownPercentage") / 100
				* (100 - CheckInventory("CooldownRewardToken") - CheckInventory("CooldownRewardToken2")) / 100;
		int plr = PlayerNumber();
		int charges = multiuse - ((tics[plr] + (MultiusePeriod[plr] - 1)) / MultiusePeriod[plr]);
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("MultiuseCharge", charges);
		SetNetworkReplicationFlags( 0 );
	}
	else
	{
		MultiusePeriod[PlayerNumber()] = 1;
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("MultiuseCharge", no);
		SetNetworkReplicationFlags( 0 );
	}
}

#define AP_TOTAL 0
#define AP_NOW   1
int activeProgress[64][2];
Script "QCDE_ShowActiveInProgress" (int duration, int now)
{
	if(duration <= 0) terminate;
	if(!now) now = duration;
	int plr = PlayerNumber();
	//log(n:0, s:" showing progress: ", d:now, s:" / ", d:duration, s:"      concurrent? ", d:activeProgress[plr][AP_NOW]);

	int concurrent = activeProgress[plr][AP_NOW] > 0;

	activeProgress[plr][AP_TOTAL] = duration;
	activeProgress[plr][AP_NOW  ] = now;

	if(concurrent) terminate;

	ACS_NamedExecuteAlways("QCDE_DoActiveInProgressCooldown", 0);
}

Script "QCDE_ShowActiveInProgress_CLIENTSIDE" (int duration, int now) clientside
{
	ACS("QCDE_ShowActiveInProgress", duration, now);
}

Script "QCDE_DoActiveInProgressCooldown" ()
{
	int plr = PlayerNumber();
	if (activeProgress[plr][AP_TOTAL] <= 0) terminate;
	int amount = 256 * activeProgress[plr][AP_NOW] / activeProgress[plr][AP_TOTAL];
	while(activeProgress[plr][AP_NOW] --> 0 && GetActorProperty(0, APROP_HEALTH) > 0)
	{
		if(CheckInventory("ActiveProgressToken") > amount) terminate; // allows preempting previously launched ability

		amount = 256 * activeProgress[plr][AP_NOW] / activeProgress[plr][AP_TOTAL];
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("ActiveProgressToken",amount);
		SetNetworkReplicationFlags( 0 );
		delay(1);
	}
	activeProgress[plr][AP_NOW] = 0;
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetInventory("ActiveProgressToken",0);
	SetNetworkReplicationFlags( 0 );
	//log(n:0, s:" completes progress: ", d:activeProgress[plr][AP_NOW], s:" / ", d:activeProgress[plr][AP_TOTAL]);
}

Script "QCDE_AbilityCooldown" (int in_tics, int dontPlayAlert)
{
	//log(s:"QCDE_AbilityCooldown - ", d:in_tics);

	// reconciling just to know how many tics to offset the cooldown
	// we add 2 to also compensate for a 1 to 2 tics delay for executing the script on clientside
	if (in_tics > -1 && GetNetworkState() == NETSTATE_SERVER) {
		in_tics -= UnlaggedReconcile(0) + 2;
		UnlaggedRestore(0);
		if (in_tics < 0)
			in_tics = 0;
	}

	int multiuse = GetMultiuse();
	int plr = PlayerNumber();
	int cooldownId = timer() * 100 + plr;
	//log(s:"Cooldown ", d:cooldownId, s:" runs, ", d:in_tics, s:", ", d:dontPlayAlert);

	if(in_tics != -1) // if not resuming
	{
		// Not starting a cooldown if either:
		// - Already in cooldown
		// - Ability is multiuse
		if(tics[plr] && !multiuse)
		{
			if (GetNetworkState() == NETSTATE_SERVER)
				ACS("QCDE_AbilityCooldown_CLIENTSIDE", tics[plr], false);
			terminate;
		}

		// For abilities that have multiple charges
		if(multiuse)
		{
			if(tics[plr] <= 0) // First grenade
			{
				in_tics = MultiusePeriod[plr];
			}
			else if(tics[plr] <= MultiusePeriod[plr] * (multiuse - 1)) // Up to last grenade
			{
				tics[plr] += MultiusePeriod[plr];
				//log(s:"Added period ", d:MultiusePeriod[plr], s:", is now ", d:GetCooldown(plr)));
				if (GetNetworkState() == NETSTATE_SERVER)
					ACS("QCDE_AbilityCooldown_CLIENTSIDE", tics[plr], false);
				terminate;
			}
			else // Out of charges
			{
				if (GetNetworkState() != NETSTATE_SERVER)
					LocalAmbientSound(GetMultiUseFailSound(), 127);
				//log(s:"Out of charges: ", d:tics[plr]), s:" > ", d:MultiusePeriod[plr], s:" * ", d:(multiuse - 1));
				SetResultValue(false); // signal to ability code that this sort of spam ain't gonna fly
				if (GetNetworkState() == NETSTATE_SERVER)
					ACS("QCDE_AbilityCooldown_CLIENTSIDE", tics[plr], false);
				terminate;
			}
		}
	}

	// Scale input according to percentage server cvar
	if(in_tics > -1) in_tics = in_tics * GetCvar("sv_cooldownPercentage") / 100;

	// If not resuming, set duration and prepare to play DING! on replenishment
	bool playAlert = false;
	if(in_tics > 0)
	{
		tics[plr] = in_tics;
		playAlert = true;

		if(!multiuse)
		{
			// Apply completionist bonus of reduced cooldown, if applicable
			int bonus = CheckInventory("CooldownRewardToken") + CheckInventory("CooldownRewardToken2");
			ACS_NamedExecuteAlways("QCDE_Hourglass",0,bonus,true);
		}
	}

	CapCooldown();

	while(CheckInventory("ActiveInProgress"))
		delay(1);

	//log(s:"QCDE_AbilityCooldown - Sending ", d:tics[plr]);
	if (GetNetworkState() == NETSTATE_SERVER)
		ACS("QCDE_AbilityCooldown_CLIENTSIDE", tics[plr], playAlert && !dontPlayAlert);
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown_DoCooldown", playAlert && !dontPlayAlert);
}

Script "QCDE_AbilityCooldown_CLIENTSIDE" (int in_tics, int playAlert) clientside
{
	if (PlayerNumber() != ConsolePlayerNumber())
		terminate;

	//log(s:"QCDE_AbilityCooldown_CLIENTSIDE - new: ", d:in_tics, s:", old: ", d:tics[PlayerNumber()]);

	if (in_tics == 0)
		SetInventory("AbilityCooldownToken",0);

	if (CheckInventory("Class_Corvus") || CheckInventory("Class_Keel")
		|| CheckInventory("Class_Freeman") || CheckInventory("Class_Lucienne")) {
		if (extraAbilityData[PlayerNumber()] > 0)
			extraAbilityData[PlayerNumber()]--;
		if (extraAbilityData[PlayerNumber()] > 0) {
			//log(s:"QCDE_AbilityCooldown_CLIENTSIDE - ignored");
			terminate;
		}
	}

	tics[PlayerNumber()] = in_tics;
	SetInventory("AbilityCooldownSeconds", in_tics / 35);
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown_DoCooldown", playAlert);
}

Script "QCDE_AbilityCooldown_DoCooldown" (int playAlert)
{
	int plr = PlayerNumber();
	//log(s:"QCDE_AbilityCooldown_DoCooldown - ", d:tics[plr]);

	if (tics[plr] > 0)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("AbilityCooldownToken", 1);
		SetNetworkReplicationFlags( 0 );
	}

	if (cooldownActive[plr])
		terminate;

	cooldownActive[plr] = tics[plr] > 0;

	if(playAlert && GetNetworkState() != NETSTATE_SERVER)
		ACS("QCDE_AbilityIconFlash", no);
	// Actual countdown
	while(tics[plr] > 0)
	{
		SetActivator(-1);

		delay(1);

		if(!PlayerInGame(plr)) {
			cooldownActive[plr] = false;
			terminate;
		}

		SetActivator(plr + 1000);

		if(CheckInventory("ActiveInProgress")) continue;

		tics[plr] -= 1;

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );

		// Update charges count if ability is multi-usable
		int multiuse = GetMultiuse();
		if(multiuse)
		{
			int charges = multiuse - ((tics[plr] + (MultiusePeriod[plr] - 1)) / MultiusePeriod[plr]);
			SetInventory("MultiuseCharge", charges);
		}

		// Update second count if it changed
		SetInventory("AbilityCooldownSeconds", tics[plr] / 35);

		// Update decisecond count if it's relevant
		if(tics[plr] < 5 *35)
			SetInventory("AbilityCooldownDeciseconds", (tics[plr] % 35) * 10 / 35);

		SetNetworkReplicationFlags( 0 );
	}

	//log(s:"Cooldown ", d:cooldownId, s:" is done by ", d:Timer());
	tics[plr] = 0;
	cooldownActive[plr] = false;
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetInventory("AbilityCooldownToken",		0);
	SetInventory("AbilityCooldownSeconds",		0);
	SetInventory("AbilityCooldownDeciseconds",	0);
	SetInventory("TeleporterThrownToken",		0); // Reset Ranger orb
	SetNetworkReplicationFlags( 0 );

	if(playAlert && !CheckInventory("Class_Sarge"))
	{
		if (GetNetworkState() != NETSTATE_SERVER)
		{
			ACS("QCDE_AbilityIconFlash", yes);
		}
		else
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			PlaySound(0, "QC/Abilities/General/AbilityCharged", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
			SetNetworkReplicationFlags( 0 );
		}
	}
}

script "QCDE_AbilityIconFlash" (int sound) clientside
{
	if(IsZandronum(true))
		if(ActivatorTid() != CheckPlayerCamera(ConsolePlayerNumber()))
			terminate;

	SetHudSize(1400,1050,1);

	if(sound) AmbientSound("QC/Abilities/General/AbilityCharged",127);
	SetHudSize(1400,1050,1);
	SetFont("BLINKGL2");
	HudMessageBold(s:"A"; HUDMSG_FADEOUT, 3244, CR_UNTRANSLATED, 700.0, 911.0, 0.18, 0.2);
}

// Useful when switching from high cooldown champion to lower cooldown champion after using ability
Function void CapCooldown(void)
{
	if(CheckInventory("Class_Sarge")) return; // MAP31: DBThanatos says no cheating

	int plr = PlayerNumber();
	int perc = GetCvar("sv_cooldownPercentage");
	int baseCooldown = GetCooldown();
	if (tics[plr] > baseCooldown * perc / 100)
		tics[plr] = baseCooldown * perc / 100;
}

Script "nocd" (void) // cheat for debugging
{
	tics[PlayerNumber()] = 0;
}


// This is added to ensure the ability-weapons are being held only by the correct
// class and only when his ability is being used
str ClassxWeapon[8][2] = {
		{"nothing",				"nothing"			},		//0  Empty
		{"Class_Blazkowicz",	"BlazkoAkimbo"		},		//1
		{"Class_Doomslayer",	"SlayerBFG"			},		//2
		{"Class_DukeNukem",		"DukeFreezeThrower"	},		//3
		{"Class_Inquisitor",	"Shieldquisitor"	},		//4
		{"Class_Sam",			"SamMinigun"		},		//5
		{"Class_Sorgaul",		"SorgaulFists"		},		//6
		{"Class_Caleb",			"CalebDoll"			}		//7
		// ^ insert more ability weapons here
		};

script "CheckIfCorrectPlayer" (int who)
{
	if(CheckInventory(ClassxWeapon[who][0]) && CheckInventory("ActiveInProgress"))
	{
		//PrintBold(s:"we good");
	}
	else
	{
		if(!checkinventory("AbilityWeaponDebug")) //if you have this token, you can use the weap with any champ anytime
		{
			//PrintBold(s:"something's off, bye");
			TakeInventory(ClassxWeapon[who][1],1);
		}
	}
}

//=============================================================================
//
//		Active Ability: Per Class handlers
//
//=============================================================================


//---------------------------------
//		CTF special case: drop flag if holding flag

int flagNames[NUMBER_OF_FLAGS] = {
	"RedFlag"  ,
	"BlueFlag" ,
	"GreenFlag",
	"WhiteFlag",
	"GoldFlag" ,
};

Script "QCDE_Ability_Flag" (void)
{
	// Cannot drop flag. Capture or die.
	terminate;
}


//---------------------------------
//		Ranger's Active

Script "QCDE_Ability_Ranger" (void)
{
	if (tics[PlayerNumber()]) terminate;

	if(!CheckInventory("TeleporterThrownToken"))
	{
		extraAbilityData[PlayerNumber()] = false;
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("DireOrbFireProc",1);
		ACS("QCDE_RangerHandAnimation");
		SetNetworkReplicationFlags( 0 );
		delay(3);
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("GenericActiveCleanerProc",1);
		SetNetworkReplicationFlags( 0 );
	}
	else
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("DireOrbTeleProc",1);
		ACS_NamedExecuteWithResult("QCDE_DireOrbUsed", 0, 0);
		SetNetworkReplicationFlags( 0 );
		delay(3);
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("GenericActiveCleanerProc",1);

		GiveInventory("NoWeaponFireToken",1);
		SetNetworkReplicationFlags( 0 );
		ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
		delay(GetDuration()); //duration of active ability
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		TakeInventory("NoWeaponFireToken",1);
		SetNetworkReplicationFlags( 0 );
	}
}
Script "QCDE_RangerHandAnimation" (void) clientside
{
	// *.0 on coordinates means "align to center"
	DrawWeapon("QP01X0",  60.0, 310.0);	delay(1);
	DrawWeapon("QP01X0",  90.0, 290.0);	delay(1);
	DrawWeapon("QP01X0", 120.0, 270.0);	delay(1);
	DrawWeapon("QP01X0", 150.0, 250.0); delay(1);
	DrawWeapon("QP01X0", 150.0, 250.0); delay(1);
	DrawWeapon("QP01X0", 150.0, 250.0); delay(1);
	DrawWeapon("QP01X0", 150.0, 250.0); delay(1);

	DrawWeapon("QP01Y0", 150.0, 260.0); delay(1);
	DrawWeapon("QP01Y0", 150.0, 280.0); delay(1);
	DrawWeapon("QP01Y0", 150.0, 300.0); delay(1);
	DrawWeapon("QP01Y0", 150.0, 320.0); delay(1);
	DrawWeapon("QP01Y0", 150.0, 340.0); delay(1);
	DrawWeapon("QP01Y0", 150.0, 360.0); delay(1);
}

//---------------------------------
//		Doomslayer's Active

Script "QCDE_Ability_Doomslayer" (void)
{
	int w;
	for(w = 0; w < NUMBER_OF_WEAPONS; w++)
		if(!stricmp(getWeapon(), weaponList[w]))
			break;

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("SlayerBFGProc",1);
	PlaySound(0,"QC/Abilities/Doomslayer/BFGWeaponRaise",CHAN_7,0.75,false,0.5);
	SetNetworkReplicationFlags( 0 );
	ACS("QCDE_SetWeapon", "SlayerBFG", 80);

	while(CheckInventory("BFGstarted")<1)	//token is given by the weapon. This is to ensure the meter starts when the weapon is out
		delay(1);							//because if you fire a RG, RG animation has to end before the weapon is switched
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	//total duration is 83
	//firing delay is 34
	//remaining time is 83-34=49

	Delay(34);

	int t = 35;

	while(t --> 0)
	{
		if(GetActorProperty(0,APROP_HEALTH) <= 0) break;
		delay(1);
	}

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	//Unzoom if using toggle zoom
	if (!GetCVar("cl_holdZoom")) SetInventory("WeaponZoomedToken", 0);
	//Give and select fake weapon
	SetWeapon(weaponList[w]);
	//Remove ability weapon
	TakeInventory("SlayerBFG",1);
	TakeInventory("BFGstarted",1);
	GiveInventory("SlayerBFGCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}


//---------------------------------
//		Corvus's Active

Script "QCDE_Ability_Corvus" (void)
{
	if(!CheckInventory("ActiveProgressToken") && ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown()))
	{
		SetLastUse(Timer());
		extraAbilityData[PlayerNumber()]++;
		ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("CorvusFlightProc",1);
		SetNetworkReplicationFlags( 0 );

		delay(GetDuration()); //duration of active ability

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("GenericActiveCleanerProc",1);
		SetNetworkReplicationFlags( 0 );
	}
}


//---------------------------------
//		Kane's Active

Script "QCDE_Ability_Kane" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("InjectionProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_KaneAbilityMovement", 1);

	// Disable remaining damage over time from possible Postal's cow head or Quietus
	cowgassing_for[PlayerNumber()] = 0;
	quieting_for[PlayerNumber()] = 0;

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	delay(GetDuration()); //duration of active ability

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_KaneAbilityMovement", 0);
}


//---------------------------------
//		Caleb's Active
//---------------------------------

Script "QCDE_Ability_Caleb" (void)
{
	int w;
	for(w = 0; w < NUMBER_OF_WEAPONS; w++)
		if(!stricmp(getWeapon(), weaponList[w]))
			break;

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	//PlaySound(0,"QC/Abilities/Caleb/ActivateDrain",CHAN_5,0.75,false,1.0,false,true);
	SetPlayerProperty(0,1,PROP_INSTANTWEAPONSWITCH);
	SetNetworkReplicationFlags( 0 );

	if(PlayerIsBot(PlayerNumber()))
	{
		GiveInventory("DollBotProc",1);
		ACS("QCDE_SetWeapon", "CalebDollBot", GetDuration());
	}
	else
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("DollProc",1);
		SetNetworkReplicationFlags( 0 );
		ACS("QCDE_SetWeapon", "CalebDoll", GetDuration());
	}

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	int t = GetDuration();
	while(t --> 0)
	{
		if(checkinventory("DollSpent")) t=0;
		if(GetActorProperty(0,APROP_HEALTH) <= 0) break;
		delay(1);
	}

	// Break progress meter: 1 total duration, 1 remaining tic
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", 1, 1);

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetWeapon(weaponList[w]);
	TakeInventory("CalebDoll",1);
	TakeInventory("CalebDollBot",1);
	GiveInventory("DollCleanerProc",1); //Remove ability weapon
	TakeInventory("DollSpent",1);
	SetNetworkReplicationFlags( 0 );
}

Script "VoodooHealer" (int deathmatcher)
{
	int maxhealth = CheckInventory("MaxHealthToken");
	int healnormal, healover;

	if(deathmatcher==1)
	{
		healnormal=25;
		healover=5;
	}
	else
	{
		healnormal=35;
		healover=10;
	}


	if( GetActorProperty(0,APROP_HEALTH) < maxhealth)
		ACS_NamedExecuteWithResult("HealthGiver",maxhealth,healnormal, 0);
	else
		ACS_NamedExecuteWithResult("HealthGiver",maxhealth,healover, 75);

}



int last_voodoocaster = -2;
int last_voodootime;
int last_voodoovictimtime[64];
// Activator: Casting Caleb
Script "QCDE_VoodooOwner" (void)
{
	last_voodoocaster = ActivatorTid();
	last_voodootime = Timer();
	//PrintBold(s:"\cv VOODOO CASTER IS NOW ", d:last_voodoocaster, s:" ", n:last_voodoocaster-999);
}

#define VOODOO_ALTFIRE_DMG 30
// Activator: Voodoo Victim
Script "QCDE_VoodooVictim" (void)
{
	int tid = ActivatorTid();
	if(tid == last_voodoocaster) terminate; // no self damage
	if(last_voodoovictimtime[tid-999] == last_voodootime) terminate; // don't repeat
	last_voodoovictimtime[tid-999] = last_voodootime;

	// Activator: Casting Caleb
	SetActivator(last_voodoocaster);

	Thing_Damage(tid, VOODOO_ALTFIRE_DMG, MOD_DISINTEGRATE);
	GiveInventory("HitBeepMid",1);
	//PrintBold(n:0, s:"\ck damaging ", d:tid-1000, s:" ", n:tid-999);
}

//---------------------------------
//		Menelkir's Active

Script "QCDE_Ability_Menelkir" (void)
{
	if(CheckInventory("ActiveProgressToken")) terminate;

	if(!CheckDaveRoom())
	{
		PlaySound(0, "Menelkir/fail", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
		terminate;
	}

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0,"QC/Abilities/Menelkir/Activate",CHAN_7,1.0,false,0.5);
	GiveInventory("SummonProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());

	delay(GetDuration()); // duration before rethrow is allowed

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}

function int CheckDaveRoom(void)
{
	int a = GetActorAngle(0);
	int x = GetActorX(0) + cos(a) * 60;
	int y = GetActorY(0) + sin(a) * 60;
	int z = GetActorZ(0);

	int tid = UniqueTid();
	bool succ = Spawn("DaveRoomTest", x,y,z, tid);
	Thing_Remove(tid);

	return succ;
}

script "MyBoyIsDed" (void)	//played on menelkir's head when dave dies
{
	PlaySound(0, "minotaur/death", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
}


//---------------------------------
//		Terminator's Active

#define TERMINATOR_ROCKET_DELAY  3
Script "QCDE_Ability_Terminator" (void)
{
	int counterer;
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("TerminatorMainProc",1); //plays voice line and stop weapons
	GiveInventory("ActiveProgressToken",256);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	Delay(25);	//waits a bit before using them, chance to escape
	int rocketCount = CheckInventory("TerminatorRockets");
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", rocketCount * TERMINATOR_ROCKET_DELAY);

	while(counterer++ < rocketCount && GetActorProperty(0, APROP_HEALTH) > 0)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("TermRocketProc",1);
		TakeInventory("TerminatorRockets",1);
		SetNetworkReplicationFlags( 0 );
		delay(TERMINATOR_ROCKET_DELAY);
	}

	Delay(10);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("TerminatorCleanerProc",1);
	if (GameType() >= GAME_NET_DEATHMATCH)
		SetInventory("TerminatorRockets",10);
	else
		SetInventory("TerminatorRockets",20);
	SetNetworkReplicationFlags( 0 );
}


//---------------------------------
//		Zedek's Active

Script "QCDE_Ability_Zedek" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("QuietusAttackProc",1);
	ACS("QCDE_ZedekSwordAnimation");
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	Delay(GetDuration());
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}

Script "QCDE_ZedekSwordAnimation" (void) clientside
{

	// *.1 on coordinates means "align to top-left"
	DrawWeapon("QP08Z0",  40.1, 235.1);	delay(1);
	DrawWeapon("QP08Z0", 130.1, 260.1);	delay(1);
	DrawWeapon("QP08Z0", 200.1, 300.1);	delay(1);
	DrawWeapon("QP08Z0", 260.1, 320.1);	delay(1);
	DrawWeapon("QP08Z0", 300.1, 335.1);	delay(1);
	DrawWeapon("QP08Z0", 330.1, 350.1);	delay(1);
	DrawWeapon("QP08Z0", 360.1, 365.1);	delay(1);
	DrawWeapon("QP08Z0", 390.1, 375.1);	delay(1);
	DrawWeapon("QP08Z0", 420.1, 385.1);	delay(1);
	DrawWeapon("QP08Z0", 420.1, 955.1);	delay(1);	//super far away, to not be visible
}

int last_quieter;
Script "QCDE_QuietusHit" (void)
{
	last_quieter = GetActorProperty(0, APROP_TargetTID);
	//log(s:"Last quieter is set to ", d:last_quieter, s:" -- ", n:last_quieter -999);
}

int quieting_for[64], quieter_of[64];
#define QUIETING_AMOUNT  6
#define QUIETING_DAMAGE 10
#define QUIETING_PERIOD 35
Script "QCDE_QuietusVictim" (void)
{
	int plr = PlayerNumber();
	if(!isEnemy(last_quieter - 1000)) terminate; // No self nor team quietance
	quieter_of[plr] = last_quieter;

	// Already quieted by somebody? Update the other script
	if(quieting_for[plr])
	{
		quieting_for[plr] = QUIETING_AMOUNT;
		//log(n:plr+1, s:" updates quieter ", d:quieter_of[plr], s:" -- ", n:quieter_of[plr] -999, s:" and duration to ", d:quieting_for[plr]);
		terminate;
	}

	// New quietance
	//log(n:plr+1, s:" gets quieted by ", d:quieter_of[plr], s:" -- ", n:quieter_of[plr] -999, s:" for ", d:quieting_for[plr]);
	quieting_for[plr] = QUIETING_AMOUNT;
	ACS("QCDE_ZedekFireLevel", quieting_for[plr], plr+1000);
	while(quieting_for[plr] --> 0)
	{
		int t = QUIETING_PERIOD;
		while(t --> 0)
			if(GetActorProperty(plr+1000,APROP_HEALTH) > 0)
				delay(1);

		SetActivator(quieter_of[plr]);
		Thing_Damage(plr+1000, QUIETING_DAMAGE, MOD_LAVA);
		GiveInventory("HitBeepLow",1);
		ACS("QCDE_ZedekFireLevel", quieting_for[plr], plr+1000);
		if(GetActorProperty(plr+1000,APROP_HEALTH) <= 0) break;
		//log(n:plr+1, s:" gets quieted by ", d:quieter_of[plr], s:" -- ", n:quieter_of[plr] -999, s:" for ", d:quieting_for[plr]);
	}
	quieting_for[plr] = 0;
}



//---------------------------------
//		Inqusitor's Active


// This define must be float
#define SHIELD_PROLONGATION 1.5
Script "QCDE_Ability_Inquisitor" (void)
{
	int plr = PlayerNumber();
	if(tics[plr]) terminate;
	int stage = CheckInventory("InquisitorStageToken");

	// bots only activate second stage 5% of the clicks, about every 3rd ability use, at random
	if(stage == 1 && PlayerIsBot(PlayerNumber()) && random(0,20)) terminate;

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("InquisitorStageToken",1); // post-incrementing token count
	SetNetworkReplicationFlags( 0 );

	if(stage) terminate;

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("ReflectiveInProc",1);
	SetNetworkReplicationFlags( 0 );
	int baseDuration = GetDuration();
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", baseDuration);
	int t = baseDuration;
	while(t --> 0)
	{
		// stage 1: be stronk
		delay(1);
		stage = CheckInventory("InquisitorStageToken");
		if(stage > 1)
		{
			// stage 2: literally become shield and protec
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("ReflectiveCleanerProc",1);
			GiveInventory("BecomeShieldProc",1);
			SetNetworkReplicationFlags( 0 );
			ACS_NamedExecuteAlways("QCDE_Display_Shield_Message", 0, 0);

			int maxTics = baseDuration * SHIELD_PROLONGATION / 1.0;
			int moreTics = t * SHIELD_PROLONGATION / 1.0;
			ACS("QCDE_SetWeapon", "Shieldquisitor", moreTics);
			ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", maxTics, moreTics);

			int w;
			for(w = 0; w < NUMBER_OF_WEAPONS; w++)
				if(!stricmp(getWeapon(), weaponList[w]))
					break;

			t = moreTics; // prolonged duration
			while(t --> 0)
				if(GetActorProperty(0, APROP_Health) > 0) delay(1);
				else break;

			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("BecomeShieldCleanerProc",1);
			SetNetworkReplicationFlags( 0 );
			ACS_NamedExecuteAlways("QCDE_Clean_Shield_Message", 0, 0);

			delay(3); // add short delay before bringing up proper weapon, or else player can shoot his own shield with rocket

			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			//Unzoom if using toggle zoom
			if (!GetCVar("cl_holdZoom")) SetInventory("WeaponZoomedToken", 0);
			//Give and select fake weapon
			SetWeapon(weaponList[w]);
			//Remove ability weapon
			TakeInventory("Shieldquisitor",1);
			SetNetworkReplicationFlags( 0 );
			tics[plr] = 1;

			break; // exit outer loop
		}

		if(GetActorProperty(0, APROP_Health) <= 0) break;
	}
	tics[plr] = 0;
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("ReflectiveOutProc",1);
	SetNetworkReplicationFlags( 0 );
}

script "QCDE_Display_Shield_Message" (void)
{
	SetHUDsize(800,600,1);
	if(gametype()<=1)
		HUDmessage(s:"SP/Coop: Block only enemy attacks";HUDMSG_PLAIN,53,CR_GOLD,400.0,570.0,100.0);
	else if(gametype()>=2)
		HUDmessage(s:"Deathmatch: Block enemy and friendly attacks";HUDMSG_PLAIN,53,CR_GOLD,400.0,570.0,100.0);
}

script "QCDE_Clean_Shield_Message" (void)
{
		HUDmessage(s:" ";HUDMSG_PLAIN,53,CR_GOLD,400.0,570.0,0.3);
}


//---------------------------------
//		Bitterman's Active

Script "QCDE_Ability_Bitterman" (void)
{
	int howmuch = CheckInventory("PowerShieldCharge");
	int gameidentifierhere;
	// not more than max allowed, starting from
	int max = CheckInventory("MaxArmorToken") + 25 - CheckInventory("BasicArmor");
	if(howmuch > max) howmuch = max;

	if (GetNetworkState() != NETSTATE_CLIENT && !InDemoMode())
		GiveInventory("QCArmorPoint", howmuch);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	TakeInventory("PowerShieldCharge", howmuch);
	PlaySound(0,"QC/Abilities/Bitterman/ShieldRestore",CHAN_7,1.0,false,0.9);
	SetNetworkReplicationFlags( 0 );

	//The "Michaelis' Magic Code" that figures if it's coop, FFA or TDM!
	if(GameType() < GAME_NET_DEATHMATCH || CheckInventory("TeamDeathmatch"))
	{
		gameidentifierhere=2; // coop or TDM
	}
	else
	{
		gameidentifierhere=3; //FFA
	}

	// GetActorPitch is -0.25 at highest and +0.25 at lowest
	// Extra height goes from +26.0 at highest to -26.0 at lowest
	int extraheight = GetActorPitch(0) * 26 * -4;

	int x = GetActorX(0);
	int y = GetActorY(0);
	int z = GetActorZ(0) + 30.0 + extraheight;
	int count = CheckInventory("PowerShieldCharge");
	SetInventory("PowerShieldCharge", 0);
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	if(GetNetworkState() != NETSTATE_CLIENT && !InDemoMode() && gameidentifierhere != 3) //Not FFA
	{
		if(IsPVE()) count = count * FixedSqrt(PlayerCount() * 2.0) / 5.0;
		while(count --> 0)
		{
			SpawnForced("QCArmorBitterman", x,y,z);

			if(count % 40 == 0)
			{
				z += 4.0;
				delay(1);
			}
		}
	}

	delay(GetDuration());
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}


//---------------------------------
//		Galen's Active

Script "QCDE_Ability_Galen" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("TotemProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	ACS("QCDE_GalenHandAnimation");
	SetNetworkReplicationFlags( 0 );
	delay(GetDuration()); //duration of active ability
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}


Script "QCDE_GalenHandAnimation" (void) clientside
{
	// *.1 on x means "align to left", *.0 on y means "vertically centered"
	DrawWeapon("GLNHA0", -60.1, 250.0);	delay(1);
	DrawWeapon("GLNHA0", -30.1, 240.0);	delay(1);
	DrawWeapon("GLNHB0", -10.1, 230.0);	delay(1);
	DrawWeapon("GLNHB0",  10.1, 230.0);	delay(1);
	DrawWeapon("GLNHC0",  20.1, 210.0);	delay(1);
	DrawWeapon("GLNHC0",  30.1, 205.0);	delay(1);
	DrawWeapon("GLNHD0",  40.1, 200.0);	delay(1);
	DrawWeapon("GLNHD0",  45.1, 202.0);	delay(1);
	DrawWeapon("GLNHD0",  50.1, 205.0);	delay(1);
	DrawWeapon("GLNHC0",  55.1, 210.0);	delay(1);
	DrawWeapon("GLNHC0",  50.1, 215.0);	delay(1);
	DrawWeapon("GLNHB0",  40.1, 235.0);	delay(1);
	DrawWeapon("GLNHB0",  30.1, 255.0);	delay(1);
	DrawWeapon("GLNHA0",  20.1, 275.0);	delay(1);
	DrawWeapon("GLNHA0",  10.1, 295.0);	delay(1);
}


//---------------------------------
//		Nyx's Active

#define NYX_TRAIL_LENGTH 10
Script "QCDE_Ability_Nyx" (void)
{
	// Saving position to ghost-recall to if stuck
	int ox = GetActorX(0);
	int oy = GetActorY(0);
	int oz = GetActorZ(0);

	// Begin
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GhostWalkInProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration() + NYX_TRAIL_LENGTH);
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	// Disable remaining damage over time from possible Quietus hit or Postal's cow head
	quieting_for[PlayerNumber()] = 0;
	cowgassing_for[PlayerNumber()] = 0;

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0, "QC/Abilities/Nyx/GhostWalkStart", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
	SetNetworkReplicationFlags( 0 );

	// First loop: leaving slight trail
	int counter;
	while(counter++ < NYX_TRAIL_LENGTH) //for first N tics, it will spawn a trail every tic
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("GhostWalkTrailProc",1);
		SetNetworkReplicationFlags( 0 );
		delay(1);
	}

	// Main loop
	counter=0;
	while(counter <= GetDuration())
	{
		delay(5);
		counter += 5;
	}

	// Exit at destination
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GhostWalkOutProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteAlways("QCDE_RestoreIndicator",0);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0, "QC/Abilities/Nyx/GhostWalkEnd", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
	SetNetworkReplicationFlags( 0 );

	// Stuck check (not in PVP)
	if(IsPVP()) terminate;

	int nx = GetActorX(0);
	int ny = GetActorY(0);
	int nz = GetActorZ(0);
	SetActorVelocity(0, 0.1,0.1,0.1, true,true);
	delay(1);
	if(GetActorX(0) != nx || GetActorY(0) != ny || GetActorZ(0) != nz) terminate;
	SetActorVelocity(0, -0.2,-0.2,-0.2, true,true);
	delay(1);
	if(GetActorX(0) != nx || GetActorY(0) != ny || GetActorZ(0) != nz) terminate;

	// Got stuck, activate Ghost Recall
	SetActorPosition(0, ox,oy,oz, 0);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GhostWalkOutProc",1);
	SetNetworkReplicationFlags( 0 );
}



//---------------------------------
//		Sorgaul's Active

Script "QCDE_Ability_Sorgaul" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0,"QC/Abilities/Sorgaul/RageStart",CHAN_7,1.0,false,0.8);
	//PlaySound(0,"QC/Abilities/Sorgaul/RageLoop",CHAN_5,1.0,true,1.0); //has to be played through weapon itself
	SetNetworkReplicationFlags( 0 );

	if(PlayerIsBot(PlayerNumber()))
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("PrimalRageBotProc",1);
		SetNetworkReplicationFlags( 0 );
		ACS("QCDE_SetWeapon", "SorgaulFistsBot", GetDuration());
	}
	else
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("PrimalRageProc",1);
		SetNetworkReplicationFlags( 0 );
		ACS("QCDE_SetWeapon", "SorgaulFists", GetDuration());
	}
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	int w;
	for(w = 0; w < NUMBER_OF_WEAPONS; w++)
		if(!stricmp(getWeapon(), weaponList[w]))
			break;


	int t = GetDuration();
	while(t --> 0)
	{
		if(GetActorProperty(0,APROP_HEALTH) <= 0) break;
		delay(1);
	}

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	//Unzoom if using toggle zoom
	if (!GetCVar("cl_holdZoom")) SetInventory("WeaponZoomedToken", 0);
	//Give and select fake weapon
	SetWeapon(weaponList[w]);
	//Remove ability weapon
	GiveInventory("PrimalRageCleanerProc",1);
	TakeInventory("SorgaulFists",1);
	TakeInventory("SorgaulFistsBot",1);
	PlaySound(0,"QC/Abilities/Sorgaul/RageEnd",CHAN_7,1.0,false,1.0);
	StopSound(0, CHAN_5);
	SetNetworkReplicationFlags( 0 );
}


//---------------------------------
//		Duke Nukem's Active

Script "QCDE_Ability_DukeNukem" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0,"QC/Abilities/DukeNukem/PullWeapon",CHAN_7,1.0,false,0.5);
	GiveInventory("DukeFreezerProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS("QCDE_SetWeapon", "DukeFreezeThrower", GetDuration());

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	int w;
	for(w = 0; w < NUMBER_OF_WEAPONS; w++)
		if(!stricmp(getWeapon(), weaponList[w]))
			break;


	int t = GetDuration();
	while(t --> 0)
	{
		if(GetActorProperty(0,APROP_HEALTH) <= 0) break;
		delay(1);
	}

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	//Unzoom if using toggle zoom
	if (!GetCVar("cl_holdZoom")) SetInventory("WeaponZoomedToken", 0);
	//Give and select fake weapon
	SetWeapon(weaponList[w]);
	//Remove ability weapon
	GiveInventory("DukeFreezerCleanerProc",1);
	TakeInventory("DukeFreezeThrower",1);
	SetNetworkReplicationFlags( 0 );
}

#define BALLS_TIL_FREEZE 6
Script "QCDE_StartFreezeCounter" (void)
{
	if (GetNetworkState() == NETSTATE_CLIENT || InDemoMode())
		terminate;

	int t = 35*3;	//window to connect freezeballs to freeze solid
	int tokensnow, tokensbefore;

	tokensnow = checkinventory("ImFrozen");
	tokensbefore = tokensnow; //equalize them on initialization

	while(t>0)
	{
		tokensnow=checkinventory("ImFrozen");
		if(tokensnow>=BALLS_TIL_FREEZE)							//if it has X tokens, freeze for X seconds
		{
			//printbold(s:"Frozen solid");
			GiveInventory("IceCubePlayerProc",1);
			GiveInventory("ImFullyFrozen",1);
			GiveInventory("NoAbilitiesToken",1);
			SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);

			//Freeze for ~2.5sec
			delay(88);

			SyncPlayerNetwork( PlayerNumber() );
			SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
			TakeInventory("PowerIceProtection",1);
			delay(35);			//tiny window in which player cant be frozen again
			TakeInventory("ImFrozen",999); 			//then take the tokens afterwards
			TakeInventory("ImFullyFrozen",1); 		//then take the tokens afterwards
			if(!CheckInventory("Freezetagged"))
				TakeInventory("NoAbilitiesToken",1);
			t=0;									//set time to zero to end loop
		}
		else
		{
			if(tokensnow>tokensbefore)	//if it has one more token than it did before
			{
				GiveInventory("IceDamageTintProc",1);
				t=35*3;					//reset timer
				tokensbefore=tokensnow; //and equalizes them again for next count
			}
		}
		t--;
		//printbold(d:t);
		delay(1);
	}
	TakeInventory("ImFrozen",999); //when the script ends, remove all tokens
}


Script "CheckTargetFrozen" (void)
{
	int radius;
	SetActivator(0,AAPTR_PLAYER_GETTARGET);

	if(checkinventory("ImFrozen")>=1)
		SetResultValue(1);
	else
		SetResultValue(0);
}


// Activator: exploding freeze shot
script "QCDE_FreezeShotHits" (void)
{
	Thing_ChangeTid(0, FREEZESHOT_TIDBASE + GetActorProperty(0, APROP_TargetTID) - 1000);
}

// Activator: frostbitten victim
script "QCDE_HitByFreezeShot" (void)
{
	if (GetNetworkState() == NETSTATE_CLIENT || InDemoMode())
		terminate;

	// This distance goes from center of freeze shot to center of player,
	// so should have quite some wiggle room
	int radius = 50;
	int tokencount = CheckInventory("ImFrozen");

	if (tokencount < BALLS_TIL_FREEZE &&
		HostileRadiusCheck(FREEZESHOT_TIDBASE, radius, true))
	{
		if (tokencount == 0) //if it doesnt have any tokens prior
		{	ACS_NamedExecuteAlways("QCDE_StartFreezeCounter",0,0,0);	} //start the counter

		GiveInventory("FreezeSlowerer", 1);
		GiveInventory("ImFrozen",       1);
		ACS_NamedExecuteAlways("QCDE_FreezeIndicator_CLIENT",0,CheckInventory("ImFrozen") * (100 / BALLS_TIL_FREEZE));
	}
}


//---------------------------------
//		Durandal's Active

#define HOW_MANY_BOBS 4
#define HOW_MANY_BOBS_PVE 8
Script "QCDE_Ability_Durandal" (void)
{
	int counter;
	int How_Many_Bobs_PvX;
	if(IsPvE())
		How_Many_Bobs_PvX = HOW_MANY_BOBS_PVE;
	else
		How_Many_Bobs_PvX = HOW_MANY_BOBS;

	str BobType="SingleBOBSPProc";

	if(gametype()>=2)
		BobType="SingleBOBDMProc";

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0,"QC/Abilities/Durandal/Summon",CHAN_7,0.7,false,0.5);
	PlaySound(0,"QC/Abilities/Durandal/FBTVCrandom",CHAN_VOICE,1.0,false,0.7);
	SetNetworkReplicationFlags( 0 );

	if (GetNetworkState() == NETSTATE_CLIENT || InDemoMode())
		terminate;

	while(counter++ < How_Many_Bobs_PvX) //Spawn N bobs
	{
		GiveInventory(BobType,1);
		delay(3);
	}

	delay(GetDuration()); //duration of active ability

	// second check after time is up: have bobs spawned?
	int spawned = ThingCount(T_NONE, BOB_TIDBASE + PlayerNumber());
	while(spawned++ < How_Many_Bobs_PvX)
	{
		GiveInventory(BobType,1);
		delay(3);
	}
}


//---------------------------------
//		Keel's Active

Script "QCDE_Ability_Keel" (void)
{
	if(ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown()))
	{
		extraAbilityData[PlayerNumber()]++;
		SetLastUse(Timer());
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("KeelFireGrenProc",1); //Fire grenade
		SetNetworkReplicationFlags( 0 );
	}
}



//---------------------------------
//		Lo Wang's Active

Script "QCDE_Ability_LoWang" (void)
{
	int counter;
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("NobitsuraProc1",1);
	ACS("QCDE_NobitsuraAnimation");
	GiveInventory("ThirdPersonPunch",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	delay(12);

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("NobitsuraProc2",1);
	SetNetworkReplicationFlags( 0 );

	delay(7);

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	TakeInventory("ThirdPersonPunch",32767);
	SetNetworkReplicationFlags( 0 );
}

Script "QCDE_NobitsuraAnimation" (void) clientside
{
	// *.1 on coordinates means "align to top-left"
	DrawWeapon("QP18W0",  80.1, 200.1);	delay(1);
	DrawWeapon("QP18W0", 140.1, 250.1);	delay(1);
	DrawWeapon("QP18W0", 190.1, 300.1);	delay(1);
	DrawWeapon("QP18W0", 230.1, 330.1);	delay(1);
	DrawWeapon("QP18W0", 250.1, 360.1);

	delay(8);

	DrawWeapon("QP18X0",  300.1, 180.1);	delay(1);
	DrawWeapon("QP18X0",  250.1, 187.1);	delay(1);
	DrawWeapon("QP18X0",  175.1, 194.1);	delay(1);
	DrawWeapon("QP18X0",   75.1, 201.1);	delay(1);
	DrawWeapon("QP18X0",    0.1, 208.1);	delay(1);
	DrawWeapon("QP18X0",  -75.1, 215.1);	delay(1);
	DrawWeapon("QP18X0", -225.1, 229.1);	delay(1);
	DrawWeapon("QP18X0", -400.1, 400.1);	//away from sight to remove without fadeout
}


//---------------------------------
//		Grayson's Active


#define TICS_BEFORE_THUMPER  27
#define TICS_FOR_THUMPER     30
#define TICS_BETWEEN_SPARKS   2

Script "QCDE_Ability_Grayson" (void)
{
	if(tics[PlayerNumber()]) terminate;
	if(CheckInventory("ThumperArmingToken")) terminate;

	int i;

	if(CheckInventory("ThumperReadyToken"))
	{
		// Second press on ability key signalling to fire
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		TakeInventory("ThumperReadyToken",1);
		SetNetworkReplicationFlags( 0 );
		terminate;
	}

	//Stop regular weapons and show ability used
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("DisableWeaponProc",1);
	GiveInventory("ThumpSoundAndHaloProc",1);
	GiveInventory("ThumperArmingToken",1);
	SetNetworkReplicationFlags( 0 );

	//Spawn player sparks
	while(i < TICS_BEFORE_THUMPER)
	{
		if(GetActorProperty(0, APROP_HEALTH) <= 0) break;

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("PlayerThumpSparkerProc",1);
		GiveInventory("ActiveProgressToken",256 * TICS_BETWEEN_SPARKS / TICS_BEFORE_THUMPER);
		SetNetworkReplicationFlags( 0 );
		Delay(TICS_BETWEEN_SPARKS);
		i += TICS_BETWEEN_SPARKS;
	}

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration() - TICS_BEFORE_THUMPER);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	TakeInventory("ThumperArmingToken",1);
	GiveInventory("ThumperReadyToken",1);
	SetNetworkReplicationFlags( 0 );

	//Continue spawning sparks, and fire when ready
	while(i < GetDuration())
	{
		if(GetPlayerInput(-1, MODINPUT_BUTTONS) & BT_ATTACK) break;
		if(GetActorProperty(0, APROP_HEALTH) <= 0) break;
		if(!CheckInventory("ThumperReadyToken")) break; // means other instance sends signal to fire

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("PlayerThumpSparkerProc",1);
		SetNetworkReplicationFlags( 0 );
		Delay(TICS_BETWEEN_SPARKS);
		i += TICS_BETWEEN_SPARKS;
	}

	//Fire projectile
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("ThumperShootProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	Delay(5);	//slight delay before he can shoot again

	//Clean the rest
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}


//When thumper hits -- should happen immediately before ThumperAffected
int thumperOwner;
Script "QCDE_ThumperHit" (void)
{
	SetActivatorToTarget(0);
	thumperOwner = PlayerNumber();
	//log(s:"\c[brite]Thumper hit. Owner: ", n:0, s:" -- #", d:thumperOwner);
}

//When a player gets hit by the thumper -- should happen immediately after ThumperHit
#define THUMPER_THRUSTZ 15
Script "QCDE_ThumperAffected" (void)
{
	int victim = PlayerNumber();
	if(!HostileCheck(thumperOwner, true)) {
		//log(s:"\c[black]Thumper thrown by ", n:-~thumperOwner, s:" -- #", d:thumperOwner, s:" harmlessly skips ", n:0, s:" -- #", d:victim);
		terminate;
	}

	//log(s:"\c[bludi]Thumper thrown by ", n:-~thumperOwner, s:" -- #", d:thumperOwner, s:" affects ", n:0, s:" -- #", d:victim);
	SetPlayerProperty(0,1,PROP_FROZEN);
	Thing_Stop(0);
	GiveInventory("GrayThumperFlight",1);
	GiveInventory("Twitchless3sec",1);
	ThrustThingZ(0,THUMPER_THRUSTZ * 4,0,0);

	int t = 35, velz, hit; //only lasts 1 sec
	while(t --> 0)
	{
		if(GetActorVelZ(0) == 0 && !hit)
		{
			if(GetActorProperty(0, APROP_HEALTH) >= 0)
			{
				GiveInventory("ThumperHitCeilingProc",1);

				SetActivator(1000 + thumperOwner);
				// Activator: thumper thrower

				int dmg = 40 + velz / 1.0 * 5;
				Thing_Damage(1000 + victim, dmg, MOD_SPLASH);
				GiveInventory("HitBeepMid",1);
				//log(s:"\c[bludi]", n:-~victim, s:" -- #", d:thumperOwner, s:" hits the ceiling! +", d:dmg, s:" damage!");

				SetActivator(1000 + victim);
				// Activator: thumper victim
			}
			hit = true;
		}
		velz = GetActorVelZ(0);
		if(velz < 0) velz = 0;
		SetActorVelocity(0, 0,0,0.05, true,false); // QZan only! Ensure some upward momentum for the ceiling check to work
		delay(1);
	}

	SetActivator(1000 + victim);
	SetPlayerProperty(0,0,PROP_FROZEN);

	if(!checkinventory("PowerCorvusFlight"))	//if corvus flying, skip removing flight, since he'll lose it automatically
		TakeInventory("PowerGrayThumpFlight",1);
}

// Activator: somebody already caught in radius
function int HostileCheck (int friendOrFoe, int blockable)
{
	// if not DM, skip
	if(GameType() < GAME_NET_DEATHMATCH) return false;

	if(blockable)
	{
		// if this player is invulnerable by ability, skip
		if(CheckInventory("PowerGhostTint")) return false;    //doesnt affect ghostwalking nyx
	}

	// if the projectile is your own, skip
	if(friendOrFoe == PlayerNumber()) return false;

	// if that player is on same team in TDM, skip
	if (CheckInventory("TeamDeathmatch") &&
		GetPlayerInfo(friendOrFoe,    PLAYERINFO_TEAM) ==
		GetPlayerInfo(PlayerNumber(), PLAYERINFO_TEAM))
		return false;

	return true;
}


//---------------------------------
//		Eradicator's Active

Script "QCDE_Ability_Eradicator" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0, "QC/Abilities/Eradicator/Radar", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	for(int t = GetDuration(); t; t--)
	{
		// ensures radar persists regardless of possible death
		if(!CheckInventory("Radar") && CheckInventory("Class_Eradicator"))
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("Radar",1);
			SetNetworkReplicationFlags( 0 );
		}
		if(!CheckInventory("ActiveInProgress"))
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("ActiveInProgress",1);
			SetNetworkReplicationFlags( 0 );
			ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", t);
		}
		delay(1);
	}

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}

//---------------------------------
//		Blazkowicz's Active

Script "QCDE_Ability_Blazkowicz" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0,"QC/Abilities/Blazkowicz/AbilityVoice",CHAN_VOICE,0.75,false,1.0);
	SetPlayerProperty(0,1,PROP_INSTANTWEAPONSWITCH);
	SetNetworkReplicationFlags( 0 );

	if(PlayerIsBot(PlayerNumber()))
	{
		GiveInventory("AkimboBotProc",1);
		ACS("QCDE_SetWeapon", "BlazkoAkimboBot", GetDuration());
	}
	else
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("AkimboProc",1);
		SetNetworkReplicationFlags( 0 );
		ACS("QCDE_SetWeapon", "BlazkoAkimbo", GetDuration());
	}

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	int w;
	for(w = 0; w < NUMBER_OF_WEAPONS; w++)
		if(!stricmp(getWeapon(), weaponList[w]))
			break;


	int t = GetDuration();
	while(t --> 0)
	{
		if(GetActorProperty(0,APROP_HEALTH) <= 0) break;
		delay(1);
	}

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	//Unzoom if using toggle zoom
	if (!GetCVar("cl_holdZoom")) SetInventory("WeaponZoomedToken", 0);
	//Give and select fake weapon
	SetWeapon(weaponList[w]);
	//Remove ability weapon
	GiveInventory("AkimboCleanerProc",1);
	TakeInventory("BlazkoAkimbo",1);
	TakeInventory("BlazkoAkimboBot",1);
	SetNetworkReplicationFlags( 0 );
}

script "BJTimerLeft" (void)
{
	delay(28);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	TakeInventory("BJLeft",1);
	SetNetworkReplicationFlags( 0 );
}
script "BJTimerRight" (void)
{
	delay(28);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	TakeInventory("BJRight",1);
	SetNetworkReplicationFlags( 0 );
}


//---------------------------------
//		Freeman's Active

Script "QCDE_Ability_Freeman" (void)
{
	if(ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown()))
	{
		extraAbilityData[PlayerNumber()]++;
		SetLastUse(Timer());
		if(checkInventory("DMToken"))	//DM version does 3 blasts to deflect projectiles
		{
			ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("PvPBlastInitialProc",1); //spawns FX, deals 10dmg of explosion, and A_Blast
			SetNetworkReplicationFlags( 0 );
			Delay(6);
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("PvPBlastExtraProc",1); //does only A_Blast
			SetNetworkReplicationFlags( 0 );
			Delay(6);
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("PvPBlastExtraProc",1); //does only A_Blast
			SetNetworkReplicationFlags( 0 );
			delay(GetDuration()-12); //duration of ability, minus x tics due to those 2 "delay(y)"
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("GenericActiveCleanerProc",1);
			SetNetworkReplicationFlags( 0 );
		}
		else		//PvE version does a single a_blast that pushes enemies and deals damage to them
		{
			ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("PvEBlastProc",1); //spawns FX and A_Blast
			SetNetworkReplicationFlags( 0 );
			delay(GetDuration()); //duration of active ability
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("GenericActiveCleanerProc",1);
			SetNetworkReplicationFlags( 0 );
		}
	}
}


//---------------------------------
//		VorMatur's Active

Script "QCDE_Ability_VorMatur" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("DarkeningProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	Delay(GetDuration());
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}

int darkener_now;
Script "QCDE_DarkeningShotHits" (void)
{
	darkener_now = GetActorProperty(0, APROP_TargetTID) - 1000;
}

#define DARKEN_DURATION 1.5
#define DARKEN_FADEIN   0.1
#define DARKEN_FADEOUT  1.0
Script "QCDE_DarkenedVictim" (void)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate; // DM-only

	if(!isEnemy(darkener_now)) terminate; // don't darken allies

	ACS("QCDE_Darkening_Start", DARKEN_DURATION, DARKEN_FADEIN, DARKEN_FADEOUT);

	if(PlayerIsBot(PlayerNumber())) GiveInventory("NoWeaponFireToken",1);

	SetNetworkReplicationFlags( NETREP_NOUNLAGGED );
	SpawnProjectile(0, "BlindVisualizer", 0,0,0,0,0);
	SetNetworkReplicationFlags( 0 );

	int t = (DARKEN_DURATION + DARKEN_FADEIN + DARKEN_FADEOUT) * 35 / 1.0;
	while(t --> 0)
		if(GetActorProperty(0, APROP_HEALTH) > 0)
			delay(1);
		else
		{
			// Remove darkness if died
			ACS("QCDE_Darkening_Stop");
			TakeInventory("NoWeaponFireToken",1);
			terminate;
		}

	if(PlayerIsBot(PlayerNumber())) TakeInventory("NoWeaponFireToken",1);
}

//---------------------------------
//		Eleena's Active

Script "QCDE_Ability_Eleena" (void)
{
	if(tics[PlayerNumber()] && !CheckInventory("ActiveProgressToken")) terminate;

	int plrtid = ActivatorTid();
	int doptid = plrtid - 1000 + DOPPELGANG_TIDBASE;

	int px = GetActorX(0); int pxs = GetActorVelX(0);
	int py = GetActorY(0); int pys = GetActorVelY(0);
	int pz = GetActorZ(0); int pzs = GetActorVelZ(0);
	int pan = GetActorAngle(0);
	int ppi = GetActorPitch(0);

	// Spawn Doppelganger
	if(!tics[PlayerNumber()])
	{
		SetActorState(doptid, "Vanish"); // Vanish other possible doppelgangers

		if (GetNetworkState() != NETSTATE_CLIENT && !InDemoMode())
		{
			SpawnForced("Doppelganger", px,py,pz, doptid, pan >> 8);
			SetActorVelocity(doptid, pxs,pys,pzs, false, true);
			GiveActorInventory(doptid, "TeamColor", CheckInventory("TeamColor"));
			giveEleenaCloneWeaponSkins(doptid);

			int translation = GetActorProperty(plrtid, APROP_Translation);
			SetActorProperty(doptid, APROP_Translation, translation);

			ACS("QCDE_ColorDoppelganger_CLIENTSIDE");
		}

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("PowerShieldCharge", 3);
		SetNetworkReplicationFlags( 0 );

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("ActiveInProgress",1);
		SetNetworkReplicationFlags( 0 );
		ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
		ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		PlaySound(0,"QC/Abilities/Eleena/Activate",CHAN_AUTO,1.0,0,1.5);
		SetNetworkReplicationFlags( 0 );

		if (GetNetworkState() != NETSTATE_CLIENT && !InDemoMode())
		{
			SetActivator(doptid);
			SetPointer(AAPTR_MASTER,plrtid);
			SetActivator(plrtid);
		}

		int t = GetDuration();
		while(t --> 0) delay(1);

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("PowerShieldCharge", 0);
		GiveInventory("GenericActiveCleanerProc", 1);
		SetNetworkReplicationFlags( 0 );
		terminate;
	}

	if(!CheckInventory("ActiveProgressToken")) terminate;

	if(!CheckInventory("PowerShieldCharge")) terminate;
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	TakeInventory("PowerShieldCharge", 1);
	SetNetworkReplicationFlags( 0 );

	// dx, dy, dz, pxs, pys, pzs, dxs, dys, dzs
	int dx = GetActorX(doptid); int dxs = GetActorVelX(doptid);
	int dy = GetActorY(doptid); int dys = GetActorVelY(doptid);
	int dz = GetActorZ(doptid); int dzs = GetActorVelZ(doptid);
	//int dan = GetActorAngle(doptid);
	//int dpi = GetActorPitch(doptid);

	SetPredictableValue(0, 0, 1);
	SetPredictableValue(0, 1, dx);
	SetPredictableValue(0, 2, dy);
	SetPredictableValue(0, 3, dz);
	SetPredictableValue(0, 4, dxs);
	SetPredictableValue(0, 5, dys);
	SetPredictableValue(0, 6, dzs);
	//SetPredictableValue(0, 7, dan);
	//SetPredictableValue(0, 8, dpi);

	// warp p to d; thrust p like d; turn p like d
	int recalltid = UniqueTid();
	if (GetNetworkState() != NETSTATE_CLIENT && !InDemoMode())
	{
		SpawnForced("MapSpot", px,py,pz, recalltid);
	}

	Warp(0, dx, dy, dz, 0, WARPF_ABSOLUTEPOSITION|WARPF_NOCHECKPOSITION);
	SetActorVelocity(plrtid, dxs,dys,dzs, false, true);
	//SetActorAngle(plrtid, dan);
	//SetActorPitch(plrtid, dpi);

	// warp d to p; thrust d like p; turn d like p
	if (GetNetworkState() != NETSTATE_CLIENT && !InDemoMode())
	{
		GiveActorInventory(doptid, "DrawAttentionProc", 1);
		Thing_Move(doptid, recalltid, true);
		GiveActorInventory(doptid, "DrawAttentionProc", 1);
		SetActorVelocity(doptid, pxs,pys,pzs, false, true);
		SetActorAngle(doptid, pan);
		SetActorPitch(doptid, ppi);

		Thing_Remove(recalltid);
	}

	// FX
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(doptid,"QC/Abilities/Eleena/SwapFake",CHAN_AUTO,1.0,false,1.5); // fake Eleena sound
	GiveInventory("EleenaSwapProc",1);
	SetNetworkReplicationFlags( 0 );
}

Script "QCDE_ColorDoppelganger_CLIENTSIDE" (void) CLIENTSIDE
{
	int plrtid = ActivatorTid();
	int plr = plrtid - 1000;
	int conplr = ConsolePlayerNumber();

	int doptid = plr + DOPPELGANG_TIDBASE;

	bool teamplay       = getCvar("teamplay");
	bool teamlms        = getCvar("teamlms");
	bool teampossession = getCvar("teampossession");
	bool teamgame       = getCvar("teamgame");

	// Your own is always cyan
	if (plr == conplr || PlayerIsSpectator(conplr))
		Thing_SetTranslation(doptid, TRANSLATION_LGCOLOR);
	// Teammates also see the clone
	else if((teamplay || teamlms || teampossession || teamgame) && (GetPlayerInfo(plr, PLAYERINFO_TEAM) == GetPlayerInfo(conplr, PLAYERINFO_TEAM)))
		Thing_SetTranslation(doptid, TRANSLATION_LGCOLOR);
}

#define DURATION_DOPPELGANGER 15
Script "QCDE_DoppelgangerSpawned" (void)
{
	if(CheckInventory("NotSpectator")) terminate;
	GiveInventory("NotSpectator",true);

	if(GetCvar("rocketarena")) GiveInventory(getRocketArenaWeaponName(), 1); // needs rework
	if(GetCvar("instagib"   )) GiveInventory(getInstagibWeaponName(), 1);

	delay(DURATION_DOPPELGANGER * 35);
	SetActorState(0, "Vanish");
}

// Activator: Player
script "QCDE_EleenaSwapPredictedUse" (void)
{
	int posX = GetPredictableValue(0, 1);
	int posY = GetPredictableValue(0, 2);
	int posZ = GetPredictableValue(0, 3);
	int velX = GetPredictableValue(0, 4);
	int velY = GetPredictableValue(0, 5);
	int velZ = GetPredictableValue(0, 6);
	//int angle = GetPredictableValue(0, 7); // pitch and angle are commented out in activation script
	//int pitch = GetPredictableValue(0, 8);
	Warp(0, posX, posY, posZ, 0, WARPF_ABSOLUTEPOSITION|WARPF_NOCHECKPOSITION);
	SetActorVelocity(0, velX,velY,velZ, false, true);
	//SetActorAngle(0, angle);
	//SetActorPitch(0, pitch);
}


//---------------------------------
//		Lucienne's Active

#define LUCIENNE_MIN_DAMAGE    25
#define LUCIENNE_MAX_DAMAGE  2000
#define LUCIENNE_HURT_PERCENT  10
#define LUCIENNE_HEAL_PERCENT  20

Script "QCDE_Ability_Lucienne" (void)
{
	if(ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown()))
	{
		extraAbilityData[PlayerNumber()]++;
		SetLastUse(Timer());
		ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("LucienneFireBallProc",1); //Fire ball
		ACS("QCDE_LucienneHandAnimation");
		SetNetworkReplicationFlags( 0 );
	}
}

int currentCleanser;
Script "QCDE_LucienneBallHits" (void)
{
	currentCleanser = GetActorProperty(0, APROP_TargetTID) - 1000;
}

#define LUCIENNE_CURSE_DURATION  100
#define LUCIENNE_TINT_DURATION 99999
Script "QCDE_Cleansed" (void)
{
	//log(n:0, s:" cleansed by ", n:currentCleanser + 1);

	if(isEnemy(currentCleanser))
		CleanseHurt();
	else
		CleanseHeal();

	while(GetActorPowerupTics(0,"PowerCleanVulnerable") > LUCIENNE_TINT_DURATION - LUCIENNE_CURSE_DURATION) delay(1);
	TakeInventory("PowerCleanVulnerable", 1);
	TakeInventory("CleansingWeakener", 1);
}

function void CleanseHeal(void)
{
	int maxhp = CheckInventory("MaxHealthToken");
	if(!maxhp) maxhp = GetActorProperty(0, APROP_SPAWNHEALTH);
	int heal = maxhp * LUCIENNE_HEAL_PERCENT / 100;
	HealThingEx(heal);

	// Reduce damages over time
	int plr = PlayerNumber();
	if(cowgassing_for[plr]) cowgassing_for[plr]--;
	if(  quieting_for[plr])   quieting_for[plr]--;

	GiveInventory("CleansingHealProc", 1);
}

function void CleanseHurt(void)
{
	int maxhp = CheckInventory("MaxHealthToken");
	if(!maxhp) maxhp = GetActorProperty(0, APROP_SPAWNHEALTH);

	int hurt = maxhp * LUCIENNE_HURT_PERCENT / 100;
	if(GameType() <= GAME_NET_COOPERATIVE && hurt < LUCIENNE_MIN_DAMAGE)
		hurt = LUCIENNE_MIN_DAMAGE; // ensure minimum damage in PvE
	// cap max damage
	if(hurt > LUCIENNE_MAX_DAMAGE) hurt = LUCIENNE_MAX_DAMAGE;

	GiveInventory("CleansingHurtProc", 1);

	int victim = ActivatorTid(), temptid;
	if(!victim) // special case to prevent Lucienne from hurting herself when enemy had no tids
	{
		temptid = true;
		victim = UniqueTid();
		Thing_ChangeTID(0,victim);
	}
	SetActivator(currentCleanser + 1000);
	Thing_Damage2(victim, hurt, "Cleanse");
	SetActivator(victim);
	if(temptid)
	{
		Thing_ChangeTID(0,0);
	}
}

Script "QCDE_LucienneHandAnimation" (void) clientside
{
	// *.0 on coordinates means "align to center"
	DrawWeapon("QP25Y0",  60.0, 310.0);	delay(1);
	DrawWeapon("QP25Y0", 100.0, 290.0);	delay(1);
	DrawWeapon("QP25Y0", 140.0, 270.0);	delay(1);
	DrawWeapon("QP25Y0", 160.0, 250.0); delay(1);
	DrawWeapon("QP25Y0", 160.0, 270.0); delay(1);
	DrawWeapon("QP25Y0", 160.0, 270.0); delay(1);
	DrawWeapon("QP25Z0", 160.0, 290.0); delay(1);
	DrawWeapon("QP25Z0", 160.0, 310.0); delay(1);
	DrawWeapon("QP25Z0", 160.0, 340.0); delay(1);
	DrawWeapon("QP25Z0", 160.0, 380.0); delay(1);
	DrawWeapon("QP25Z0", 160.0, 980.0); delay(1);
}

//---------------------------------
//		Major's Active

#define MAJOR_ROCKETS   4

Script "QCDE_Ability_Major" (void)
{
	int rocketsfired=0;
	int duration;
	int imabot;
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("ActiveInProgress",1);
	GiveInventory("NoWeaponFireToken",1);

	GiveInventory("StrikesCounter",MAJOR_ROCKETS);

	//PlaySound(0, "QC/Abilities/Major/IncomingVO", CHAN_VOICE, 1.0, false, 1.0);
	PlaySound(0, "QC/Abilities/Major/Activate", 7, 0.8, false, 0.3);
	SetNetworkReplicationFlags( 0 );

	if(PlayerIsBot(PlayerNumber()))
		imabot=1;

	ACS("QCDE_MajorCharges", MAJOR_ROCKETS);

	while(rocketsfired < MAJOR_ROCKETS && duration<= GetDuration())
	{
		if (GetPlayerInput(-1, INPUT_BUTTONS) & BT_ATTACK || imabot>=1 )
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			GiveInventory("MajorAirStrikeProc",1);
			AmbientSound("QC/Abilities/Major/Launch",64);	//everyone hears it low
			rocketsfired++;
			TakeInventory("StrikesCounter",1);
			SetNetworkReplicationFlags( 0 );
			ACS("QCDE_MajorCharges", CheckInventory("StrikesCounter"), true);
			delay(10);
			duration=duration+10;
		}
		duration++;
		delay(1);
		if(GetActorProperty(0,APROP_HEALTH) <= 0)
		{
			while(rocketsfired<MAJOR_ROCKETS)
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				GiveInventory("MajorAirStrikeShortProc",1);
				rocketsfired++;
				TakeInventory("StrikesCounter",1);
				SetNetworkReplicationFlags( 0 );
				ACS("QCDE_MajorCharges", CheckInventory("StrikesCounter"), true);
				delay(10);
			}
		}
	}

	while(CheckInventory("StrikesCounter"))
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		TakeInventory("StrikesCounter",1);
		SetNetworkReplicationFlags( 0 );
		ACS("QCDE_MajorCharges", CheckInventory("StrikesCounter"), true);
	}
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}


Script "QCDE_StrikeSetter" (void)
{
	Thing_ChangeTID(0,GetActorProperty(0, APROP_TargetTID) - 1000 + STRIKESET_TIDBASE);
}

Script "QCDE_BombIncoming" (void)
{
	int plrtid = GetActorProperty(0, APROP_TargetTID);

	int translation = GetActorProperty(plrtid, APROP_Translation);
	SetActorProperty(0, APROP_Translation, translation);
}



//---------------------------------
//		Hunter's Active

Script "QCDE_Ability_Hunter" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("HunterSkullProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	delay(GetDuration()); //duration of active ability
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("HunterCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}

Script "QCDE_SkullSpawned" (void)
{
	int tid = ActivatorTid();
	int plr = tid - SKULL_TIDBASE;
	int plrtid = plr + 1000;

	GiveInventory("TargetForgetter",1);
	SetPointer(AAPTR_MASTER, plrtid);

	if(GameType() <= GAME_NET_COOPERATIVE) GiveInventory("FriendlyProc",1);

	while(GetActorProperty(plrtid, APROP_HEALTH) > 0 && !CheckActorInventory(plrtid, "Freezetagged"))
		delay(1);
	Thing_Remove(tid);
	//ACS("iamamiwhoami");
}

Script "QCDE_ReattributeToMaster" (void)
{
	SetPointer (AAPTR_TARGET,
				GetActorProperty(0, APROP_TargetTID) - SKULL_TIDBASE + 1000);

	//ACS("iamamiwhoami");
}

Script "QCDE_HasLivingTarget" (void)
{
	int tid1 = ActivatorTid();
	SetActivatorToTarget(0);
	int tid2 = ActivatorTid();
	int hp = GetActorProperty(0, APROP_HEALTH);

	bool enemies = GameType() <= GAME_NET_COOPERATIVE  ||  areEnemies((tid1 - 1000) % 64, (tid2 - 1000) % 64);

	SetResultValue(
			tid2  &&
			tid1 != tid2  &&
			(tid1 - SKULL_TIDBASE) != (tid2 - 1000)  &&
			hp > 0  &&
			enemies);
}


//---------------------------------
//		Serious Sam's Active

Script "QCDE_Ability_Sam" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0,"QC/Abilities/Sam/Activate",CHAN_7,0.85,false,0.5);
	GiveInventory("SamMinigunProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS("QCDE_SetWeapon", "SamMinigun", GetDuration());

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	// Rocket arena special case: disable infinite ammo for duration
	if(CheckInventory("RocketArena")) TakeInventory("PowerInfiniteAmmo",1);

	// Store previously used weapon
	int w;
	for(w = 0; w < NUMBER_OF_WEAPONS; w++)
		if(!stricmp(getWeapon(), weaponList[w]))
			break;


	// Main loop
	int t = GetDuration();
	while(t --> 0)
	{
		if(CheckInventory("SeriousBullets") <= 0) t = 0;
		if(GetActorProperty(0,APROP_HEALTH) <= 0) break;
		delay(1);
	}

	// Break progress meter: 1 total duration, 1 remaining tic
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", 1, 1);

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	//Unzoom if using toggle zoom
	if (!GetCVar("cl_holdZoom")) SetInventory("WeaponZoomedToken", 0);
	//Give and select fake weapon
	SetWeapon(weaponList[w]);
	//Remove ability weapon
	GiveInventory("SamMinigunCleanerProc",1);
	TakeInventory("SamMinigun",1);
	If(CheckInventory("DMToken"))	//this if is no longer needed, kept "just in case" in the future
		GiveInventory("SeriousBullets",80);
	else
		GiveInventory("SeriousBullets",GetAmmoCapacity("SeriousBullets"));
	SetNetworkReplicationFlags( 0 );

	// Rocket arena special case: reenable infinite ammo for duration
	if(CheckInventory("RocketArena"))
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("EndlessInfiniteAmmo",1);
		SetNetworkReplicationFlags( 0 );
	}
}


//---------------------------------
//		Postal Dude's Active

Script "QCDE_Ability_Postal" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("PostalCowProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS("QCDE_SetWeapon", "PostalCowHead", GetDuration());

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	int w;
	for(w = 0; w < NUMBER_OF_WEAPONS; w++)
		if(!stricmp(getWeapon(), weaponList[w]))
			break;


	int t = GetDuration();
	while(t --> 0 )
	{
		if(checkinventory("CowHeadToken")<= 0) t=0;
		if(GetActorProperty(0,APROP_HEALTH) <= 0) break;
		delay(1);
	}

	// Break progress meter: 1 total duration, 1 remaining tic
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", 1, 1);

	if(checkinventory("CowHeadToken"))
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("PostalCowDropProc",1);
		TakeInventory("CowHeadToken",1);
		SetNetworkReplicationFlags( 0 );
	}

	//Give and select fake weapon
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetWeapon(weaponList[w]);
	//Remove ability weapon
	GiveInventory("PostalCowCleanerProc",1);
	TakeInventory("PostalCowHead",1);
	SetNetworkReplicationFlags( 0 );
}




int last_cowgasser;
Script "QCDE_CowGasHit" (void)
{
	last_cowgasser = GetActorProperty(0, APROP_TargetTID);
	//log(s:"Last cowgasser is set to ", d:last_cowgasser, s:" -- ", n:last_cowgasser -999);
}

int cowgassing_for[64], cowgasser_of[64];
#define COWGASSING_AMOUNT     9
#define COWGASSING_INCREMENT  1
#define COWGASSING_DAMAGE     9
#define COWGASSING_PERIOD    35
Script "QCDE_CowGasVictim" (void)
{
	int plr = PlayerNumber(), victid = plr + 1000;
	if(!isEnemy(last_cowgasser - 1000)) terminate; // No self nor team damage
	cowgasser_of[plr] = last_cowgasser;

	// Already gassed by somebody? Update the other script
	if(cowgassing_for[plr])
	{
		cowgassing_for[plr] += COWGASSING_INCREMENT;
		//log(n:plr+1, s:" updates gasser ", d:cowgasser_of[plr], s:" -- ", n:cowgasser_of[plr] -999, s:" and duration to ", d:cowgassing_for[plr]);
		terminate;
	}

	// New gassing
	//log(n:plr+1, s:" gets gassed by cow of ", d:cowgasser_of[plr], s:" -- ", n:cowgasser_of[plr] -999, s:" for ", d:cowgassing_for[plr]);
	cowgassing_for[plr] = COWGASSING_AMOUNT;
	ACS("QCDE_CowGasLevel", cowgassing_for[plr], victid);
	while(cowgassing_for[plr] --> 0)
	{
		if(CheckActorInventory(victid, "PowerGhostTint")) break;

		SetActivator(cowgasser_of[plr]);

		if(PlayerNumber() == -1) break; // if player disconnected

		if(!CheckActorInventory(victid, "Class_Freeman"))
			Thing_Damage(victid, COWGASSING_DAMAGE, MOD_WATER); // MOD_WATER ignores armor
		else // Freeman ignores water though :shrug:
			Thing_Damage(victid, COWGASSING_DAMAGE, MOD_POISON);

		if(!CheckActorInventory(victid, "Freezetagged"))
		{
			GiveActorInventory(victid, "VomitBloodProc",1);
			GiveInventory("HitBeepLow",1);
		}

		ACS("QCDE_CowGasLevel", cowgassing_for[plr], victid);
		if(GetActorProperty(victid,APROP_HEALTH) <= 0) break;
		//log(n:plr+1, s:" gets gassed by cow of ", d:cowgasser_of[plr], s:" -- ", n:cowgasser_of[plr] -999, s:" for ", d:cowgassing_for[plr]);

		int t = COWGASSING_PERIOD;
		while(t --> 0)
			if(GetActorProperty(victid,APROP_HEALTH) > 0)
				delay(1);
	}
	cowgassing_for[plr] = 0;
}



//---------------------------------
//		Painkiller's Active

#define CARD_BUTTONS (BT_MOVELEFT|BT_FORWARD|BT_MOVERIGHT)
#define CARD_SELECT_TIME 150
#define CARD_CD_PENALTY_DIVISOR 3
#define CARDS_TO_PICK 3

Script "QCDE_Ability_Painkiller" (void)
{
	int buttons, oldbuttons, triggers;
	int lastTapValue, ws_axis, ad_axis;
	int card1, card2, card3, cards, time;
	int plr = PlayerNumber();

	// Prefill buttons
	buttons = 0;
	ws_axis = GetPlayerInput(plr, INPUT_FORWARDMOVE);
	ad_axis = GetPlayerInput(plr, INPUT_SIDEMOVE);
	if(ws_axis > 0) buttons |= BT_FORWARD;
	if(ad_axis < 0) buttons |= BT_MOVELEFT;
	if(ad_axis > 0) buttons |= BT_MOVERIGHT;

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	// Sound cue
	PlaySound(0,"QC/Abilities/Painkiller/Choose",CHAN_7,1.0,false,0.9);

	// Input stage
	GiveInventory("ActiveInProgress",1);
	SetNetworkReplicationFlags( 0 );
	if(!PlayerIsBot(PlayerNumber()))
	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		// "Make your selection" visuals
		if(time % 35 == 0)
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			ACS("QCDE_Tarot_Hint");
			SetNetworkReplicationFlags( 0 );
		}

		oldbuttons = buttons;
		buttons = 0;
		ws_axis = GetPlayerInput(plr, INPUT_FORWARDMOVE);
		ad_axis = GetPlayerInput(plr, INPUT_SIDEMOVE);
		if(ws_axis > 0) buttons |= BT_FORWARD;
		if(ad_axis < 0) buttons |= BT_MOVELEFT;
		if(ad_axis > 0) buttons |= BT_MOVERIGHT;
		triggers = buttons & ~oldbuttons;

		if (triggers & CARD_BUTTONS && !oldbuttons)
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			if(triggers & BT_MOVELEFT)  { ACS("QCDE_Tarot_Hint_Success", 1, ++card1, ++cards); lastTapValue = 1; }
			if(triggers & BT_FORWARD)   { ACS("QCDE_Tarot_Hint_Success", 2, ++card2, ++cards); lastTapValue = 2; }
			if(triggers & BT_MOVERIGHT) { ACS("QCDE_Tarot_Hint_Success", 3, ++card3, ++cards); lastTapValue = 3; }
			SetNetworkReplicationFlags( 0 );
		}

		if(cards >= CARDS_TO_PICK) break;
		if(time++ > CARD_SELECT_TIME) break;
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("ActiveProgressToken",256 * time / CARD_SELECT_TIME);
		SetNetworkReplicationFlags( 0 );

		// Oops! Turned into a demon
		if(CheckInventory("PowerDemonMorph"))
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			SetInventory("ActiveProgressToken",no);
			SetInventory("ActiveInProgress",no);
			ACS("QCDE_Tarot_Hint_End");
			SetNetworkReplicationFlags( 0 );
			terminate;
		}

		delay(1);
	}
	else switch(random(1,3))
	{
	case 1: card1 = 3; cards = 3; break;
	case 2: card2 = 3; cards = 3; break;
	case 3: card3 = 3; cards = 3; break;
	}
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	TakeInventory("ActiveInProgress",1);
	SetNetworkReplicationFlags( 0 );

	// Selection not started, punish
	if(cards == 0)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("ActiveProgressToken",no);
		ACS("QCDE_Tarot_Hint_Failure");
		SetNetworkReplicationFlags( 0 );
		ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown() / CARD_CD_PENALTY_DIVISOR);
		terminate;
	}

	// Selection unfinished, auto complete
	while(cards < CARDS_TO_PICK && lastTapValue)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetInventory("ActiveProgressToken",no);
		SetNetworkReplicationFlags( 0 );
		//log(n:0, s:" hasn't selected all cards. Autofill: ", d:card1, s:", ", d:card2, s:", ", d:card3);
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		switch(lastTapValue)
		{
		case 1: ACS("QCDE_Tarot_Hint_Success", 1, ++card1, ++cards); break;
		case 2: ACS("QCDE_Tarot_Hint_Success", 2, ++card2, ++cards); break;
		case 3: ACS("QCDE_Tarot_Hint_Success", 3, ++card3, ++cards); break;
		}
		SetNetworkReplicationFlags( 0 );
	}

	// Sanity checks
	if(card1 > CARDS_TO_PICK || card2 > CARDS_TO_PICK || card3 > CARDS_TO_PICK)
	{
		PrintBold(n:0, s:" got bad card selection: ", d:card1, s:", ", d:card2, s:", ", d:card3);
	}

	// Selection complete, apply effects
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	PlaySound(0,"QC/Abilities/Painkiller/Apply",CHAN_7,1.0,false,0.9);
	ACS("QCDE_Tarot_Hint_Apply");
	GiveInventory("ActiveInProgress",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
	if(IsPvP())
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory(strparam(s:"PainkillerCard1Level", d:card1), 1);
		GiveInventory(strparam(s:"PainkillerCard2Level", d:card2), 1);
		GiveInventory(strparam(s:"PainkillerCard3Level", d:card3), 1);
		SetNetworkReplicationFlags( 0 );
	}
	else
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory(strparam(s:"PvEPainkillerCard1Level", d:card1), 1);
		GiveInventory(strparam(s:"PvEPainkillerCard2Level", d:card2), 1);
		GiveInventory(strparam(s:"PvEPainkillerCard3Level", d:card3), 1);
		SetNetworkReplicationFlags( 0 );
	}
	if (GetNetworkState() != NETSTATE_CLIENT && !InDemoMode())
	{
		str class = strparam(s:"TarotOverhead", d:(!!card1 << 0) | (!!card2 << 1) | (!!card3 << 2));
		SetNetworkReplicationFlags( NETREP_SKIPOWNER|NETREP_NOUNLAGGED );
		SpawnProjectile(0,class,0,0,0,0,0);
		SetNetworkReplicationFlags( 0 );
	}

	if(CheckInventory("PainkillerCard3Level1") || CheckInventory("PvEPainkillerCard3Level1"))
	{
		ACS_NamedExecuteWithResult("QCDE_PainkillerAbilityMovement", 1);
	}

	else if(CheckInventory("PainkillerCard3Level2") || CheckInventory("PvEPainkillerCard3Level2"))
	{
		ACS_NamedExecuteWithResult("QCDE_PainkillerAbilityMovement", 2);
	}

	else if(CheckInventory("PainkillerCard3Level3") || CheckInventory("PvEPainkillerCard3Level3"))
	{
		ACS_NamedExecuteWithResult("QCDE_PainkillerAbilityMovement", 3);
	}

	// Wait for duration
	int t = GetDuration();

	// if boots level 3, you get double duration CPM
	if(checkinventory("PainkillerCard3Level3"))		//pvp
		t = GetActorPowerupTics(0,"PainkillerCard3Level3");
	else if(checkinventory("PvEPainkillerCard3Level3"))	//or pve
		t = GetActorPowerupTics(0,"PvEPainkillerCard3Level3");

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", t);

	while(t --> 0) if(GetActorProperty(0, APROP_Health) > 0  &&  !CheckInventory("NoAbilitiesToken")) delay(1);

	// End of effects
	ACS_NamedExecuteWithResult("QCDE_PainkillerAbilityMovement", 0);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	ACS("QCDE_Tarot_Hint_End");
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );
}

//---------------------------------
//		Intruder's Active

Script "QCDE_Ability_Intruder" (void)
{
	int counter;
	// Begin
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("WendigoInProc",1);
	TakeInventory("PowerIntruderSpeed",1);	//cancels passive buffs
	TakeInventory("PowerIntruderProtect",1); //cancels passive buffs

	ACS_NamedExecuteWithResult("QCDE_IntruderAbilityMovement", 1);
	SetNetworkReplicationFlags( 0 );

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", GetDuration());
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	// Disable remaining damage over time from possible Quietus hit or Postal's cow head
	quieting_for[PlayerNumber()] = 0;
	cowgassing_for[PlayerNumber()] = 0;

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	ACS("QCDE_IntruderLoop");
	SetNetworkReplicationFlags( 0 );

	// Main loop: Battles between visible and fadeout
	counter=0;
	while(counter <= GetDuration() && GetActorProperty(0,APROP_HEALTH) > 0)
	{
		if(CheckInventory("IntruderFadeBreakToken"))	//if token (given by fire and pain states in player def)
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			ACS_NamedExecuteAlways("IntruderRestoreVisibility",0);  //makes visible
			SetNetworkReplicationFlags( 0 );
			delay(10);                                              //and waits a bit before trying to fadeout again
			counter += 10;
		}
		else
		{
			if(GetActorProperty(0,APROP_Alpha)>0)
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				ACS_NamedExecuteAlways("IntruderFadeOut",0);
				SetNetworkReplicationFlags( 0 );
			}

			If(random(1,10)==1 && GetNetworkState() != NETSTATE_CLIENT && !InDemoMode())	//small % of the time it will deal damage to enemies
				GiveInventory("WendigoAuraDmgProc",1);

			delay(1);
			counter += 1;
		}
	}

	// Exit at destination
	ACS_NamedExecuteWithResult("QCDE_IntruderAbilityMovement", 0);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	ACS_NamedExecuteAlways("IntruderRestoreVisibility",0);  //makes visible again
	GiveInventory("WendigoOutProc",1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteAlways("QCDE_RestoreIndicator",0);
}


Script "IntruderFadeOut" (void)
{
	int counter=10;

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetActorProperty(0,APROP_RenderStyle,STYLE_Translucent);
	SetNetworkReplicationFlags( 0 );
	while(counter>0)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetActorProperty(0,APROP_Alpha,counter*0.1);
		SetNetworkReplicationFlags( 0 );
		//printbold(f:counter*0.1);
		counter--;
		delay(1);
		if(CheckInventory("IntruderFadeBreakToken"))
			Break;
	}

	if(!GetActorPowerupTics(0,"PowerWendigoTint"))
		terminate; // The ability is over, everything was already taken care of

	if(!CheckInventory("IntruderFadeBreakToken"))	//if the loop wasnt interrupted, then fully invis
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetActorProperty(0,APROP_Alpha,0);
		GiveInventory("WendiInvisPowerUpProc",1);
		SetNetworkReplicationFlags( 0 );
	}
	else	//if it was interrupted, then go full visible
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetActorProperty(0,APROP_RenderStyle,STYLE_Normal);
		SetActorProperty(0,APROP_Alpha,1.0);
		GiveInventory("WendiInvisPowerDownProc",1);
		SetNetworkReplicationFlags( 0 );
	}
}

Script "IntruderRestoreVisibility" (void)
{
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetActorProperty(0,APROP_RenderStyle,STYLE_Normal);
	SetActorProperty(0,APROP_Alpha,1.0);
	GiveInventory("WendiInvisPowerDownProc",1);
	SetNetworkReplicationFlags( 0 );
	delay(2);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	TakeInventory("IntruderFadeBreakToken",1);
	SetNetworkReplicationFlags( 0 );
}

#define WENDIGO_ALERT_COOLDOWN   60
#define WENDIGO_FOOTPRINT_PERIOD 10
#define WENDIGO_FOOTPRINT_RADIUS  8.0

Script "QCDE_IntruderLoop" (void) CLIENTSIDE
{
	int revealed = 0, last_revealed = 0;
	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		if(!GetActorPowerupTics(0, "PowerWendigoTint")) break;

		// Reveal sound
		if(!revealed  &&  CheckInventory("IntruderFadeBreakToken")) // just revealing now
			if(last_revealed + WENDIGO_ALERT_COOLDOWN < Timer())
			{
				//PlaySound(0, "QC/Abilities/Intruder/WendigoReveal", 7, 1.0, false, 0.75);
				GiveInventory("PowerWendigoReveal",1);
				last_revealed = 0x7FFFFFFF;
			}
		if(revealed  &&  !CheckInventory("IntruderFadeBreakToken")) last_revealed = Timer();
		revealed = CheckInventory("IntruderFadeBreakToken");

		// Footprint FX
		if(Timer() % WENDIGO_FOOTPRINT_PERIOD == 0)
		{
			//GiveInventory("IntruderBodyTrailProc",1);
			int x = GetActorX(0) + random(-WENDIGO_FOOTPRINT_RADIUS, WENDIGO_FOOTPRINT_RADIUS);
			int y = GetActorY(0) + random(-WENDIGO_FOOTPRINT_RADIUS, WENDIGO_FOOTPRINT_RADIUS);
			int z0 = GetActorFloorZ(0);
			int z1 = GetActorZ(0);
			if(CheckInventory("Instagib")) SpawnForced("IntruderBodyTrailInstagib",x,y,z1, 0, random(0, 255));
			SpawnForced("D4TBlood",         x,y,z0, 0, random(0, 255));
			SpawnForced("WendigoFootprint", x,y,z0, 0, random(0, 255));
		}

		delay(1);
	}
}

//---------------------------------
//		Orbb's Active

#define DRON_SPEED 4.0
#define DRON_FRICTION 0.8 // lower is more friction
#define DRON_DURATION 25

Script "QCDE_Ability_Orbb" (void)
{
	int plr = PlayerNumber();
	int plrtid = plr + 1000;
	int tid = ORBBDRON_TIDBASE + plr;

	if (IsTidUsed(tid))
	{
		if (GetNetworkState() != NETSTATE_SERVER && !PlayerIsBot(PlayerNumber()))
		{
			SetActivator(tid);
			if (Timer() - extraAbilityData[plr] > 2 && !CheckInventory("ImDead"))
			{
				SetActivator(plrtid);
				extraAbilityData[plr] = Timer();
				ACS_NamedExecuteWithResult("ORBB_DroneViewEnter", 0);
				if (GetNetworkState() == NETSTATE_CLIENT)
				{
					NamedRequestScriptPuke("ORBB_DroneViewEnterServer", 0);
				}
			}
			SetActivator(plrtid);
		}
		terminate;
	}
	else
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		GiveInventory("OrbbDroneProc",1);
		SetNetworkReplicationFlags( 0 );
	}

	if(CheckInventory("ActiveProgressToken")) terminate;

	int cooldown = DRON_DURATION * 35;
	bool droneSpawned = false;
	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", cooldown);
	while (cooldown --> 0)
	{
		SetActivator(plrtid);
		if (GetActorProperty(0, APROP_HEALTH) <= 0)
			break;
		if (droneSpawned)
		{
			SetActivator(tid);
			if (GetActorProperty(0, APROP_HEALTH) <= 0)
				break;
		}
		else
		{
			droneSpawned = IsTidUsed(tid);
		}
		SetActivator(-1);
		Delay(1);
	}

	SetActivator(plrtid);
	TakeInventory("UsingDrone", 1);

	ACS_NamedExecuteWithResult("QCDE_ShowActiveInProgress", DRON_DURATION * 35, 1);
    ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("GenericActiveCleanerProc",1);
	SetNetworkReplicationFlags( 0 );

	SetActivator(tid);
	GiveInventory("ImDead",1);
}

// Activator: controlled drone
Script "ORBB_DroneSpawned" (void)
{
	int plr = GetActorProperty(0, APROP_MasterTID) - 1000;
	int tid = ORBBDRON_TIDBASE + plr;
	Thing_ChangeTID(0, tid);
	SetPointer(AAPTR_TARGET, GetActorProperty(0, APROP_MasterTID));
	if(PlayerIsBot(plr) && GetNetworkState() != NETSTATE_CLIENT)
		ACS_NamedExecuteWithResult("ORBB_NotifyDroneChargeUp", tid);
}

// Activator: player
Script "ORBB_DroneViewEnter" (void)
{
	int plr = PlayerNumber();
	int plrtid = plr + 1000;
	int tid = ORBBDRON_TIDBASE + plr;

	GiveInventory("OrbbDroneEnter", 1);

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetPlayerProperty(0, 1, PROP_TOTALLYFROZEN);
	ChangeCamera(tid, false, false);
	GiveInventory("UsingDrone", 1); // giving the item to player, used for tunnel vision
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteWithResult("ORBB_TunnelVision", tid);

	SetActivator(tid);
	GiveInventory("OrbbDroneEnterDrone", 1);
	GiveInventory("UsingDrone", 1); // giving the item to drone, used to switch drone sprites
	// Activator: controlled drone

	int origa = GetActorAngle(plrtid), a = GetActorAngle(tid);
	int origp = GetActorPitch(plrtid), p = GetActorPitch(tid);
	int oldbuttons = GetPlayerInput(plr, INPUT_BUTTONS);
	int buttons = oldbuttons;
	int velx = 0, spd_for = 0, spd_tmp = 0;
	int vely = 0, spd_sid = 0;
	int velz = 0, spd_ver = 0;

	while(true)
	{
		if (CheckInventory("ImDead") || !IsTidUsed(tid))
			break;

		oldbuttons = buttons;
		buttons = GetPlayerInput(plr, INPUT_BUTTONS);

		if ((buttons & BT_USER1) && !(oldbuttons & BT_USER1))
		{
			extraAbilityData[plr] = Timer();
			break;
		}

		if ((GetNetworkState() != NETSTATE_SERVER) && (buttons & BT_ATTACK) && !(oldbuttons & BT_ATTACK))
		{
			NamedRequestScriptPuke("ORBB_NotifyDroneChargeUp", tid);
		}

		if (GetNetworkState() != NETSTATE_SERVER)
		{
			a += GetPlayerInput(plr, INPUT_YAW);
			p -= GetPlayerInput(plr, INPUT_PITCH);
			if(p >  0.25) p =  0.25;
			if(p < -0.25) p = -0.25;

			velx = FixedMul(GetActorVelX(tid), DRON_FRICTION);
			vely = FixedMul(GetActorVelY(tid), DRON_FRICTION);
			velz = FixedMul(GetActorVelZ(tid), DRON_FRICTION);

			spd_for = 0;
			spd_sid = 0;
			spd_ver = 0;

			// Turn pressed buttons into speed
			if (buttons & BT_FORWARD)
				spd_for += DRON_SPEED;
			if (buttons & BT_BACK)
				spd_for -= DRON_SPEED;
			if (buttons & BT_MOVERIGHT)
				spd_sid += DRON_SPEED;
			if (buttons & BT_MOVELEFT)
				spd_sid -= DRON_SPEED;
			if (buttons & BT_MOVEUP)
				spd_ver += DRON_SPEED;
			if (buttons & BT_MOVEDOWN)
				spd_ver -= DRON_SPEED;

			// Calculate proper vector when multiple buttons are pressed
			if (spd_for != 0 && spd_sid != 0 && spd_ver != 0)
			{
				spd_for = FixedMul(spd_for, 0.5);
				spd_sid = FixedMul(spd_sid, 0.5);
				spd_ver = FixedMul(spd_ver, 0.5);
			}
			else if (spd_for != 0 && spd_sid != 0)
			{
				spd_for = FixedMul(spd_for, 0.71);
				spd_sid = FixedMul(spd_sid, 0.71);
			}
			else if (spd_for != 0 && spd_ver != 0)
			{
				spd_for = FixedMul(spd_for, 0.71);
				spd_ver = FixedMul(spd_ver, 0.71);
			}
			else if (spd_sid != 0 && spd_ver != 0)
			{
				spd_sid = FixedMul(spd_sid, 0.71);
				spd_ver = FixedMul(spd_ver, 0.71);
			}

			// Calculate forward and vertical movement based on pitch
			spd_tmp = spd_for;
			spd_for = FixedMul(spd_for, cos(p)) + FixedMul(spd_ver, sin(p));
			spd_ver = FixedMul(spd_tmp, -sin(p)) + FixedMul(spd_ver, cos(p));

			// Calculate forward and side movement based on angle
			spd_tmp = spd_for;
			spd_for = FixedMul(spd_for, cos(a)) + FixedMul(spd_sid, sin(a));
			spd_sid = FixedMul(spd_tmp, sin(a)) + FixedMul(spd_sid, -cos(a));

			SetActorVelocity(tid, velx + spd_for, vely + spd_sid, velz + spd_ver, 0, 0);
			SetActorAngle(tid, a);
			SetActorPitch(tid, p);

			if (GetNetworkState() == NETSTATE_CLIENT)
			{
				NamedRequestScriptPuke("ORBB_ReplicateDronePos", GetActorX(tid), GetActorY(tid), GetActorZ(tid));
				NamedRequestScriptPuke("ORBB_ReplicateDroneAngle", a, p);
			}
		}

		delay(1);
	}

	SetActorVelocity(tid, 0, 0, 0, 0, 0);

	if (GetNetworkState() == NETSTATE_CLIENT)
	{
		NamedRequestScriptPuke("ORBB_ReplicateDronePos", GetActorX(tid), GetActorY(tid), GetActorZ(tid));
	}

	SetActivator(plrtid);

	SetActorAngle(plrtid, origa);
	SetActorPitch(plrtid, origP);

	ACS_NamedExecuteWithResult("ORBB_DroneViewExit", 0);
	if (GetNetworkState() == NETSTATE_CLIENT)
	{
		NamedRequestScriptPuke("ORBB_DroneViewExitServer");
	}
}

Script "ORBB_DroneViewExit" (void)
{
	int plr = PlayerNumber();
	int plrtid = plr + 1000;
	int tid = ORBBDRON_TIDBASE + plr;

	SetActivator(tid);

	GiveInventory("OrbbDroneExitDrone", 1);
	TakeInventory("UsingDrone", 1); // Take the item from drone

	SetActivator(plrtid);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("OrbbDroneExit", 1);
	ChangeCamera(plrtid, false, false);
	SetPlayerProperty(0, 0, PROP_TOTALLYFROZEN);
	SetNetworkReplicationFlags( 0 );

	TakeInventory("UsingDrone", 1); // Take the item from player
}

Script "ORBB_DroneViewEnterServer" (void) NET
{
	ACS_NamedExecuteWithResult("ORBB_DroneViewEnter", 0);
}

Script "ORBB_DroneViewExitServer" (void) NET
{
	ACS_NamedExecuteWithResult("ORBB_DroneViewExit", 0);
}

Script "ORBB_ReplicateDronePos" (int x, int y, int z) NET
{
	if (PlayerNumber() != ConsolePlayerNumber())
	{
		int tid = ORBBDRON_TIDBASE + PlayerNumber();
		SetActivator(tid);
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		Warp(0, x, y, z, 0, WARPF_ABSOLUTEPOSITION|WARPF_NOCHECKPOSITION|WARPF_INTERPOLATE);
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	}
}

Script "ORBB_ReplicateDroneAngle" (int angle, int pitch) NET
{
	int tid = ORBBDRON_TIDBASE + PlayerNumber();
	SetActorAngle(tid, angle);
	SetActorPitch(tid, pitch);
}

// Activator: player
bool tunnelVisionAlreadyOn = false;
Script "ORBB_TunnelVision" (int tid) clientside
{
	if (GetNetworkState() == NETSTATE_SERVER || tunnelVisionAlreadyOn)
		terminate;

	tunnelVisionAlreadyOn = true;

	int plr = PlayerNumber();
	bool isMe = plr == ConsolePlayerNumber();

	SetHudSize(320,240,1);
	int hmid = HMID_TUNNEL_VISION;
	SetFont("GREYMASK");
	while(CheckInventory("UsingDrone"))
	{
		if (!isMe)
		{
			if (CheckPlayerCamera(CPN()) == 1000 + plr)
			{
				SetActivator(0);
			}
			else
			{
				Delay(1);
				continue;
			}
		}

		HudMessage(s:"A";HUDMSG_FADEINOUT,hmid++,-1, 160.0,120.0, 0.4,0.2,0.4);
		if(hmid >= HMID_TUNNEL_VISION + 64) hmid = HMID_TUNNEL_VISION;
		Delay(random(20,25));

		if (!isMe)
			SetActivator(plr + 1000);
	}

	tunnelVisionAlreadyOn = false;
}

Script "ORBB_NotifyDroneChargeUp" (int tid) NET
{
	SetActivator(tid);
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	if(GameType() < GAME_NET_DEATHMATCH)
		GiveInventory("DroneExplodeCoop", 1);
	else
		GiveInventory("DroneExplodeDM", 1);
	SetNetworkReplicationFlags( 0 );
	ACS_NamedExecuteAlways("ORBB_DroneChargeUp", 0, tid);
}

Script "ORBB_DroneChargeUp" (int tid) CLIENTSIDE
{
	SetActivator(tid);
	if(GameType() < GAME_NET_DEATHMATCH)
		GiveInventory("DroneExplodeCoop", 1);
	else
		GiveInventory("DroneExplodeDM", 1);
	int time = 5;
	while (GetActorProperty(tid, APROP_HEALTH) > 0)
	{
		SetActorProperty(tid, APROP_RenderStyle, Style_Stencil);
		delay(time);
		SetActorProperty(tid, APROP_RenderStyle, Style_Translucent);
		delay(time);
		SetActorProperty(tid, APROP_RenderStyle, Style_Stencil);
		delay(time);
		SetActorProperty(tid, APROP_RenderStyle, Style_Translucent);
		delay(time);
		SetActorProperty(tid, APROP_RenderStyle, Style_Stencil);
		delay(time);
		SetActorProperty(tid, APROP_RenderStyle, Style_Translucent);
		delay(time);
		if (time > 1)
			time--;
	}
}

//=============================================================================
//
//		Active Ability: individual effects
//
//=============================================================================

// Activator: Player
script "QCDE_DireOrbThrown" (void)
{
	int tid = GetActorProperty(0, APROP_TargetTID) + 64;
	Thing_Remove(tid);
	Thing_ChangeTID(0, tid);
}

// Activator: Player
script "QCDE_DireOrbUsed" (void)
{
	if (GetNetworkState() == NETSTATE_CLIENT && PlayerNumber() != ConsolePlayerNumber())
		terminate;

	if (GetNetworkState() != NETSTATE_SERVER)
		extraAbilityData[PlayerNumber()] = true;
	int tid = 1000+64 + PlayerNumber();

	int posX = GetActorX(tid);
	int posY = GetActorY(tid);
	int posZ = GetActorZ(tid);

	SetPredictableValue(0, 0, 1);
	SetPredictableValue(0, 1, posX);
	SetPredictableValue(0, 2, posY);
	SetPredictableValue(0, 3, posZ);
	Teleport_NoFog(tid, 0, 0, FALSE);

	Thing_Remove(tid);
	SetNetworkReplicationFlags( NETREP_NOUNLAGGED );
	SpawnProjectile(0, "DireOrbExploder", 0, 0, 0, 0, 0);
	SetNetworkReplicationFlags( 0 );

	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	delay(1); //waits a bit
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	GiveInventory("DireOrbTeleFogOutProc",1); //then spawns dire orb fog, which also plays sound
	SetNetworkReplicationFlags( 0 );
}

// Activator: Player
script "QCDE_DireOrbPredictedUse" (void)
{
	int posX = GetPredictableValue(0, 1);
	int posY = GetPredictableValue(0, 2);
	int posZ = GetPredictableValue(0, 3);
	SetActorPosition(0, posX, posY, posZ, false);
}

// Activator: Dire Orb
script "QCDE_DireOrbTimedOut" (void)
{
	SetActivatorToTarget(0);
	// Activator: Player
	if (extraAbilityData[PlayerNumber()] == false) {
		if (GetNetworkState() != NETSTATE_SERVER)
			extraAbilityData[PlayerNumber()] = true;
		ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());
		if (GetNetworkState() == NETSTATE_SERVER)
			ACS("QCDE_DireOrbTimedOutClientside");
		delay(3);
		TakeInventory("TeleporterThrownToken",1);
	}
}

script "QCDE_DireOrbTimedOutClientside" (void) clientside
{
	ACS("QCDE_DireOrbTimedOut");
}

Script "QCDE_SetWeapon" (int weapon, int tics)
{
	while(tics --> 0)
	{
		if(GetActorProperty(0,APROP_HEALTH) <= 0) break;
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetWeapon(weapon);
		SetNetworkReplicationFlags( 0 );
		delay(1);
	}
}

// Activator: BFG ball
script "QCDE_BFGBallSpawned" (void)
{
	Thing_ChangeTid(0, BFGBALL_TIDBASE - 1000 + GetActorProperty(0, APROP_TargetTID));
	//log(s:"Spawned BFG ball, tid ", d:ActivatorTid());
}

#define BFG_ARMOR_MELT 8

// Activator: irradiated victim
script "QCDE_BFGRadiation" (void)
{
	// Only change "radius" here if changed A_RadiusGive in BFG9000Shot_DM
	int radius = 384;

	if(HostileRadiusCheck(BFGBALL_TIDBASE, radius, true))
	{
		int ac = CheckInventory("BasicArmor");

		if(ac) // if this player has armor, melt it
		{
			TakeInventory("BasicArmor", BFG_ARMOR_MELT);
			GiveInventory("BfgSlow2", 1); // this doesn't actually slow, but gives color and HUD icon
		}
		else // if this player is naked, apply debuff
		{
			str debuff = "BfgSlow";
			debuff = strparam(s:debuff, x:random(3,15));
			GiveInventory("BfgSlow1", 1); // always here for HUD indication
			GiveInventory(debuff, 1);
		}
	}
}

function int HostileRadiusCheck (int projectileTidBase, int radius, int blockable)
{
	// if not DM, skip
	if(GameType() < GAME_NET_DEATHMATCH) return false;

	if(blockable)
	{
		// if this player is invulnerable by ability, skip
		if(CheckInventory("PowerGhostTint")) return false;    //doesnt affect ghostwalking nyx
	}

	int i;

	int x = GetActorX(0) >> 16;
	int y = GetActorY(0) >> 16;

	for(i = 0; i < 64; i++)
	{
		// if the projectile is your own, skip
		if(i == PlayerNumber()) continue;

		// if that owner player doesn't have a projectile, skip
		if(!ClassifyActor(projectileTidBase + i)) continue;

		// this projectile should be the only one in existence
		// if that player's projectile is too far, skip
		int bx = GetActorX(projectileTidBase + i) >> 16;
		if(bx - x > radius || x - bx > radius) continue;
		int by = GetActorY(projectileTidBase + i) >> 16;
		if(by - y > radius || y - by > radius) continue;

		// if that player is on same team in TDM, skip
		if (CheckInventory("TeamDeathmatch") &&
			GetPlayerInfo(i,              PLAYERINFO_TEAM) ==
			GetPlayerInfo(PlayerNumber(), PLAYERINFO_TEAM))
			continue;

		return true;
	}
	return false;
}

#define MAX_TOTEMS_PVE     5
#define MAX_TOTEMS_PVP     3
int totemsUp[64][MAX_TOTEMS_PVE];

function int getMaxTotems()
{
	if(GameType() < GAME_NET_DEATHMATCH)
		return MAX_TOTEMS_PVE;
	else
		return MAX_TOTEMS_PVP;
}

// Activator: Totem
script "QCDE_TotemSpawned" (void)
{
	int plr = GetActorProperty(0, APROP_TargetTID) - 1000;
	int lastTotem = getLastTotem(plr);

	removeTotem(plr,lastTotem);

	int tid = TOTEM_TIDBASE + plr + lastTotem * 128;

	Thing_ChangeTID(0,tid);
	totemsUp[plr][lastTotem] = Timer();
	Warp(0, GetActorX(0), GetActorY(0), GetActorZ(0), 0, WARPF_ABSOLUTEPOSITION|WARPF_NOCHECKPOSITION);
	ACS_NamedExecuteAlways("QCDE_TotemSpawned_Client",0,plr);
	//log(s:"Totem[", d:plr, s:"][", d:lastTotem, s:"] spawned at ", d:totemsUp[plr][lastTotem], s:", tidded ", d:tid);
}

// Activator: Totem
script "QCDE_TotemSpawned_Client" (int plr) clientside
{
	bool cooperative    = getCvar("cooperative");
	bool teamplay       = getCvar("teamplay");
	bool teamlms        = getCvar("teamlms");
	bool teampossession = getCvar("teampossession");
	bool teamgame       = getCvar("teamgame");

	int tid = UniqueTid();
	int translation = GetActorProperty(plr + 1000, APROP_Translation);

	if(cooperative)
	{
		SpawnProjectile(0, "TotemFX", 0, 0, 0, 0, 0);
	}
	else if(teamplay || teamlms || teampossession || teamgame)
	{
		SpawnProjectile(0, "TotemColoredFX", 0, 0, 0, 0, tid);
		SetActorProperty(tid, APROP_Translation, translation);
	}
	else // ffa or duel
	{
		if(ConsolePlayerNumber() == plr)
		{
			SpawnProjectile(0, "TotemFX", 0, 0, 0, 0, 0);
			// Own totems aren't color translated in ffa
		}
		else
		{
			SpawnProjectile(0, "TotemColoredFX", 0, 0, 0, 0, tid);
			SetActorProperty(tid, APROP_Translation, translation);
		}
	}
}

// Activator: Totem's hitbox
script "QCDE_HitboxSpawned" (void)
{
	int plr = GetActorProperty(0, APROP_TargetTID) - 1000;
	int tid = HITBOX_TIDBASE + plr + getRecentTotem(plr) * 128;

	Thing_ChangeTID(0,tid);

	SetActivator(1000 + plr);
	// Activator: Galen
	ACS_NamedExecuteAlways("QCDE_UpdateTotemCount",0);

	// Cooperative has indestructible totems
	if(GameType() < GAME_NET_DEATHMATCH)
		Thing_Remove(tid);

	delay(20);

	// Totem never settled, nothing to check for hits?
	int totemtid = tid - HITBOX_TIDBASE + TOTEM_TIDBASE;
	if(!IsTidUsed(totemtid))
		Thing_Remove(tid);

	// Or wrong tid altogether?
	if(tid && tid < 1000)
		Thing_Remove(tid);

	// Once more! With feeling!
	delay(20);

	if(!IsTidUsed(totemtid))
		Thing_Remove(tid);

	if(tid && tid < 1000)
		Thing_Remove(tid);

	// Update count if anything changed
	ACS_NamedExecuteAlways("QCDE_UpdateTotemCount",0);

	// Hitbox follows the totem in case it's moved
	while(GetActorProperty(tid, APROP_Health) > 0)
	{
		int x = GetActorX(tid); int xt = GetActorX(totemtid);
		int y = GetActorY(tid); int yt = GetActorY(totemtid);
		int z = GetActorZ(tid); int zt = GetActorZ(totemtid);
		if(x != xt || y != yt || z != zt)
			Thing_Move(tid, totemtid, true);
		delay(1);
	}
}

function int getLastTotem(int plr)
{
	int i, min = totemsUp[plr][0], res = 0;
	for(i = 1; i < getMaxTotems(); i++)
	{
		if(totemsUp[plr][i] < min)
		{
			min = totemsUp[plr][i];
			res = i;
		}
	}
	return res;
}

function int getRecentTotem(int plr)
{
	int i, max = totemsUp[plr][0], res = 0;
	for(i = 1; i < getMaxTotems(); i++)
	{
		if(totemsUp[plr][i] > max)
		{
			max = totemsUp[plr][i];
			res = i;
		}
	}
	return res;
}

function void removeTotem(int plr, int totem)
{
	Thing_Remove( TOTEM_TIDBASE + plr + totem * 128);
	Thing_Remove(HITBOX_TIDBASE + plr + totem * 128);
}

// Activator: Totem
script "QCDE_TotemAttacks" (void)
{
	int plr = (ActivatorTid() - 1000) % 64;
	int plrtid = plr + 1000;
	int target = GetActorProperty(0, APROP_TargetTID);
	int targetplr = target - 1000;

	bool friendly = false;

	bool teamplay       = getCvar("teamplay");
	bool teamlms        = getCvar("teamlms");
	bool teampossession = getCvar("teampossession");
	bool teamgame       = getCvar("teamgame");

	if(teamplay || teamlms || teampossession || teamgame)
		friendly = GetPlayerInfo(plr,       PLAYERINFO_TEAM) ==
		           GetPlayerInfo(targetplr, PLAYERINFO_TEAM);
	else
		friendly = plrtid == target;

	bool targetOutsideRange = GetActorZ(target) > GetActorZ(0) + 40.0 || GetActorZ(target) < GetActorZ(0) - 20.0;
	if (targetOutsideRange)
	{
		//log(s:"Totem avoids attack");
		SetActorState(0,"NoAttack");
	}
	else if(friendly)
	{
		bool friendHealed = false;
		if (CheckActorInventory(plrtid, "TotemTokenPvP") >= 3)
		{
			if (GetActorProperty(target,APROP_HEALTH) < CheckActorInventory(target,"MaxHealthToken") + 50)
			{
				//log(s:"Totem super heals friend");
				SetActorState(0,"SuperDMSingleHeal");
				friendHealed = true;
			}
		}
		else
		{
			if (GetActorProperty(target,APROP_HEALTH) < CheckActorInventory(target,"MaxHealthToken"))
			{
				//log(s:"Totem heals friend");
				SetActorState(0,"DMSingleHeal");
				friendHealed = true;
			}
		}

		if (!friendHealed)
		{
			//log(s:"Totem doesn't heal friend");
			SetActorState(0,"NoAttack");
		}
	}
	else
	{
		//log(s:"Avoid attacks enemy");
		SetActorState(0,"Explode");
	}

	delay(20);

	SetActivator(1000 + plr);
	// Activator: Galen
	ACS_NamedExecuteAlways("QCDE_UpdateTotemCount",0);
}

// Activator: Totem
script "QCDE_TotemDestroyed" (void)
{
	// Totem never spawned, only projectile blew up?
	if(!ActivatorTid()) terminate;

	Thing_Destroy(ActivatorTid() + 64);
	int plr = (ActivatorTid() - 1000) % 64;
	int totem = (ActivatorTid() - 1064) / 128;
	totemsUp[plr][totem] = 0;
	//log(s:"Totem ", d:ActivatorTid(), s:" exploding, removing hitbox ", d:ActivatorTid() + 64, s:", evicting record ", s:"[", d:plr, s:"][", d:totem, s:"]");

	SetActivator(1000 + plr);
	// Activator: Galen
	ACS_NamedExecuteAlways("QCDE_UpdateTotemCount",0);
}

// Activator: Totem's hitbox
script "QCDE_HitboxDestroyed" (void)
{
	Thing_Remove(ActivatorTid() - 64);
	int plr = (ActivatorTid() - 1000) % 64;
	int totem = (ActivatorTid() - 1128) / 128;
	totemsUp[plr][totem] = 0;
	//log(s:"Hitbox ", d:ActivatorTid(), s:" dying, destroying totem ", d:ActivatorTid() - 64, s:", evicting record ", s:"[", d:plr, s:"][", d:totem, s:"]");

	SetActivator(1000 + plr);
	// Activator: Galen
	ACS_NamedExecuteAlways("QCDE_UpdateTotemCount",0);
}

// Activator: Galen, or ex-Galen
script "QCDE_UpdateTotemCount" (void)
{
	int plr = PlayerNumber();

	// Remove totems from ex-Galen
	if(!CheckInventory("Class_Galen"))
	{
		Thing_Remove(TOTEM_TIDBASE + plr      ); Thing_Remove(HITBOX_TIDBASE + plr      );
		Thing_Remove(TOTEM_TIDBASE + plr + 128); Thing_Remove(HITBOX_TIDBASE + plr + 128);
		Thing_Remove(TOTEM_TIDBASE + plr + 256); Thing_Remove(HITBOX_TIDBASE + plr + 256);
		Thing_Remove(TOTEM_TIDBASE + plr + 384); Thing_Remove(HITBOX_TIDBASE + plr + 384);
		Thing_Remove(TOTEM_TIDBASE + plr + 512); Thing_Remove(HITBOX_TIDBASE + plr + 512);
	}

	int count;
	count += IsTidUsed(TOTEM_TIDBASE + plr      );
	count += IsTidUsed(TOTEM_TIDBASE + plr + 128);
	count += IsTidUsed(TOTEM_TIDBASE + plr + 256);
	count += IsTidUsed(TOTEM_TIDBASE + plr + 384);
	count += IsTidUsed(TOTEM_TIDBASE + plr + 512);

	SetInventory("TotemTokenPvE", count);
	SetInventory("TotemTokenPvP", count);
}


#define MAULOTAUR_DURATION 25
// Activator: Dave
script "QCDE_MaulotaurSpawned" (void)
{
	// In coop, don't block players
	if (GameType() <= GAME_NET_COOPERATIVE) GiveInventory("ThruSpeciesProc", 1);

	int tid = ActivatorTid();
	int plr = tid - MAULOTAUR_TIDBASE;
	int plrtid = plr + 1000;

	SetPointer(AAPTR_TARGET, UniqueTid());
	SetPointer(AAPTR_MASTER, plrtid);

	//ACS("iamamiwhoami");

	// Seppuku if ronin.
	if (!plrtid)
	{
		Thing_Destroy(tid);
		//log(s:"Orphaned Maulotaur without master dying");
		terminate;
	}

	// If DM, apply reduced health
	if (GameType() >= GAME_NET_DEATHMATCH)
		SetActorProperty(0,APROP_HEALTH,200);


	//log(s:"Maulotaur spawned for ", n:plr+1, s:" with tid ", d:tid);
	ACS("QCDE_ObjectAllyMarker_Client", plr);

	// Set target to an arbitrary enemy
	int i;
	for(i = 0; i < 64; i++)
	{
		if(!PlayerInGame(i)) continue;
		if(!areEnemies(plr, i)) continue;

		SetPointer(AAPTR_TARGET, i+1000);
		//PrintBold(n:plr+1, s:"'s ", n:0, s:" now hates ", n:i+1);
		break;
	}

	// Activator: Player
	SetActivator(plrtid);
	delay(1);
	ACS_NamedExecuteWithResult("QCDE_AbilityCooldown", GetCooldown());

	if (GetNetworkState() == NETSTATE_CLIENT || InDemoMode())
		terminate;


	if (extraAbilityData[plr])
	{
		// previous maulotaur's clock is still ticking
		// just update the timer and leave
		extraAbilityData[plr] = MAULOTAUR_DURATION;
		terminate;
	}

	GiveInventory("MaulotaurAliveToken", 1);

	// Keep track of current Maulotaur, and kill it in 25 seconds.
	extraAbilityData[plr] = MAULOTAUR_DURATION;
	while(extraAbilityData[plr] --> 0)
	{
		if(GetActorProperty(tid, APROP_HEALTH) <= 0) break;
		SetInventory("MaulotaurAliveToken", true);
		delay(35);
	}

	extraAbilityData[plr] = 0;
	SetInventory("MaulotaurAliveToken", false);

	Thing_Destroy(tid);
}

// Activator: Minion Missile
Script "QCDE_MaulotaurAttacks" (void)
{
	//int tid = UniqueTid();
	//Thing_ChangeTID(0, tid);
	int res = SetPointer(AAPTR_TARGET, GetActorProperty(0, APROP_TargetTID) - MAULOTAUR_TIDBASE + 1000);

	//str s = strparam(n:0);
	//SetActivatorToTarget(0);
	//str col = "\c[green]";
	//if(!res) col = "\c[red]";
	//PrintBold(s:col, s:s, s:" comes from ", n:0);
}

// Activator: attacking Dave
Script "QCDE_DavieDontHurtMeDontHurtMeNoMore" (void)
{
	int target = GetActorProperty(0, APROP_TargetTID) - 1000;
	int player = GetActorProperty(0, APROP_MasterTID) - 1000;

	if (target < 0 || target > 63 ||
	    player < 0 || player > 63) terminate;

	if(!areEnemies(player, target))
	{
		GiveInventory("TargetForgetter", 1);
		SetActorState(0,"Idle");
	}
}

// Activator: Player
script "QCDE_Hourglass" (int percentage, int nosandswirl)
{
	if (GetNetworkState() == NETSTATE_CLIENT || InDemoMode())
		terminate;

	if(!percentage) terminate;

	int plr = PlayerNumber();

    if(tics[plr] == 0) terminate;

	int take = GetCooldown() * percentage / 100;

	// Scale bonus according to percentage server cvar
	take = take * GetCvar("sv_cooldownPercentage") / 100;

	SetHudSize(1400,1050,1);

	if(percentage > 0)
	{
		int size = (percentage + 9) / 10 * 10 + 40;
		if(size <  30) size =  30;
		if(size > 100) size = 100;
		str font = strparam(s:"QCFNT", d:size/100, d:size%100/10, d:size%10);
		SetFont(font);
		HudMessage(s:"-", d:percentage, s:"%"; HUDMSG_FADEOUT, 3243, CR_GOLD, 760.1, 946.1, 0.2, 0.04 * percentage);
	}
	SetFont("BLINKGLD");
	//HudMessage(s:"A"; HUDMSG_FADEOUT, 3245, CR_UNTRANSLATED, 700.0, 911.0, 0.08, 0.005 * percentage);
	if(!nosandswirl) ACS("QCDE_BlinkSandwatch");
	tics[plr] -= take;
    if(tics[plr] < 0)
    	tics[plr] = 0;

	if (GetNetworkState() == NETSTATE_SERVER)
		ACS("QCDE_Hourglass_Replicate", tics[plr]);
}

script "QCDE_Hourglass_Replicate" (int tics)
{
	delay(1);
	//log(s:"QCDE_Hourglass: Sending ", d:tics[plr]);
	ACS("QCDE_AbilityCooldown_CLIENTSIDE", tics > 0 ? tics - 1 : 0, true);
}

script "QCDE_BlinkSandwatch" (void) clientside
{
	if(IsZandronum(true))
		if(ActivatorTid() != CheckPlayerCamera(ConsolePlayerNumber()))
			terminate;

	SetHudSize(1400,1050,1);

	SetFont("SWIRLIN1"); HudMessageBold(s:"A"; HUDMSG_FADEOUT, 3246, CR_UNTRANSLATED, 700.0, 911.0, 0.1, 0.1); delay(2);
	SetFont("SWIRLIN2"); HudMessageBold(s:"A"; HUDMSG_FADEOUT, 3246, CR_UNTRANSLATED, 700.0, 911.0, 0.1, 0.1); delay(2);
	SetFont("SWIRLIN3"); HudMessageBold(s:"A"; HUDMSG_FADEOUT, 3246, CR_UNTRANSLATED, 700.0, 911.0, 0.1, 0.1); delay(2);
	SetFont("SWIRLIN4"); HudMessageBold(s:"A"; HUDMSG_FADEOUT, 3246, CR_UNTRANSLATED, 700.0, 911.0, 0.1, 0.1); delay(2);
	SetFont("SWIRLIN5"); HudMessageBold(s:"A"; HUDMSG_FADEOUT, 3246, CR_UNTRANSLATED, 700.0, 911.0, 0.1, 0.1); delay(2);
	SetFont("SWIRLIN6"); HudMessageBold(s:"A"; HUDMSG_FADEOUT, 3246, CR_UNTRANSLATED, 700.0, 911.0, 0.1, 0.1); delay(2);
}


// Activator: freshly spawned BOB
Script "QCDE_BobPointers" (void)
{
	int mast = GetActorProperty(0, APROP_MasterTID) - 1000;
	int targ = GetActorProperty(0, APROP_TargetTID) - 1000;
	if(mast >= 0)
		Thing_ChangeTID(0, BOB_TIDBASE + mast);
	else if(targ >= 0)
		Thing_ChangeTID(0, BOB_TIDBASE + targ);
	//log(n:0, s:" ownership: mast ", n:mast+1, s:", targ ", n:targ+1, s:" tid ", d:ActivatorTid());
}

// Activator: BOB spawned a few tics ago
Script "QCDE_BobRecolor" (int tid)
{
	int plr = tid - BOB_TIDBASE;
	if(CheckActorClass(0, "QCDEMaulotaur")) plr = tid - MAULOTAUR_TIDBASE;
	if(CheckActorClass(0, "QCDEMaulotaurPvE")) plr = tid - MAULOTAUR_TIDBASE;
	if(CheckActorClass(0, "OrbbDrone")) plr = tid - ORBBDRON_TIDBASE;

	int translation = GetActorProperty(plr + 1000, APROP_Translation);
	SetActorProperty(tid, APROP_Translation, translation);
}

// Activator: BOB's explosive hack
Script "QCDE_BobExplosionAttribution" (void)
{
	//log(s:" my target tids ", d:GetActorProperty(0, APROP_TargetTID), s:", remainder ", d:(GetActorProperty(0, APROP_TargetTID) % 64));
	SetPointer(AAPTR_TARGET, 960 + (GetActorProperty(0, APROP_TargetTID) % 64));
}



//=============================================================================
//
//		Passive Ability: Per Class handlers
//
//=============================================================================

//---------------------------------
//		Corvus's Passive

Script "QCDE_Passive_Corvus" (void)
{
	if (GameType() >= GAME_NET_DEATHMATCH)
		GiveInventory("CorvusRegenerationDM",1);
	else
		GiveInventory("CorvusRegenerationCoop",1);
}


// Activator: dying monster
Script "QCDE_MonsterKill_QCCaleb" (int xdeath)
{
	int killertid = GetActorProperty(0,APROP_TargetTID);
	if(CheckActorInventory(killertid,"PowerCalebDrain")) // killer uses ability?
	{
		GiveActorInventory(killertid,"CalebHeartSP",1); // instant delivery
	}
	else
	{
		SpawnSpotForced("CalebHeartSP",0,0,0);
	}
}

// Activator: dying victim
Script "QCDE_PlayerKill_QCCaleb" (void)
{
	if(GetActorProperty(0,APROP_HEALTH) > 0) terminate;

	int killertid = GetActorProperty(0,APROP_TargetTID);
	if(!CheckActorInventory(killertid,"Class_Caleb")) terminate; // killer is not Caleb?

	if(CheckActorInventory(killertid,"PowerCalebDrain")) // killer uses ability?
	{
		GiveActorInventory(killertid,"CalebHeartDM",1); // instant delivery
	}
	else
	{
		SpawnSpotForced("CalebHeartDM",0,0,0);
	}
}


//---------------------------------
//		Menelkir's Passive

// Activator: dying monster
Script "QCDE_MonsterKill_QCMenelkir" (void)
{
	if(GetActorProperty(0,APROP_HEALTH) > 0) terminate;

	int killertid = GetActorProperty(0,APROP_TargetTID);
	if(!CheckActorInventory(killertid, "Class_Menelkir")) terminate;
	if(GetActorProperty(killertid, APROP_HEALTH) <= 0) terminate;

	if(random(1,100) < 20)
		SpawnSpotForced("MenelkirMonsterHourglass",0,0,0);
}

// Activator: dying victim
Script "QCDE_PlayerKill_QCMenelkir" (void)
{
	if(GetActorProperty(0,APROP_HEALTH) > 0) terminate;

	int killertid = GetActorProperty(0,APROP_TargetTID);
	if(!CheckActorInventory(killertid, "Class_Menelkir")) terminate;
	if(GetActorProperty(killertid, APROP_HEALTH) <= 0) terminate;

	SpawnSpotForced("MenelkirHourglass",0,0,0);
}


//---------------------------------
//		Terminator's Passive

str AmmoType[8] = {
		"QCBulletAmmo",		//0  bullet
		"QCShellAmmo",		//1  shell
		"QCNailAmmo",		//2  nail
		"QCBoltAmmo",		//3  bolt
		"QCRocketAmmo",		//4  rocket
		"QCCoilAmmo",		//5  coil
		"QCSlugAmmo",		//6  slug
		"QCBFGAmmo"			//7  bfg
		};

Script "QCDE_Passive_Terminator" (void)
{
	//if(GetActorProperty(0,APROP_HEALTH) > 0) terminate;
	int TenTics, CurrentAmmo, PreviousAmmo;
	if (GameType() >= GAME_NET_DEATHMATCH)
		SetInventory("TerminatorRockets",10);
	else
		SetInventory("TerminatorRockets",20);

	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		if(CheckInventory("Freezetagged")) // FT fix
		{
			delay(50);
			continue;
		}

		if		(qcContains("Mac"))	CurrentAmmo=0;
		else if (qcContains("Sho"))	CurrentAmmo=1;
		else if (qcContains("Nai"))	CurrentAmmo=2;
		else if (qcContains("Tri"))	CurrentAmmo=3;
		else if (qcContains("Roc"))	CurrentAmmo=4;
		else if (qcContains("Lig"))	CurrentAmmo=5;
		else if (qcContains("Rai"))	CurrentAmmo=6;
		else if (qcContains("BFG"))	CurrentAmmo=7;
		else	//if any other weapon
			CurrentAmmo=-1;	//nothing at all

		TenTics++;			//Increase counter of tics

		if(CurrentAmmo != -1 && TenTics >= getTerminatorAmmoRegenInterval(CurrentAmmo))
		{
			if(CheckInventory(AmmoType[CurrentAmmo]) < GetAmmoCapacity(AmmoType[CurrentAmmo]))
				GiveInventory(AmmoType[CurrentAmmo] , getTerminatorAmmoRegenAmount(CurrentAmmo));
			else if(GameType() == GAME_NET_COOPERATIVE || // in cooperative
					CheckInventory("TeamDeathmatch"))  // or team deathmatch
			{
				// Drop small pickup and stop regen for time equal to normal regen period
				int x = GetActorX(0);
				int y = GetActorY(0);
				int z = GetActorZ(0) + 64.0;
				SpawnForced(strparam(s:AmmoType[CurrentAmmo], s:"Terminator"), x,y,z);
				//Log(s:strparam(s:AmmoType[CurrentAmmo], s:"Terminator"), s:" shared");
				Delay(getTerminatorAmmoRegenInterval(CurrentAmmo));
			}
			TenTics=0;
		}

		Delay(10);
	}
}

Script "QCDE_Terminator_Rockets_Full"
{
	if (CheckInventory("TerminatorRockets") >= 20)
		SetResultValue(1);
	else
		SetResultValue(0);
}

function int qcContains(str subst)
{
	// If 3-letter substring starting at second ("qcBFGdm") or at seventh ("qcheavyMAChinegun")
	// character equals weapon name input, that's the weapon we're looking for.
	// Partially inspired by AcsUtils StrFind.
	str weapon = GetWeapon();
	return  !stricmp(strmid(weapon, 2, 3), subst) ||
			!stricmp(strmid(weapon, 7, 3), subst);
}

//---------------------------------
//		Zedek's Passive

#define ZEDEK_MIN_FALL_SPEED  10
#define ZEDEK_POST_FALL_DELAY 10
Script "QCDE_Passive_Zedek" (void)
{
	// Give the ironfeet powerup
	if (GameType() >= GAME_NET_DEATHMATCH)
		GiveInventory("PowerZedekFeet_DM",1);
	else
		GiveInventory("PowerZedekFeet",1);

	// Stomping on landing for Zedek
	int zs0, zs1, landSpeed;

	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		// Speed history -- you're grounded if were flying but aren't anymore.
		zs0 = zs1;
		zs1 = GetActorVelZ(0) >> 16;
		if(zs0 < -ZEDEK_MIN_FALL_SPEED && !zs1)
		{
			landSpeed = -zs0;
			SetNetworkReplicationFlags( NETREP_SKIPOWNER | NETREP_NOUNLAGGED );
			SpawnProjectile(0, "ZedekCannonball", 0, 0,landSpeed*8, 0,0);
			SetNetworkReplicationFlags( 0 );
			delay(ZEDEK_POST_FALL_DELAY);
		}

		delay(1);
	}
}


//---------------------------------
//		Inquisitor's Passive

#define MOVEMENT_BUTTONS (BT_MOVELEFT|BT_FORWARD|BT_MOVERIGHT|BT_BACK)
Script "QCDE_Passive_Inquisitor" (void)
{
	// This passive is human-scum-only.
	if(PlayerIsBot(PlayerNumber())) terminate;

	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		// Still defense
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		bool stillDefense = !CheckInventory("InquisitorStageToken") && !(GetPlayerInput(-1, INPUT_BUTTONS) & MOVEMENT_BUTTONS);
		if (!stillDefense)
			TakeInventory("PowerClutchProtec",1);
		else if(!CheckInventory("PowerClutchProtec"))
			GiveInventory("ClutchPassiveProtec",1);
		SetNetworkReplicationFlags( 0 );

		delay(1);
	}
}


//---------------------------------
//		Bitterman's Passive

#define BITTERMAN_REGEN_PERIOD 30 //tics to gain 1 armor charge

Script "QCDE_Passive_Bitterman" (void)
{
	if(GameType() < GAME_NET_DEATHMATCH)
	{
		if(!CheckInventory("ExtraAmmoCapacity"))
		{
			GiveInventory("ExtraAmmoCapacity",1);
			GiveInventory("QCBackpack",1);
			ACS_NamedExecuteAlways("鳞~Loot🅱ox0_2",0,0,0,0);
			ACS_NamedExecuteAlways("鳞~Loot🅱ox0_2",0,0,0,0);
			ACS_NamedExecuteAlways("鳞~Loot🅱ox0_2",0,0,0,0);
		}
	}
	else
	{
		delay(1);
		SetAmmoCapacity("QCBulletAmmo",	getBittermanDMAmmoCapacity(0));
		SetAmmoCapacity("QCShellAmmo",	getBittermanDMAmmoCapacity(1));
		SetAmmoCapacity("QCNailAmmo",	getBittermanDMAmmoCapacity(2));
		SetAmmoCapacity("QCBoltAmmo", 	getBittermanDMAmmoCapacity(3));
		SetAmmoCapacity("QCRocketAmmo",	getBittermanDMAmmoCapacity(4));
		SetAmmoCapacity("QCCoilAmmo", 	getBittermanDMAmmoCapacity(5));
		SetAmmoCapacity("QCSlugAmmo", 	getBittermanDMAmmoCapacity(6));
		SetAmmoCapacity("QCBFGAmmo",	getBittermanDMAmmoCapacity(7));
	}

	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		if(CheckInventory("PowerShieldCharge") < 200 || GameType() > GAME_SINGLE_PLAYER)
			GiveInventory("PowerShieldCharge", Timer() % BITTERMAN_REGEN_PERIOD == 0);
		delay(1);
	}
}

//Passive 2 "Armor Efficient", where armor degenerates MUCH slower,
//the effect takes place in the script "QCDE_Degeneration" in "HLTHARMR.acs"



//---------------------------------
//		Durandal's Passive

//This is derived of the script "ArmorGiver" from HLTHARMR.acs
//Edited to work for Durandal's rules
Script "DurandalArmor" (int ClassArmorMax, int ClassHealthMax, int ArmorToGive)
{
	if( ArmorToGive >= 100 ) 				//if it's a heavy armor
		ClassArmorMax = ClassArmorMax+75;	//allow overcharge of +75

	int ArmorCount;
	int CurrentHealth = GetActorProperty(0,APROP_HEALTH);
	int HealthMissing = 0;

	if(CurrentHealth < ClassHealthMax)
	{
		HealthMissing = ClassHealthMax - CurrentHealth;	//determines how much health was missing

		if(HealthMissing<=ArmorToGive)
			SetActorProperty(0, APROP_Health, CurrentHealth+HealthMissing);	//and heals it
		else
		{
			SetActorProperty(0, APROP_Health, CurrentHealth+ArmorToGive);
			HealthMissing=0;
		}
	}

	if(GetActorProperty(0,APROP_HEALTH)>= ClassHealthMax) //if current health max or above
	{
		ArmorToGive= ArmorToGive - HealthMissing;
		if(ArmorToGive>0)
			while(CheckInventory("BasicArmor") < ClassArmorMax  &&  ArmorCount < ArmorToGive)
			{
				GiveInventory("QCArmorPoint", 1);
				ArmorCount++;
			}
	}
}


//---------------------------------
//		Keel's Passive

Script "QCDE_Passive_Keel" (void)
{
	int amm0, amm1;

	// Remember initial state (not to get cooldown bonus on respawn)
	amm0 =  CheckInventory("QCBulletAmmo") +
			CheckInventory("QCShellAmmo" ) +
			CheckInventory("QCNailAmmo"  ) +
			CheckInventory("QCBoltAmmo"  ) +
			CheckInventory("QCRocketAmmo") +
			CheckInventory("QCCoilAmmo"  ) +
			CheckInventory("QCSlugAmmo"  ) +
			CheckInventory("QCBFGAmmo"   );


	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		// Reduce cooldown with ammo
		amm1 =
				CheckInventory("QCBulletAmmo") +
				CheckInventory("QCShellAmmo" ) +
				CheckInventory("QCNailAmmo"  ) +
				CheckInventory("QCBoltAmmo"  ) +
				CheckInventory("QCRocketAmmo") +
				CheckInventory("QCCoilAmmo"  ) +
				CheckInventory("QCSlugAmmo"  ) +
				CheckInventory("QCBFGAmmo"   );

		if(amm1 > amm0  &&  tics[PlayerNumber()])
		{
			if(GameType() >= GAME_NET_DEATHMATCH)
				ACS("QCDE_Hourglass", 5);
			else
				ACS("QCDE_Hourglass", 5);
		}

		amm0 = amm1;

		delay(1);
	}
}

//---------------------------------
//		Sarge's Passive

Script "QCDE_Passive_Sarge" (void)
{
	if(IsPVE())
	{
		GiveInventory("NoHealthDegenerationToken", 1);
		GiveInventory("NoArmorDegenerationToken" , 1);
	}
}

Script "QCDE_Sarge_Armor_Full"
{
	if (CheckInventory("BasicArmor") >= CheckInventory("MaxArmorToken") + 100)
		SetResultValue(1);
	else
		SetResultValue(0);
}



//---------------------------------
//		Lo Wang's Passive

#define LOWANG_TAP_DELAY    25
#define LOWANG_TIC_PERIOD    5
#define LOWANG_MAX_DURATION 35
#define LOWANG_LOW_HEALTH   40
#define LOWANG_DMG_PERIOD   10
Script "QCDE_Passive_LoWang" (void)
{
	// Right-right-use healing and extra damage when low
	int buttons, oldbuttons, triggers;
	int lastTapTime, lastTapValue, tapSequence, angle;
	int ws_axis, ad_axis;
	int rageTime, healTime;

	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		// Player input information
		oldbuttons = buttons;
		buttons = GetPlayerInput(-1, INPUT_BUTTONS) & ~BT_SPEED;
		ws_axis = GetPlayerInput(-1, INPUT_FORWARDMOVE);
		ad_axis = GetPlayerInput(-1, INPUT_SIDEMOVE);
		if(ws_axis < 0) buttons |= BT_BACK;
		if(ws_axis > 0) buttons |= BT_FORWARD;
		if(ad_axis < 0) buttons |= BT_MOVELEFT;
		if(ad_axis > 0) buttons |= BT_MOVERIGHT;
		triggers = buttons & ~oldbuttons;

		// Extra damage when low
		if (!(Timer() % LOWANG_DMG_PERIOD))
			if (GetActorProperty(0, APROP_HEALTH) <= LOWANG_LOW_HEALTH)
			{
				if(!rageTime) GiveInventory("LoWangRageSoundProc", 1);
				rageTime++;

				GiveInventory("LoWangPassiveDamage", 1);
			}
			else
			{
				TakeInventory("PowerLoWangDamage", 1);
				rageTime=0;
			}


		// Hold detection
		// Player holds +use
		if (buttons & BT_USE)
		{
			if (lastTapTime + LOWANG_TAP_DELAY > Timer()) // if tapping time hasn't yet expired
			{
				if (!(Timer() % LOWANG_TIC_PERIOD))
				{
					if(!healTime) GiveInventory("LoWangHealSoundProc", 1);
					healTime++;

					GiveInventory("LoWangHealAreaProc", 1);
				}

				lastTapTime = Timer();

				// Duration cap. Measured in LOWANG_TIC_PERIODs.
				if (healTime > LOWANG_MAX_DURATION) lastTapTime = 0;
			}
		}
		// Tap detection
		// Player taps D, holds no other button
		else if (buttons == BT_MOVERIGHT && !oldbuttons)
		{
			healTime=0;
			if (lastTapTime + LOWANG_TAP_DELAY > Timer()){ // if tapping time hasn't yet expired
				tapSequence += 1;
			} else {
				tapSequence = 1;
			}
			//printbold(s:"\c[bludi] TAP! \nseq = ", d:tapSequence, s:"\ndelay = ", d:Timer() - lastTapTime);
			lastTapTime = Timer();
		}

		delay(1);
	}
}




//---------------------------------
//		Grayson's Passive

#define GRAYSON_NEWLIFE_DELAY 15
#define GRAYSON_INITIAL_DELAY 20
#define GRAYSON_HOLD_DELAY    28
#define GRAYSON_ARMOR_TAKE    25

Script "QCDE_Passive_Grayson" (void)
{
	// Hold +use to buy ammo packs for armor blocks
	int holdPulses, lastHoldPulses;
	int lastHoldStartTime = Timer();
	int CurrentAmmo;

	// Separate block to wait for respawn spacebar to release
	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		if(CurrentAmmo ++> GRAYSON_NEWLIFE_DELAY) break;
		delay(1);
	}

	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		delay(1);

		if (!(GetPlayerInput(-1, INPUT_BUTTONS) & BT_USE)) continue;

		// -- Now alive and holding +use --

		if (!(GetPlayerInput(-1, INPUT_OLDBUTTONS) & BT_USE))
			lastHoldStartTime = Timer();

		if		(qcContains("Mac"))	CurrentAmmo = 0;
		else if (qcContains("Sho"))	CurrentAmmo = 1;
		else if (qcContains("Nai"))	CurrentAmmo = 2;
		else if (qcContains("Tri"))	CurrentAmmo = 3;
		else if (qcContains("Roc"))	CurrentAmmo = 4;
		else if (qcContains("Lig"))	CurrentAmmo = 5;
		else if (qcContains("Rai"))	CurrentAmmo = 6;
		else if (qcContains("BFG"))	CurrentAmmo = 7;
		else continue;
		int amount = getGraysonAmmoPackSize(CurrentAmmo);

		lastHoldPulses = holdPulses;
		int duration = Timer() - lastHoldStartTime;
		holdPulses = (duration + GRAYSON_HOLD_DELAY - GRAYSON_INITIAL_DELAY) / GRAYSON_HOLD_DELAY; // [Ms] sorry for arcaneness, but this is still better than previous attempt

		if (lastHoldPulses == holdPulses) continue; // prevent from triggering every tic

		//log(s:"trig: ", d:lastHoldStartTime, s:" -> ", d:Timer(), s:". diff ", d:duration + GRAYSON_HOLD_DELAY - GRAYSON_INITIAL_DELAY, s:".  pulse = ", d:holdPulses);

		if (holdPulses < 1) continue; // prevent from triggering too early

		if (holdPulses == 1)
		{
			// Show initial prompt
			ACS("QCDE_GraysonText", amount, 0, CurrentAmmo);
			continue;
		}

		// -- holdPulses > 1: now buying stuff --

		if(CheckInventory("BasicArmor") >= GRAYSON_ARMOR_TAKE)
		{
			// To be used if we decide to drop player's excess ammo
			//int x = GetActorX(0);
			//int y = GetActorY(0);
			//int z = GetActorZ(0) + 30.0;
			if(GiveAndCheck(AmmoType[CurrentAmmo], amount))
			{
				// Bought successfully
				TakeInventory("BasicArmor", GRAYSON_ARMOR_TAKE);
				ACS("QCDE_GraysonText", amount, 1, CurrentAmmo);
				//log(d:Timer(), s:": pulses = ", d:holdPulses, s:", lastHoldStartTime = ", d:lastHoldStartTime, s:" (duration = ", d:duration, s:")");
			}
			else
			{
				// Full already
				ACS("QCDE_GraysonText", amount, -2, CurrentAmmo);
			}
		}
		else
		{
			// No money -- no honey
			ACS("QCDE_GraysonText", amount, -1, CurrentAmmo);
		}
	}
}

// Activator: dying monster
Script "QCDE_MonsterKill_QCGrayson" (void)
{
	int max = GetActorProperty(0,APROP_SPAWNHEALTH);
	int bounty = sqrt(max / 5);

	SetActivatorToTarget(0);
	// Activator: Player

	if(!CheckInventory("Class_Grayson")) terminate;

	PlaySound(0, "QC/Abilities/Grayson/Earn", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
	ACS("QCDE_AwardArmorOverTime", bounty);
}

// Activator: dying victim
#define GRAYSON_REWARD_DM 25
Script "QCDE_PlayerKill_QCGrayson" (void)
{
	if(GetActorProperty(0,APROP_HEALTH) > 0) terminate;

	SetActivatorToTarget(0);
	// Activator: Player
	if(!CheckInventory("Class_Grayson")) terminate;
	if(GetActorProperty(0,APROP_HEALTH) <= 0) terminate;

	PlaySound(0, "QC/Abilities/Grayson/Earn", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
	ACS("QCDE_AwardArmorOverTime", GRAYSON_REWARD_DM);
}

Script "QCDE_AwardArmorOverTime" (int amount)
{
	while(amount --> 0)
	{
		if(CheckInventory("BasicArmor") > CheckInventory("MaxArmorToken") + 50) terminate;
		GiveInventory("QCArmorPoint",1);
		if(amount < 25) delay(1);
	}
}



//---------------------------------
//		Eradicator's Passive

int level_up_at[100] =
{
	    3,     5,    15,    20,    25,    30,    40,    55,    70,    85, //  1--10
	  100,   120,   140,   160,   180,   200,   220,   240,   265,   280, // 11--20
	  300,   330,   360,   390,   404,   420,   451,   512,   555,   570, // 21--30
	  600,   640,   666,   700,   740,   777,   800,   840,   888,   900, // 31--40
	  950,  1024,  1111,  1234,  1337,  1496,  1515,  1666,  1789,  1827, // 41--50
	 1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827, // 51--60
	 1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827, // 61--70
	 1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827, // 71--80
	 1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827, // 81--90
	 1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  1827,  6969, // 91--99
};

Script "QCDE_Passive_Eradicator" (void)
{
	// Is it even Eradicator?
	if(!CheckInventory("Class_Eradicator")) terminate;

	// Is it even alive?
	if(GetActorProperty(0,APROP_Health) < 0) terminate;

	int kills_had  = CheckInventory("MurderToken");
	TakeInventory("MurderToken", 1);
	int kills_left = CheckInventory("MurderToken");
	int murder     = CheckInventory("MurderLevel");

	// Does map have enough monsters in cooperative to provide another level?
	if(GameType() < GAME_NET_DEATHMATCH)
	{
		int toofew = GetLevelInfo(LEVELINFO_TOTAL_MONSTERS) - GetLevelInfo(LEVELINFO_KILLED_MONSTERS) < kills_left;
		SetInventory("TooFewMonst", toofew);
	}

	// Initial setup
	if(!murder && !kills_had && !kills_left)
	{
		GiveInventory("MurderToken", level_up_at[murder]);
	}

	// Upgrade time
	else if(!kills_left)
	{
		str take = strparam(s:"PowerMurder", d:murder);
		murder++;
		str give = strparam(s:"PowerMurder", d:murder);
		TakeInventory(take, 1);
		GiveInventory(give, 1);

		GiveInventory("MurderLevel", 1);
		GiveInventory("MurderToken", level_up_at[murder]);
		PlaySound(0,"QC/Abilities/Eradicator/DamageUp", CHAN_VOICE, 1.0, false, 0.6); // couldn't use chans 5 to 7
	}
}

// Activator: dying monster
Script "QCDE_MonsterKill_QCEradicator" (void)
{
	// Due to how this ability was originally coded, it's easier to just
	// change activator pointer and let main passive script do the rest.
	SetActivatorToTarget(0);
	ACS("QCDE_Passive_Eradicator");
}

// Activator: dying victim
Script "QCDE_PlayerKill_QCEradicator" (void)
{
	SetActivatorToTarget(0);
	ACS("QCDE_Passive_Eradicator");
}


//---------------------------------
//		Blazko's Passive

#define TICS_BEFORE_HEAL  70
#define TICS_HEALING_RATE  3
Script "QCDE_Passive_Blazkowicz" (void)
{
	int hp = GetActorProperty(0,APROP_HEALTH);
	int wasntDamagedFor, maxHp;
	while(hp > 0)
	{
		int hpWas = hp;
		hp = GetActorProperty(0,APROP_HEALTH);
		maxHp = CheckInventory("MaxHealthToken");

		if(hp != hpWas) wasntDamagedFor = 0;

		wasntDamagedFor++;

		// heal time! also has room to heal
		if(wasntDamagedFor >= TICS_BEFORE_HEAL  &&  hp % 25  &&  hp < maxHp)
		{
			// play notif
			if(wasntDamagedFor == TICS_BEFORE_HEAL)
				if(hp % 25 < 17)
					PlaySound(0, "QC/Abilities/Blazkowicz/Regen", CHAN_7|CHAN_UI, 0.56, false, ATTN_NONE, true);
				else
					PlaySound(0, "QC/Abilities/Blazkowicz/RegenShort", CHAN_7|CHAN_UI, 0.56, false, ATTN_NONE, true);

			// heal
			if(!(Timer() % TICS_HEALING_RATE))
			{
				hp++;
				HealThingEx(1);
			}
		}

		delay(1);
	}
}



//---------------------------------
//		Freeman's Passive

#define COILS_TO_1_ARMOR    3
#define PERCENT_PER_BFGCELL 2
#define REZ_COOLDOWN_SECS  120
#define FREEMAN_SPOTS       8
int rezCharge[64];
int freem[FREEMAN_SPOTS][3];
Script "QCDE_Passive_Freeman" (void)
{
	int lg0, lg1 = CheckInventory("QCCoilAmmo"), lgdiff;
	int bfg0, bfg1 = CheckInventory("QCBFGAmmo"), bfgdiff;
	int plr = PlayerNumber();
	rezCharge[plr] = 0; // reset extra-half-life
	InitFreemanSpots();
	InitGman();

	while(GetActorProperty(0,APROP_Health) > 0)
	{
		// Puppet / Extraction / Extra-half-life
		// Prevent death.
		rezCharge[plr]++;
		bool ready   = rezCharge[plr] >= REZ_COOLDOWN_SECS * 35;
		bool readyRN = rezCharge[plr] == REZ_COOLDOWN_SECS * 35;
		bool needRez = GetActorProperty(0,APROP_Health) == 1;

		if(hasFlags()) ready = false; // CTF fix
		if(CheckInventory("PowerTerminatorArtifact")) ready = false; // ES fix
		if(GetCvar("qc_freezetag")) // FT fix
		{
			delay(1);
			continue;
		}

		SetInventory("HalfLifeToken", ready);
		SetPlayerProperty(0, ready, PROP_BUDDHA);

		if(ready)
		{
			if(readyRN) PlaySound(0, "QC/Abilities/Freeman/HalfLife", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
			if(needRez)
			{
				rezCharge[plr] = -99999999; // don't restore in this level
				SpawnForced("GmanRezSound", GetActorX(0),GetActorY(0),GetActorZ(0));
				GiveInventory("GmanRezProc", 1);
				if(checkinventory("DMToken"))
				{
					SetInventory("QCHeavyMachinegunDM",0);	//take all the DM weapons except the machinegun
					SetInventory("QCShotgunDM",0);
					SetInventory("QCSuperShotgunDM",0);
					SetInventory("QCNailgunDM",0);
					SetInventory("QCSuperNailgunDM",0);
					SetInventory("QCTriboltDM",0);
					SetInventory("QCRocketLauncherDM",0);
					SetInventory("QCLightningGunDM",0);
					SetInventory("QCRailgunDM",0);
					SetInventory("QCBFGDM",0);
					SetInventory("QCHeavyMachinegun",0);	//also removes the non DM version
					SetInventory("QCShotgun",0);			//just in case there's some oddities with pickups
					SetInventory("QCSuperShotgun",0);
					SetInventory("QCNailgun",0);
					SetInventory("QCSuperNailgun",0);
					SetInventory("QCTribolt",0);
					SetInventory("QCRocketLauncher",0);
					SetInventory("QCLightningGun",0);
					SetInventory("QCRailgun",0);
					SetInventory("QCBFG",0);
					SetInventory("QCShellAmmo",0);		//set all ammo to zero except bullets
					SetInventory("QCNailAmmo",0);
					SetInventory("QCRocketAmmo",0);
					SetInventory("QCCoilAmmo",0);
					SetInventory("QCSlugAmmo",0);
					SetInventory("QCBoltAmmo",0);
					SetInventory("QCBFGAmmo",0);

					SetInventory("BasicArmor",0); //remove armor too

					int startingWeapon = GetCvar("cl_startingWeapon");
					if (startingWeapon == 1) {
						SetInventory("Starter_Machinegun"   ,1);
					} else if (startingWeapon == 2) {
						SetInventory("Starter_Shotgun"   ,1);
					} else if (startingWeapon == 3) {
						SetInventory("Starter_Nailgun"   ,1);
                    }
					ACS_NamedExecuteAlways("QCDE_StartingWeapon_Apply",0);
				}

				// Disable remaining damage over time from possible Quietus hit or Postal's cow head
				quieting_for[PlayerNumber()] = 0;
				cowgassing_for[PlayerNumber()] = 0;

				int spot = PickFreemanSpot();
				//log(s:"Used spot ", d:spot);
				SetActorPosition(0, freem[spot][0],freem[spot][1],freem[spot][2], true);
				SetActorProperty(0, APROP_Health, 25);
				StopSound(0, CHAN_WEAPON);
				PlaySound(0, "QC/Abilities/Freeman/Extract", CHAN_7|CHAN_UI, 0.7, false, ATTN_NONE, true);
				if(random(1,10)==1)	PlaySound(0, "GmanInvestments", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
			}
		}

		delay(1);
	}
}

function void InitFreemanSpots(void)
{
	int x = GetActorX(0);
	int y = GetActorY(0);
	int z = GetActorZ(0) + 0.1337;

	int i;
	for(i = 0; i < FREEMAN_SPOTS; i++)
	{
		if(!freem[FREEMAN_SPOTS-1][2]) // z-coord is chosen because it's ensured to be non-zero
		{
			//log(s:" Initialized spot ", d:i);
			freem[i][0] = x;
			freem[i][1] = y;
			freem[i][2] = z;
		}
		else
			UpdateFreemanSpot();
	}
}

function int PickFreemanSpot(void)
{
	int i, maxdist, maxdistspot;

	for(i = 0; i < FREEMAN_SPOTS; i++)
	{
		int plr = 64;
		int mindist = 0x7FFFFFFF;
		while(plr --> 0)
		{
			if (!PlayerInGame(plr) ||
				PlayerIsSpectator(plr) || // sugondeesedronum
				PlayerNumber() == plr) continue;

			int dx = (GetActorX(1000 + plr) >> 16) - (freem[i][0] >> 16);
			int dy = (GetActorY(1000 + plr) >> 16) - (freem[i][1] >> 16);
			int dz = (GetActorZ(1000 + plr) >> 16) - (freem[i][2] >> 16);

			int dista = Dist(Dist(dx, dy), dz);

			if(dista < mindist) mindist = dista;
		}

		// new best candidate
		if(mindist > maxdist)
		{
			maxdist = mindist;
			maxdistspot = i;
		}
	}

	return maxdistspot;

	//
	// Unused implementation of "farthest to death" below
	//

	int x,y,z;
	for(i = 0; i < FREEMAN_SPOTS; i++)
	{
		int x2 = (freem[i][0]  >> 16) - x;
		int y2 = (freem[i][1]  >> 16) - y;
		int z2 = (freem[i][2]  >> 16) - z;

		int d = Dist(Dist(x2, y2), z2);

		// new best candidate
		if(d > maxdist)
		{
			maxdist = d;
			maxdistspot = i;
		}
	}

	return maxdistspot;
}

function void UpdateFreemanSpot(void)
{
	int x = GetActorX(0);
	int y = GetActorY(0);
	int z = GetActorZ(0) + 1.0;

	int i = random(0,random(0,random(1,FREEMAN_SPOTS-1)));
	//log(s:"Updated spot ", d:i);

	freem[i][0] = x;
	freem[i][1] = y;
	freem[i][2] = z;
}

function void InitGman(void)
{
	if(IsTidUsed(GMAN_TID)) return;

	SpawnForced("Gman",-666.666,-1337.101,-420.69,GMAN_TID);
}

Script "QCDE_GmanShouldLeave" (void)
{
	int leave = true;

	int plrtid;
	for(plrtid = 1000; plrtid < 1064; plrtid++)
		if(CheckActorInventory(plrtid,"Class_Freeman"))
			leave = false;

	SetResultValue(leave);
}


//---------------------------------
//		VorMatur's Passive

Script "QCDE_Passive_VorMatur" (void)
{
	// PVE buff: don't take extra damage
	TakeInventory("PowerPve3BodyProtection",1);

	int hp = GetActorProperty(0,APROP_HEALTH);
	int wasntDamagedFor;
	while(hp > 0)
	{
		delay(1);

		int hpWas = hp;
		hp = GetActorProperty(0,APROP_HEALTH);

		if(hp < hpWas)
		{
			if(hp < -50) hp = -50; // no excess
			int diff = hpWas - hp;

			if(diff < 2) continue; // don't care for degeneration

			if((diff < 11) && (Timer() % 7 < 3)) continue; // rapid-fires don't do this too often

			// How far to spit blood
			int speed = sqrt(diff * 3);
			SetActorProperty(0, APROP_Accuracy, speed/2);

			while(speed --> 0)
				GiveInventory("CorrosiveBloodProc",1);
		}
	}
}

Script "QCDE_SetTarget" (int tid)
{
	str s1 = strparam(n:0);
	SetPointer(AAPTR_TARGET, tid);
	SetActivatorToTarget(0);
	str s2 = strparam(n:0);
	//printbold(s:s1, s:" set target to ", s:s2, s:" tid ", d:tid);
}







//---------------------------------
//		Eleena's Passive

#define ARCADEJUMP_PUSH          1
#define ARCADEFALL_PUSH          5
Script "QCDE_Passive_Eleena" (void)
{
	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		// Training Weights
		if (CheckInventory("BasicArmor") > 15) {
			ACS_NamedExecuteWithResult("QCDE_EleenaAbilityMovement", 1);
		} else {
			ACS_NamedExecuteWithResult("QCDE_EleenaAbilityMovement", 0);
		}

		delay(1);
	}
}

Script "QCDE_Eleena_Jump" (int predicting, int justPressed, int justReleased, int buttons)
{
	if (!justReleased && GetActorVelZ(0) > 1.0)
    	ThrustThingZ(0,ARCADEJUMP_PUSH,0,1);
}

Script "QCDE_Eleena_Crouch" (int predicting, int justPressed, int justReleased, int buttons)
{
	if (!justReleased && GetActorVelZ(0))
		if(!CheckInventory("PowerGrayThumpFlight"))
			ThrustThingZ(0,ARCADEFALL_PUSH,1,1);
}

//---------------------------------
//		Lucienne's Passive

Script "QCDE_Passive_Lucienne" (void)
{
	GiveInventory("NoArmorDegenerationToken", 1);

	// Wait while alive
	while(GetActorProperty(0,APROP_HEALTH) > 0) delay(1);

	int x = GetActorX(0);
	int y = GetActorY(0);
	int z = GetActorZ(0);
	int plrtid = ActivatorTid();
	int tid = plrtid - 1000 + IMMOLATION_TIDBASE;
	SpawnForced("LucienneImmolation", x,y,z, tid);

	SetActivator(tid);
	// Activator: Immolation
	SetPointer(AAPTR_TARGET, plrtid);
}


//---------------------------------
//		Hunter's Passive

#define HUNTER_TRACING_PERIOD 4
// Activator: hunter
Script "QCDE_Passive_Hunter" (void)
{
	int plrtid = ActivatorTid();
	if (GetNetworkState() != NETSTATE_CLIENT && !InDemoMode())
	{
		// Reset previous life's lessons
		if(GameType() <= GAME_NET_COOPERATIVE)
		{
			SetInventory("HunterQCBulletAmmo" ,0);
			SetInventory("HunterQCShellAmmo"  ,0);
			SetInventory("HunterQCNailAmmo"   ,0);
			SetInventory("HunterQCBoltAmmo"   ,0);
			SetInventory("HunterQCRocketAmmo" ,0);
			SetInventory("HunterQCCoilAmmo"   ,0);
			SetInventory("HunterQCSlugAmmo"   ,0);
			SetInventory("HunterQCBFGAmmo"    ,0);
			ACS("QCDE_UpdateBackpackStack");
		}

		while(GetActorProperty(0,APROP_HEALTH) > 0)
		{
			if(GameType() >= GAME_NET_DEATHMATCH) // PVP-only
			{
				SetActivator(plrtid, AAPTR_PLAYER_GETTARGET);
				if(ActivatorTid() && ActivatorTid() != plrtid)
				{
					// Activator: victim
					GiveInventory("HunterProjectionProc",1);
				}
				SetActivator(plrtid);
				// Activator: hunter
			}
			delay(1);
		}
	}
}

// Activator: dying enemy
#define HUNTER_LESSONS 10
str HunterLessons[HUNTER_LESSONS] = {
	"MaxHealthToken","MaxArmorToken",
	"HunterQCBulletAmmo" ,
	"HunterQCShellAmmo"  ,
	"HunterQCNailAmmo"   ,
	"HunterQCBoltAmmo"   ,
	"HunterQCRocketAmmo" ,
	"HunterQCCoilAmmo"   ,
	"HunterQCSlugAmmo"   ,
	"HunterQCBFGAmmo"    ,
};
int HunterLessonsAmount[HUNTER_LESSONS] = { 2,2, 1,1,1,1,1,1,1,1, };
str HunterLessonGFX[HUNTER_LESSONS] = {
	"HEALINCR","ARMOINCR",
	"AmmBullt",
	"AmmShell",
	"AmmNails",
	"AmmBolts",
	"AmmRockt",
	"AmmCoils",
	"AmmSlugs",
	"AmmBfugs",
};

#define MAX_LESSONS_PER_TIC 10
int lastlesson, lessonrn;
Script "QCDE_MonsterKill_QCHunter" (void)
{
	SetActivatorToTarget(0);
	// Activator: Player

	if(!CheckInventory("Class_Hunter")) terminate;

	if(lastlesson != Timer())
	{
		lastlesson = Timer();
		lessonrn = 0;
	}
	else if(lessonrn < MAX_LESSONS_PER_TIC)
		lessonrn++;

	if(!lessonrn) PlaySound(0, "QC/Abilities/Hunter/Learn", CHAN_7|CHAN_UI, 0.86, false, ATTN_NONE, true);

	int type = random(1, HUNTER_LESSONS) - 1;
	//log(n:0, s:" taking the ", s:HunterLessons[type], s:" lesson.");
	GiveInventory(HunterLessons[type],HunterLessonsAmount[type]);
	ACS("QCDE_UpdateBackpackStack");

	SetHudSize(2800,2100,true);
	SetFont(HunterLessonGFX[type]);
	HudMessage(s:"A"; HUDMSG_FADEOUT, HMID_HUNTER_LESSON + lessonrn, -1, 174.0, 1590.0 - lessonrn * 80.0, 0.1, 0.3);
}

Script "QCDE_PlayerKill_QCHunter" (void)
{
	SetActivatorToTarget(0);
	// Activator: Player

	if(!CheckInventory("Class_Hunter")) terminate;

	if(lastlesson != Timer())
	{
		lastlesson = Timer();
		lessonrn = 0;
	}
	else if(lessonrn < MAX_LESSONS_PER_TIC)
		lessonrn++;

	if(!lessonrn) PlaySound(0, "QC/Abilities/Hunter/Learn", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);

	int type = (random(1, HUNTER_LESSONS) - 1) % 2;
	//log(n:0, s:" taking the ", s:HunterLessons[type], s:" lesson.");
	GiveInventory(HunterLessons[type],HunterLessonsAmount[type]);

	SetHudSize(2800,2100,true);
	SetFont(HunterLessonGFX[type]);
	HudMessage(s:"A"; HUDMSG_FADEOUT, HMID_HUNTER_LESSON + lessonrn, -1, 174.0, 1590.0 - lessonrn * 80.0, 0.1, 0.3);
}

Script "QCDE_Traced" (void)
{
	if(GetActorPowerupTics(0, "PowerTraced")) terminate;
	if(CheckInventory("PowerGhostTint")) terminate;

	//Log(n:0, s:" starting getting traced");
	GiveInventory("GetTraced",1);
	int plr = PlayerNumber();
	ACS("QCDE_Traced_CLIENTSIDE");
	while(GetActorProperty(0,APROP_HEALTH) > 0 && GetActorPowerupTics(0, "PowerTraced")) delay(1);
}

Script "QCDE_Traced_CLIENTSIDE" (void) clientside
{
	int spectator = PlayerIsSpectator(CPN()); // Spectators can see
	int iam = CheckActorInventory(CPN()+1000, "Class_Hunter"); // Hunters can see

	if(!(spectator || iam)) terminate;

	int plr = PlayerNumber();
	int mine = CPN() == plr; // You can't see your own
	int spectatee = CheckPlayerCamera(CPN()) == 1000 + plr; // Nor your spectatee
	int team = !areEnemies(CPN(), plr); // Nor do you care about your team's

	if(mine || spectatee || team) terminate;

	while(GetActorProperty(0,APROP_HEALTH) > 0 && GetActorPowerupTics(0, "PowerTraced"))
	{
		int x = GetActorX(0);
		int y = GetActorY(0);
		int z = GetActorZ(0);
		int tid = UniqueTid();
		int a = GetActorAngle(0) >> 8;
		SpawnForced("HunterTrace", x,y,z, tid, a);

		SetStateByClass(tid);
		int translation = GetActorProperty(0, APROP_Translation);
		SetActorProperty(tid, APROP_Translation, translation);

		Thing_ChangeTID(tid,0); // free tid just in case
		//Log(n:0, s:" trace remaining tics: ", d:GetActorPowerupTics(0, "PowerTraced"));
		int t = 0;
		while(t ++< 1 + HUNTER_TRACING_PERIOD * 20 /-~ dist(GetActorVelX(0)>>16, GetActorVelY(0)>>16)) delay(1);
	}
}

function void SetStateByClass(int tid)
{
	SetActorProperty(tid, APROP_ScaleX, GetActorProperty(0, APROP_ScaleX));
	SetActorProperty(tid, APROP_ScaleY, GetActorProperty(0, APROP_ScaleY));

	if(CheckActorClass(0,"QCRanger"    )) { SetActorState(tid, "Ranger"    ); return; }
	if(CheckActorClass(0,"QCDoomslayer")) { SetActorState(tid, "Doomslayer"); return; }
	if(CheckActorClass(0,"QCCorvus"    )) { SetActorState(tid, "Corvus"    ); return; }
	if(CheckActorClass(0,"QCKane"      )) { SetActorState(tid, "Kane"      ); return; }
	if(CheckActorClass(0,"QCCaleb"     )) { SetActorState(tid, "Caleb"     ); return; }
	if(CheckActorClass(0,"QCMenelkir"  )) { SetActorState(tid, "Menelkir"  ); return; }
	if(CheckActorClass(0,"QCTerminator")) { SetActorState(tid, "Terminator"); return; }
	if(CheckActorClass(0,"QCZedek"     )) { SetActorState(tid, "Zedek"     ); return; }
	if(CheckActorClass(0,"QCInquisitor")) { SetActorState(tid, "Inquisitor"); return; }
	if(CheckActorClass(0,"QCBitterman" )) { SetActorState(tid, "Bitterman" ); return; }
	if(CheckActorClass(0,"QCGalen"     )) { SetActorState(tid, "Galen"     ); return; }
	if(CheckActorClass(0,"QCNyx"       )) { SetActorState(tid, "Nyx"       ); return; }
	if(CheckActorClass(0,"QCSorgaul"   )) { SetActorState(tid, "Sorgaul"   ); return; }
	if(CheckActorClass(0,"QCDukeNukem" )) { SetActorState(tid, "DukeNukem" ); return; }
	if(CheckActorClass(0,"QCDurandal"  )) { SetActorState(tid, "Durandal"  ); return; }
	if(CheckActorClass(0,"QCKeel"      )) { SetActorState(tid, "Keel"      ); return; }
	if(CheckActorClass(0,"QCSarge"     )) { SetActorState(tid, "Sarge"     ); return; }
	if(CheckActorClass(0,"QCLoWang"    )) { SetActorState(tid, "LoWang"    ); return; }
	if(CheckActorClass(0,"QCGrayson"   )) { SetActorState(tid, "Grayson"   ); return; }
	if(CheckActorClass(0,"QCEradicator")) { SetActorState(tid, "Eradicator"); return; }
	if(CheckActorClass(0,"QCBlazkowicz")) { SetActorState(tid, "Blazkowicz"); return; }
	if(CheckActorClass(0,"QCFreeman"   )) { SetActorState(tid, "Freeman"   ); return; }
	if(CheckActorClass(0,"QCVorMatur"  )) { SetActorState(tid, "VorMatur"  ); return; }
	if(CheckActorClass(0,"QCEleena"    )) { SetActorState(tid, "Eleena"    ); return; }
	if(CheckActorClass(0,"QCLucienne"  )) { SetActorState(tid, "Lucienne"  ); return; }
	if(CheckActorClass(0,"QCMajor"     )) { SetActorState(tid, "Major"     ); return; }
	if(CheckActorClass(0,"QCHunter"    )) { SetActorState(tid, "Hunter"    ); return; }
	if(CheckActorClass(0,"QCSam"       )) { SetActorState(tid, "Sam"       ); return; }
	if(CheckActorClass(0,"QCPostal"    )) { SetActorState(tid, "Postal"    ); return; }
	if(CheckActorClass(0,"QCPainkiller")) { SetActorState(tid, "Painkiller"); return; }
	if(CheckActorClass(0,"QCIntruder"  )) { SetActorState(tid, "Intruder"  ); return; }
	if(CheckActorClass(0,"QCOrbb"      )) { SetActorState(tid, "Orbb"      ); return; }
	// ^ insert more classes here
}




//---------------------------------
//		Serious Sam's Passive
// Same script for start of life and picking up armor
// Because it was more fun to code it that way
// I'll commit SMH now [Ms]

Script "QCDE_Passive_Sam" (int ammo)
{
	if(!ammo) // Start of life
	{
		SetInventory("SeriousBullets",80);
        int startingWeapon = GetCvar("cl_startingWeapon");
		if(GameType() <= GAME_NET_COOPERATIVE)
		{
			if(!CheckInventory("QCHeavyMachinegun")) GiveInventory("QCMachineGun", 1);
			SetInventory("QCShotgun"   ,1);
         	if(!CheckInventory("QCSuperNailgun")) GiveInventory("QCNailgun", 1);
			SetInventory("SamMinigun"  ,0);
			SetInventory("SeriousBullets",GetAmmoCapacity("SeriousBullets"));
			
            switch(startingWeapon)
            {
            default: // go to case 1
            case 1: SetWeapon("QCMachineGun");	break;
            case 2: SetWeapon("QCShotgun");		break;
            case 3: SetWeapon("QCNailgun");		break;
            }
		}
		else if(!GetCvar("instagib") && !GetCvar("rocketarena"))
		{
			SetInventory("QCMachineGunDM",1);
			SetInventory("QCShotgunDM"   ,1);
			SetInventory("QCNailgunDM"   ,1);
			
			if		(CheckInventory("Starter_Machinegun"))	SetWeapon("QCMachineGunDM");
            else if	(CheckInventory("Starter_Shotgun"   ))	SetWeapon("QCShotgunDM");
            else if	(CheckInventory("Starter_Nailgun"   ))	SetWeapon("QCNailgunDM");
            else
            {
            	switch(startingWeapon)
            	{
            	default: // go to case 1
            	case 1: SetWeapon("QCMachineGunDM");	break;
            	case 2: SetWeapon("QCShotgunDM");		break;
            	case 3: SetWeapon("QCNailgunDM");		break;
            	}
            }
		}
	}
	else // Giving ammo
	{
		int type, amount;
		if      (qcContains("Mac"))	{ type = AmmoType[0]; amount = getSamAmmoBonus(0) * ammo; }
		else if (qcContains("Sho"))	{ type = AmmoType[1]; amount = getSamAmmoBonus(1) * ammo; }
		else if (qcContains("Nai"))	{ type = AmmoType[2]; amount = getSamAmmoBonus(2) * ammo; }
		else if (qcContains("Tri"))	{ type = AmmoType[3]; amount = getSamAmmoBonus(3) * ammo; }
		else if (qcContains("Roc"))	{ type = AmmoType[4]; amount = getSamAmmoBonus(4) * ammo; }
		else if (qcContains("Lig"))	{ type = AmmoType[5]; amount = getSamAmmoBonus(5) * ammo; }
		else if (qcContains("Rai"))	{ type = AmmoType[6]; amount = getSamAmmoBonus(6) * ammo; }
		else if (qcContains("BFG"))	{ type = AmmoType[7]; amount = getSamAmmoBonus(7) * ammo; }
		else if (qcContains("mMi"))	{ type = "SeriousBullets"; amount = 10 * ammo; }
		else terminate;

		GiveInventory(type, amount);
	}
}

Script "QCDE_Sam_Bullets_Full"
{
	if (CheckInventory("SeriousBullets") >= GetAmmoCapacity("SeriousBullets"))
		SetResultValue(1);
	else
		SetResultValue(0);
}



//---------------------------------
//		Postal's Passive

#define POSTAL_UPWARD_PUSH 3
Script "QCDE_Passive_Postal" (void)
{
	// Check crackpipe stuck in throat from last map
	if(!CheckInventory("NoArmorDegenerationToken") && // Having no armor degen means there was a reliq
	    CheckInventory("NoHealthDegenerationToken"))
		TakeInventory("NoHealthDegenerationToken",1);
}

// Pressing jump automatically unpresses crouch.
// Luckily, jump script is always executed before crouch script, so we can add more velocity on crouch script release
bool postalJustJumped[64];

Script "QCDE_Postal_Jump" (int predicting, int justPressed, int justReleased, int buttons)
{
	if (justPressed && (CheckSolidFooting(0, 0) != CSF_INAIR))
		postalJustJumped[PlayerNumber()] = true;
}

Script "QCDE_Postal_Crouch" (int predicting, int justPressed, int justReleased, int buttons)
{
	if (justReleased && postalJustJumped[PlayerNumber()])
	{
		ThrustThingZ(0, POSTAL_UPWARD_PUSH * 4, 0, 1);
		postalJustJumped[PlayerNumber()] = false;
	}
}

#define POSTAL_CRACKPIPE_SECONDS_COOP 90
#define POSTAL_CRACKPIPE_SECONDS_DM   40
#define POSTAL_CRACKPIPE_WARNING      15
#define POSTAL_EXTRA_DEGEN_MAX        50
#define POSTAL_EXTRA_DEGEN_PERIOD     20
#define POSTAL_INSTANT_WITHDRAWAL     25
#define POSTAL_LOGGING             false
Script "QCDE_Passive_Postal_Mega" (void)
{
	if(CheckInventory("NoArmorDegenerationToken")) terminate; // has "no degen" reliq

	int t = POSTAL_CRACKPIPE_SECONDS_DM;
	if(GameType() < GAME_NET_DEATHMATCH) t = POSTAL_CRACKPIPE_SECONDS_COOP;
	if(CheckInventory("HighOnCrack")) // hooked
	{
		if(POSTAL_LOGGING) print(s:"\c[RG]Updated seconds before withdrawal, not starting another counter");
		SetInventory("HighOnCrack", t);
		terminate;
	}

	// High
	GiveInventory("HighOnCrack", t);
	delay(1);
	GiveInventory("NoHealthDegenerationToken",1);

	delay(16);
	if(!random(0,3))
		PlaySound(0, "QC/Abilities/Postal/Postal_Smoke", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);

	while(CheckInventory("HighOnCrack"))
	{
		if(GetActorProperty(0, APROP_Health) <= 0) terminate; // keep an eye on staying alive
		if(CheckInventory("HighOnCrack") == POSTAL_CRACKPIPE_WARNING) PlaySound(0, "QC/Abilities/Postal/Postal_Warning", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
		if(POSTAL_LOGGING) print(s:"\c[brite]Seconds before withdrawal: ", d:CheckInventory("HighOnCrack"));
		TakeInventory("HighOnCrack", 1);
		delay(35);
	}

	if(CheckInventory("NoArmorDegenerationToken")) terminate; // got "no degen" reliq
	TakeInventory("NoHealthDegenerationToken",1);

	// Withdrawal
	PlaySound(0, "QC/Abilities/Postal/Postal_Withdraw", CHAN_7|CHAN_UI, 1.0, false, ATTN_NONE, true);
	t = POSTAL_EXTRA_DEGEN_MAX;
	int hp = GetActorProperty(0, APROP_Health);
	if(hp <= CheckInventory("MaxHealthToken")) // has no overstack, so instant pain of withdrawal
	{
		hp -= POSTAL_INSTANT_WITHDRAWAL;
		if(hp > 0)
			SetActorProperty(0, APROP_Health, hp);
		else
			SetActorProperty(0, APROP_Health, 1);
		if(POSTAL_LOGGING) print(s:"No overstack: instant punishment to \c[bludi]", d:hp);
		terminate;
	}
	else while(t --> 0)
	{
		delay(POSTAL_EXTRA_DEGEN_PERIOD);
		if(POSTAL_LOGGING) print(s:"Extra degen after withdrawal: \c[bludi]", d:t);
		if(CheckInventory("NoHealthDegenerationToken")) terminate; // got "no degen" reliq or another mega

		hp = GetActorProperty(0, APROP_Health);
		if(hp <= 0) break; // died. New body shouldn't suffer for old one's sins (but it might due to rompy-stompy bug)
		if(hp <= CheckInventory("MaxHealthToken")) break; // has no overstack, no more withdrawal

		SetActorProperty(0, APROP_Health, hp - 1);
	}
	if(POSTAL_LOGGING) print(s:"\c[SNG]I'm fine today.");
}



//---------------------------------
//		Painkiller's Passive

#define SOUL_THRESHOLD_COOP 66
#define SOUL_THRESHOLD_DM    6


Script "QCDE_Passive_Painkiller" (int activate)
{
	if(!activate) terminate;
	if (GetNetworkState() == NETSTATE_CLIENT || InDemoMode())
		terminate;

	int hp = GetActorProperty(0, APROP_Health);
	int ap = CheckInventory("BasicArmor");

	delay(1); // Necessary not to crash GZDoom on morph

	ACS_NamedExecuteWithResult("QCDE_PainkillerAbilityMovement", 0);
	int translation = GetActorProperty(0, APROP_Translation);
	GiveInventory("DemonMorphProc",1);
	SetActorProperty(0, APROP_Translation, translation);
	// Break tarot if active
	GiveInventory("NoAbilitiesToken",1);
	for(int i = 1; i <= 3; i++)
		for(int j = 1; j <= 3; j++)
			SetInventory(strparam(s:"PainkillerCard", d:i, s:"Level", d:j), 0);

	// ES fix: consume soul, let it respawn
	TakeInventory("PowerTermToken",1);
	TakeInventory("PowerTerminatorArtifact",1);
	TakeInventory("PowerEldersSoul",1);

	ACS("QCDE_DM_DropPowerups");

	int t = GetActorPowerupTics(0, "PowerDemonMorph");
	ACS("QCDE_ShowActiveInProgress", t);
	if (GetNetworkState() == NETSTATE_SERVER)
		ACS("QCDE_ShowActiveInProgress_CLIENTSIDE", t);

	GiveInventory("NoReticle", 1);
	GiveInventory("NoAmmoCount", 1);
	GiveInventory("NoAbilityIcon", 1);

	// Progress
	while(CheckInventory("PowerDemonMorph"))
		if(t --> 0)
			delay(1);
		else
			break;
	UnmorphActor(0,true); // necessary extra layer

	// Morph ended
	GiveInventory("PainkillerCleanerProc",1);
	ACS_NamedExecuteAlways("QCDE_ConfigureMovement", 0);
	if(GetActorProperty(0, APROP_Health) < 0) terminate;

	// Morph ended successfully
	SetActorProperty(0, APROP_Health, hp);
	TakeInventory("QCArmorPoint", ap);
	GiveInventory("QCArmorPoint", ap);
}

// Activator: dying monster
Script "QCDE_MonsterKill_QCPainkiller" (int xdeath)
{
	str class = "PainkillerSoul";
	if(CheckInventory("MonsterBig") || CheckInventory("MonsterBoss"))
		class = "PainkillerSoulBig";
	SpawnSpotForced(class,0,0,0);
}

// Activator: dying victim
Script "QCDE_PlayerKill_QCPainkiller" (void)
{
	str class = "PainkillerSoulDM";
	SpawnSpotForced(class,0,0,0);

	// Activator: Pain killer
	SetActivatorToTarget(0);
	if(PlayerIsBot(PlayerNumber()) && random(0,3))
		GiveInventory("PainkillerSoulDM", 1);
}


Script "QCDE_Passive_Intruder" (void)
{
	int secrets;
	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		if(secrets < GetLevelInfo(LEVELINFO_FOUND_SECRETS))
		{
			ACS("ArmorGiver", ACS("MaxArmor"), 50, true);
			ACS("QCDE_IntruderMoraleBoost");
		}

		secrets = GetLevelInfo(LEVELINFO_FOUND_SECRETS);
		delay(1);
	}
}





Script "QCDE_MonsterKill_QCIntruder" (void)
{
	SetActivatorToTarget(0);
	// Activator: Player

	if(!CheckInventory("Class_Intruder")) terminate;

	if(!CheckInventory("PowerWendigoTint"))
	{
		PlaySound(0, "QC/Abilities/Intruder/BonusPick", CHAN_7|CHAN_UI, 0.86, false, ATTN_NONE, true);
		GiveInventory("IntruderSpeeder",1);
	}
}

Script "QCDE_PlayerKill_QCIntruder" (void)
{
	SetActivatorToTarget(0);
	// Activator: Player

	if(!CheckInventory("Class_Intruder")) terminate;

	if(!CheckInventory("PowerWendigoTint"))
	{
		PlaySound(0, "QC/Abilities/Intruder/BonusPick", CHAN_7|CHAN_UI, 0.86, false, ATTN_NONE, true);
		GiveInventory("IntruderSpeeder",1);
	}
}


//---------------------------------
//		Orbb's Passive

#define ORBB_BOUNCE_THRESHOLD	-11.0

bool orbbVelocityZ[64];

Script "QCDE_Orbb_Bounce" (int predicting, int justPressed, int justReleased, int buttons)
{
	if (predicting)
	{
		if (GetPredictableValue(0, 0))
		{
			SetActorVelocity(0, GetActorVelX(0), GetActorVelY(0), GetPredictableValue(0, 1), 0, 0);
		}
	}
	else
	{
		if ( ( CheckSolidFooting(0, 0) != CSF_INAIR ) && ( orbbVelocityZ[PlayerNumber()] < ORBB_BOUNCE_THRESHOLD ) )
		{
			SetActorVelocity(0, GetActorVelX(0), GetActorVelY(0), -orbbVelocityZ[PlayerNumber()], 0, 0);
			SetPredictableValue(0, 0, 1);
			SetPredictableValue(0, 1, -orbbVelocityZ[PlayerNumber()]);
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			PlaySound(0, "OrbbJump", CHAN_BODY);
			SetNetworkReplicationFlags( 0 );
		}

		orbbVelocityZ[PlayerNumber()] = GetActorVelZ(0) * 82 / 100;
	}
}
