#library "BEHAVIOR"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"

//=============================================================================
//=============================================================================
//
// |__ | __  __|  |__  __
// |  \|/  |/  |_/|  \/  \\_/
// |__/|\__|\__| \|__/\__// \
//
// Sources of this script will be removed for release.
//
//=============================================================================
//=============================================================================

//*******************************************************
// Airplane easter egg
//*******************************************************

Script "QCDE_Airplane" OPEN
{
	while(!GetCVar("please_no_more_airplanes"))
	{
		delay(35 * 35);
		int time = SystemTime();
		time = GetTimeProperty(time, 2, false) * 100 + GetTimeProperty(time, 1, false);
		if (time == 420  ||  time == 1337)
		{
			AmbientSound("Airplane!", 127);
			if(GameType() >= GAME_SINGLE_PLAYER)
				Log(s:"Airplane!");
			delay(8*35);
			Radius_Quake(1, 5*35, 0, 64, 1000);
		}
	}
}

Script "QCDE_GetDate" (void)
{
	int time = SystemTime();
	time = GetTimeProperty(time, 3, false) * 100 + -~GetTimeProperty(time, 4, false);
	SetResultValue(time);
}



//*******************************************************
// Cheat for getting unfair frags in DM
//*******************************************************

script "bepis" (int howmany, int aswho)
{
	if(!aswho) aswho = PlayerNumber() + 1;

	while(howmany)
	{
		delay(1);

		int victim = 1000 + random(0, PlayerCount() - 1);

		if(victim == ActivatorTid()) continue;
		if(GetActorProperty(victim, APROP_HEALTH) <= 0) continue;

		int x = GetActorX(victim);
		int y = GetActorY(victim);
		int z = GetActorZ(victim) + 16.0;
		SpawnForced("Testball",x,y,z, 19738456 + aswho);

		// Activator: killing projectile
		SetActivator(19738456 + aswho);
		SetPointer(AAPTR_TARGET, 999 + aswho);

		// Activator: cheat beneficiary
		SetActivator(999 + aswho);
		howmany--;
	}
	print(s:"frags received");
}


//*******************************************************
// Cheat for getting unfair lootboxes
//*******************************************************

script "whomstdve" (int howmany, int whomst)
{
	if(!whomst)  whomst  = PlayerNumber();
	if(!howmany) howmany = 25;

	deserved[whomst    ] += howmany;
	deserved[whomst+ 64] += howmany;
	deserved[whomst+128] += howmany;
	GiveInventory("LBBackpack",  howmany);
	GiveInventory("LBChest",     howmany);
	GiveInventory("LBReliquary", howmany);

	SetActivator(1000 + whomst);
	print(d:howmany, s:" lootboxes of each kind unlocked");
}



//*******************************************************
// Cheat to prevent bots from shooting and casting
//*******************************************************

int dontshoot_ticsleft;
script "dontshoot" (int seconds)
{
	if(!seconds) seconds = 60;

	dontshoot_ticsleft = seconds * 35;
	print(s:"Bot weapons and abilities disabled for ", d:seconds);

	int plr;
	while(dontshoot_ticsleft --> 0)
	{
		delay(1);
		plr = 64;
		while(plr --> 0) if(PlayerIsBot(plr))
		{
			SetActorInventory(1000 + plr, "NoWeaponFireToken", true);
			SetActorInventory(1000 + plr, "NoAbilitiesToken", true);
		}
	}

	plr = 64;
	while(plr --> 0) if(PlayerIsBot(plr))
	{
		SetActorInventory(1000 + plr, "NoWeaponFireToken", false);
		SetActorInventory(1000 + plr, "NoAbilitiesToken", false);
	}
}

//*******************************************************
// Cheat to prevent bots from moving
//*******************************************************

int dontmove_ticsleft;
script "dontmove" (int seconds)
{
	if(!seconds) seconds = 60;

	dontmove_ticsleft = seconds * 35;
	print(s:"Bot movement disabled for ", d:seconds);

	int plr;
	while(dontmove_ticsleft --> 0)
	{
		delay(1);
		plr = 64;
		while(plr --> 0) if(PlayerIsBot(plr))
		{
			SetActorInventory(1000 + plr, "Twitchless3sec", 1);
			SetActorInventory(1000 + plr, "Motionless3sec", 1);
		}
	}
}

//*******************************************************
// Cheat to prevent bots from living
//*******************************************************

script "dontlive" (int team)
{
	print(s:"Bot lives ended for team ", d:team);

	int plr = 64;
	while(plr --> 0) if(PlayerIsBot(plr)) if(!team  ||  GetPlayerInfo(plr, PLAYERINFO_TEAM) == (team-1))
	{
		SetActorProperty(1000 + plr, APROP_Health, 0);
	}
}

//*****************************************************************************
// Security through obscurity. Yikes!
// Returns string that is not easy to type in console to use as weak proof
// that some input doesn't come from user.
//*****************************************************************************
script "QCDE_GetKey" (void)
{
	SetResultValue(strparam(s:"鳞~L~`🅱\r\0\"\\\"\n", d:Timer() * 2 + 1));
}

//*****************************************************************************
// This is almost the recreation of SHA-256 hashing algorithm.
// "Cryptographically secure hashing functions? In *my* Zandronum?"
// It's more likely than you think.                          [ Free Check Now ]
//*****************************************************************************

script "SHA" (void) net clientside
{
	int s;
	s = "";     log(s:"f(\"", s:s, s:"\") = ", s:ska(s));
	s = "test"; log(s:"f(\"", s:s, s:"\") = ", s:ska(s));
}

int K[64] =
	{	0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
		0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
		0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
		0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
		0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
		0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
		0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
		0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
		0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
		0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
		0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2 };
int w[64];
function int ska(int input)
{
	int i, j, ww1, ww4, l = strlen(input);

	int message = strparam(s:input, c:0x80);

	int padding = 64 - ((l + 1) % (512 / 8));
	if(padding < 8) padding += 64;
	log(s:"padding ", d:padding, s:"    for len ", d:l);
	while(padding --> 0)
		message = strparam(s:message, c:0);
	int l1 = strlen(message);
	log(s:"l1 ", d:l1);

	l *= 8;

	message = strparam(s:strleft(message, l1 - 8), c:0, c:0, c:0, c:0, c:(l & 0xFF000000) >> 24, c:(l & 0xFF0000) >> 16, c:(l & 0xFF00) >> 8, c:l & 0xFF);

	int h0 = 0x6a09e667;
	int h1 = 0xbb67ae85;
	int h2 = 0x3c6ef372;
	int h3 = 0xa54ff53a;
	int h4 = 0x510e527f;
	int h5 = 0x9b05688c;
	int h6 = 0x1f83d9ab;
	int h7 = 0x5be0cd19;
	int a, b, c, d, e, f, g, h;
	int t1, t2;
	int lastblock = (l1 - 1) / 64;

	for(j = 0; l <= lastblock; j++)
	{
		//
		int block = strmid(message, j*64, 64);
		log(s:"block ", d:j, s:" of ", d:lastblock, s:": ", s:block);

		for(i = 0; i <= 15; i++)
			w[i] = getchar(block,i) + (getchar(block,i+1) << 8) + (getchar(block,i+2) << 16) + (getchar(block,i+3) << 24);

		for(i = 16; i <= 63; i++)
			w[i] = sigma3(w[i-2]) + w[i-7] + sigma2(w[i-15]) + w[i-16];

		a = h0; b = h1; c = h2; d = h3; e = h4; f = h5; g = h6; h = h7;

		for(i = 0; i <= 63; i++)
		{
			t1 = h + sigma1(e) + ch(e, f, g) + K[i] + w[i];
			t2 = sigma0(a) + maj(a, b, c);
			h = g; g = f; f = e;
			e = d + t1;
			d = c; c = b; b = a;
			a = t1 + t2;
		}

		h0 += a ; h1 += b ; h2 += c ; h3 += d ;
		h4 += e ; h5 += f ; h6 += g ; h7 += h ;
	}

	int answer = strparam(x:h0,x:h1,x:h2,x:h3,x:h4,x:h5,x:h6,x:h7);
	return answer;

}


function int ch(int x, int y, int z)
{
	return (x & y) ^ (~x & z);
}

function int maj(int x, int y, int z)
{
	return (x & y) ^ (x & z) ^ (y & z);
}

function int sigma0(int x) {
	return ((x >> 2 | x << 30) ^ (x >> 13 | x << 19) ^ (x >> 22 | x << 10));
}

function int sigma1(int x) {
	return ((x >> 6 | x << 26) ^ (x >> 11 | x << 21) ^ (x >> 25 | x << 7));
}

function int sigma2(int x) {
	return ((x >> 7 | x << 25) ^ (x >> 18 | x << 14) ^ (x >> 3));
}

function int sigma3(int x) {
	return ((x >> 17 | x << 15) ^ (x >> 19 | x << 13) ^ (x >> 10));
}

/*

	private int ska(int input)
	{
		int i, j, ww1, ww4, l = strlen(input);

		int message = strparam("s:input, c:0x80");

		int padding = 64 - ((l + 1) % (512 / 8));
		if(padding < 8) padding += 64;
		while(padding --> 0)
			message = strparam("s:message, c:0");
		int l1 = strlen(message);

		l *= 8;

		message = strparam("s:strleft(message, l1 - 8), c:0, c:0, c:0, c:0, c:(l & 0xFF000000) >> 24, c:(l & 0xFF0000) >> 16, c:(l & 0xFF00) >> 8, c:l & 0xFF");

		int h0 = 0x6a09e667;
		int h1 = 0xbb67ae85;
		int h2 = 0x3c6ef372;
		int h3 = 0xa54ff53a;
		int h4 = 0x510e527f;
		int h5 = 0x9b05688c;
		int h6 = 0x1f83d9ab;
		int h7 = 0x5be0cd19;
		int a, b, c, d, e, f, g, h;
		int t1, t2, w[64];
		int lastblock = (l1 - 1) / 64;

		for(j = 0; l <= lastblock; j++)
		{
			//
			int block = strmid(message, j*64, 64);
			//log(s:"block ", d:j, s:": ", s:block);
			for(i = 0; i <= 60; i += 4)
			{
			    block = strparam("s:strleft(block, i), c:getChar(block,i+3), c:getChar(block,i+2), c:getChar(block,i+1), c:getChar(block,i), s:strright(block, 60-i)");
			    //log(s:"endianness: ", s:block);
			}

			for(i = 0; i <= 15; i++)
			    w[i] = getchar(block,i+3) + (getchar(block,i+2) << 8) + (getchar(block,i+1) << 16) + (getchar(block,i) << 24);

			for(i = 16; i <= 63; i++)
			    w[i] = sigma3(w[i-2]) + w[i-7] + sigma2(w[i-15]) + w[i-16];

			a = h0; b = h1; c = h2; d = h3; e = h4; f = h5; g = h6; h = h7;

			for(i = 0; i <= 63; i++)
			{
			    t1 = h + sigma1(e) + ch(e, f, g) + k[i] + w[i];
			    t2 = sigma0(a) + maj(a, b, c);
			    h = g; g = f; f = e;
			    e = d + t1;
			    d = c; c = b; b = a;
			    a = t1 + t2;
			}

			h0 += a ; h1 += b ; h2 += c ; h3 += d ;
			h4 += e ; h5 += f ; h6 += g ; h7 += h ;
		}

		int answer = strparam("x:h0,x:h1,x:h2,x:h3,x:h4,x:h5,x:h6,x:h7");
		return answer;

	}

	int K[64] =
	{ 0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
			0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
			0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
			0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
			0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
			0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
			0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
			0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
			0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
			0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
			0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2 };

	private int ch(int x, int y, int z)
	{
		return (x & y) ^ (~x & z);
	}

	private int maj(int x, int y, int z)
	{
		return (x & y) ^ (x & z) ^ (y & z);
	}

	private int sigma0(int x) {
		return ((x >> 2 | x << 30) ^ (x >> 13 | x << 19) ^ (x >> 22 | x << 10));
	}

	private int sigma1(int x) {
		return ((x >> 6 | x << 26) ^ (x >> 11 | x << 21) ^ (x >> 25 | x << 7));
	}

	private int sigma2(int x) {
		return ((x >> 7 | x << 25) ^ (x >> 18 | x << 14) ^ (x >> 3));
	}

	private int sigma3(int x) {
		return ((x >> 17 | x << 15) ^ (x >> 19 | x << 13) ^ (x >> 10));
	}

	// nameholders

	protected int strlen(int l) { return -1; }

	protected int strparam(Object... x) { return -1; }

	protected int strleft(int a, int b) {return 0;}
	protected int strright(int a, int b) {return 0;}
	protected int strmid(int a, int b, int c) {return 0;}
	protected int getchar(int a, int b) {return 0;}

*/
