#library "BOTIMPRO"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"

//=============================================================================
//=============================================================================
//=============================================================================
//
//
//		BOT IMPROVEMENT RELATED SCRIPTS
//
//
//=============================================================================
//=============================================================================
//=============================================================================

str BotPreferredWeapons[8] = {
		"QCHeavyMachinegunDM",
		"QCSuperShotgunDM",
		"QCSuperNailgunDM",
		"QCTriboltDM",
		"QCRocketLauncherDM",
		"QCLightningGunDM",
		"QCRailgunDM",
		"QCBFGDM"
		};

script "QCDE_Bot_Weaponize" (void)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate; // bots only matter in DM

	// Very special cases for special modes
	if(GetCVar("instagib"))	{ GiveInventory("QCRailgunDM",      1); terminate; }
	if(GetCVar("buckshot"))	{ GiveInventory("QCSuperShotgunDM", 1); terminate; }

	if(GetCVar("teamlms")) terminate;
	if(!GetCVar("bot_weaponize")) terminate;

	int skill = GetCVar("bot_weaponize") + GetCVar("botskill");

	// Skill-based chance to get weapons
	if( random(1,10) <= skill ) if( ACS("QCDE_IsWeaponOnMap", 8) )	GiveInventory("QCHeavyMachinegunDM"	,1);
	if( random(2,10) <= skill ) if( ACS("QCDE_IsWeaponOnMap",10) )	GiveInventory("QCSuperShotgunDM"	,1);
	if( random(3,10) <= skill ) if( ACS("QCDE_IsWeaponOnMap",12) )	GiveInventory("QCSuperNailgunDM"	,1);
	if( random(4,20) <= skill ) if( ACS("QCDE_IsWeaponOnMap",14) )	GiveInventory("QCTriboltDM"			,1);
	if( random(5,10) <= skill ) if( ACS("QCDE_IsWeaponOnMap",16) )	GiveInventory("QCRocketLauncherDM"	,1);
	if( random(6,20) <= skill ) if( ACS("QCDE_IsWeaponOnMap",18) )	GiveInventory("QCLightningGunDM"	,1);
	if( random(7,15) <= skill ) if( ACS("QCDE_IsWeaponOnMap",20) )	GiveInventory("QCRailgunDM"			,1);
	if( random(8,40) <= skill ) if( ACS("QCDE_IsWeaponOnMap",22) )	GiveInventory("QCBFGDM"				,1);
}

script "QCDE_Bot_Buff" (void)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate; // bots only matter in DM

	int buff = GetCVar("bot_buff");

	if(!buff) terminate;

	buff += GetCVar("botskill") - 2;

	// Chance to get hEaLiNg
	if( random(0,20) < buff ) 	GiveInventory("QCStimpack", 1);
}

script "QCDE_Bot_SelectWeapon" (void)
{
	// Unless is using an ability weapon
	if(CheckWeapon("SorgaulFists"     )) terminate;
	if(CheckWeapon("SorgaulFistsBot"  )) terminate;
	if(CheckWeapon("Shieldquisitor"   )) terminate;
	if(CheckWeapon("SlayerBFG"        )) terminate;
	if(CheckWeapon("DukeFreezeThrower")) terminate;
	if(CheckWeapon("BlazkoAkimbo"     )) terminate;
	if(CheckWeapon("BlazkoAkimboBot"  )) terminate;
	if(CheckWeapon("SamMinigun"       )) terminate;
	if(CheckWeapon("PostalCowHead"    )) terminate;
	if(CheckWeapon("CalebDoll"        )) terminate;
	if(CheckWeapon("CalebDollBot"     )) terminate;
	// ^ insert more ability weapons here

	if(CheckInventory("Freezetagged")) terminate;

	// Randomly reselect weapon
	SetWeapon(BotPreferredWeapons[random(0,7)]);
}

int bot_pos_checksum[64], bepisx,bepisy,bepisz;
script "QCDE_Bot_Twitch" (void)
{
	if(CheckInventory("ImFrozen")) terminate; // Elsa doesn't twitch
	if(CheckInventory("Freezetagged")) terminate;
	if(CheckInventory("Twitchless3sec")) terminate; // As don't those thrown up by Grayson's Thumper
	if(GetActorProperty(0, APROP_HEALTH) <= 0) terminate; // As don't those that are dead like disco

	if(GetActorVelX(0) | GetActorVelY(0))
	{
		// Low chance to get a dash in random direction
		int power = random(-2 * GetCvar("bot_twitch") / 100, (GetCvar("botskill")) * GetCvar("bot_twitch") / 100);

		ThrustThing(random(0,256), power, false, 0);
		ThrustThingZ(0, power, 0, 1);
	}
	else
	{
		// If unmoving, turn around and jump especially far
		SetActorAngle(0, random(0, 1.0));
		ThrustThing(random(0,256), 13, false, 0);
		ThrustThingZ(0, 18, 0, 1);
	}

	// Extra BEPIS
	// https://cdn.discordapp.com/attachments/297799908084154378/435081076889616384/image.jpg

	int plr = PlayerNumber();
	int old_checksum = bot_pos_checksum[plr];
	int new_checksum = (GetActorX(0) >> 17) + (GetActorY(0) >> 17);
	if(old_checksum == new_checksum)
	{
		delay(140);
		new_checksum = (GetActorX(0) >> 17) + (GetActorY(0) >> 17);
		if(old_checksum == new_checksum)
		{
			SetActorPosition(0, bepisx,bepisy,bepisz, true);
			ThrustThing(random(0,256), 30, false, 0);
			ThrustThingZ(0, 40, 0, 1);
		}
	}
	bot_pos_checksum[plr] = new_checksum;
	if(!random(0,30+PlayerCount()) || !(bepisx|bepisy|bepisz))
	{
		bepisx = GetActorX(0);
		bepisy = GetActorY(0);
		bepisz = GetActorZ(0);
	}
}

#define HEALTH_FOR_DEFENSIVE 75
#define TRACKER_UPDATE_RATE 5
script "QCDE_AbilityTracker_BOT" (void)
{
	// Depending on situation and nature of active ability, activate it in
	// different situations.
	int health;

	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		if(CheckInventory("ActiveOffensive"))
		{
			// Offensive active is activated any second when bot's has target.
			if(!(timer()%7))
			if(ACS("QCDE_HasTarget",0))
			{
				ACS_NamedExecuteAlways("QCDE_ActiveAbility",0, 0, 1);
			}
		}
		if(CheckInventory("ActiveDefensive"))
		{
			// Defensive active is activated sometimes when bot's low on health.
			health = GetActorProperty(0,APROP_HEALTH);

			if(health < HEALTH_FOR_DEFENSIVE && !random(0,3))
			{
				ACS_NamedExecuteAlways("QCDE_ActiveAbility",0, 0, 1);
			}
		}

		delay(TRACKER_UPDATE_RATE);
	}
}

script "QCDE_Bot_FreezetagTimeout" (void)
{
	if(!GetCvar("qc_freezetag")) terminate;

	int myteam = PlayerTeam(), humans, humansfrozen;
	int i;
	for(i = 0; i < 64; i++) if(PlayerInGame(i)) if(!PlayerIsBot(i)) if(GetPlayerInfo(i, PLAYERINFO_TEAM) == myteam)
	{
		humans++;
		humansfrozen += CheckActorInventory(1000+i,"Freezetagged");
	}

	if(!random(0,PlayerCount())  &&  humans  &&  humans == humansfrozen) ACS("QCDE_Freezetag_Freeze", 1);
}

script "QCDE_HasTarget" (void)
{
	str nameWas = strparam(n:0);
	SetActivatorToTarget(0);
	str nameIs = strparam(n:0);
	setResultValue(stricmp(nameWas, nameIs));
}
