#library "BOTIMPRO"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"
#import "WEAPCNST.bcs"

//=============================================================================
//=============================================================================
//=============================================================================
//
//
//		BOT IMPROVEMENT RELATED SCRIPTS
//
//
//=============================================================================
//=============================================================================
//=============================================================================

str BotPreferredWeapons[8] = {
		"QCHeavyMachinegunDM",
		"QCSuperShotgunDM",
		"QCSuperNailgunDM",
		"QCTriboltDM",
		"QCRocketLauncherDM",
		"QCLightningGunDM",
		"QCRailgunDM",
		"QCBFGDM"
		};

int bot_pos_checksum[64], bepisx,bepisy,bepisz;
script "QCDE_Bot_Unstuck" (void)
{
	if(CheckInventory("ImFrozen")) terminate; // Elsa doesn't get stuck
	if(CheckInventory("Freezetagged")) terminate;
	if(CheckInventory("Twitchless3sec")) terminate; // As don't those thrown up by Grayson's Thumper
	if(GetActorProperty(0, APROP_HEALTH) <= 0) terminate; // As don't those that are dead like disco
	if(GetGameModeState() >= GAMESTATE_INRESULTSEQUENCE) terminate; // Everyone should be frozen when the match ends

	// Extra BEPIS
	// https://cdn.discordapp.com/attachments/297799908084154378/435081076889616384/image.jpg

	int plr = PlayerNumber();
	int old_checksum = bot_pos_checksum[plr];
	int new_checksum = (GetActorX(0) >> 17) + (GetActorY(0) >> 17);
	if(old_checksum == new_checksum)
	{
		delay(140);
		new_checksum = (GetActorX(0) >> 17) + (GetActorY(0) >> 17);
		if(old_checksum == new_checksum)
		{
			SetActorPosition(0, bepisx,bepisy,bepisz, true);
			ThrustThing(random(0,256), 30, false, 0);
			ThrustThingZ(0, 40, 0, 1);
		}
	}
	bot_pos_checksum[plr] = new_checksum;
	if(!random(0,30+PlayerCount()) || !(bepisx|bepisy|bepisz))
	{
		bepisx = GetActorX(0);
		bepisy = GetActorY(0);
		bepisz = GetActorZ(0);
	}
}

#define HEALTH_FOR_DEFENSIVE 75
#define TRACKER_UPDATE_RATE 5
script "QCDE_AbilityTracker_BOT" (void)
{
	if (GetGameModeState() < GAMESTATE_INPROGRESS)
		terminate;

	// Depending on situation and nature of active ability, activate it in
	// different situations.
	int health;

	while(GetActorProperty(0,APROP_HEALTH) > 0 && GetGameModeState() < GAMESTATE_INRESULTSEQUENCE)
	{
		if(CheckInventory("ActiveOffensive"))
		{
			// Offensive active is activated any second when bot's has target.
			if(!(timer()%7))
			if(ACS("QCDE_HasTarget",0))
			{
				ACS_NamedExecuteAlways("QCDE_ActiveAbility",0, 0, 1);
			}
		}
		if(CheckInventory("ActiveDefensive"))
		{
			// Defensive active is activated sometimes when bot's low on health.
			health = GetActorProperty(0,APROP_HEALTH);

			if(health < HEALTH_FOR_DEFENSIVE && !random(0,3))
			{
				ACS_NamedExecuteAlways("QCDE_ActiveAbility",0, 0, 1);
			}
		}

		delay(TRACKER_UPDATE_RATE);
	}
}

script "QCDE_Bot_FreezetagTimeout" (void)
{
	if(!GetCvar("qc_freezetag")) terminate;

	int myteam = PlayerTeam(), humans, humansfrozen;
	int i;
	for(i = 0; i < 64; i++) if(PlayerInGame(i)) if(!PlayerIsBot(i)) if(GetPlayerInfo(i, PLAYERINFO_TEAM) == myteam)
	{
		humans++;
		humansfrozen += CheckActorInventory(1000+i,"Freezetagged");
	}

	if(!random(0,PlayerCount())  &&  humans  &&  humans == humansfrozen) ACS("QCDE_Freezetag_Freeze", 1);
}

script "QCDE_HasTarget" (void)
{
	int activator = ActivatorTID();
	SetActivatorToTarget(0);
	int target = ActivatorTID();
	setResultValue(activator != target);
}
