#library "MESSAGES"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"
#import "WEAPCNST.bcs"

//=============================================================================
//=============================================================================
//=============================================================================
//
//
//		MESSAGE POPUP RELATED SCRIPTS
//
//
//=============================================================================
//=============================================================================
//=============================================================================


//=============================================================================
//
//		Simple notifications
//
//=============================================================================

script "QCDE_BindAbilityKey_Hint" (void) clientside
{
	delay(80);
	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	str k = strparam(k: "+user1");
	if(!stricmp(k, "??? (+user1)"))
	{
		HudMessage(s:"\c[white]Bind \c[brite]\"Use Active Ability\" \c[white]key.";
				HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK ,CR_WHITE,  256.0,260.0, 0.4,0.4,1.0);

		SetHUDSize(1400,1050,1);
		SetFont("ACTFRAM0");
		HudMessage(s:"A";
				HUDMSG_FADEINOUT,ID_CHANGEWEAPON_UNDER,-1,572.1,800.1, 0.8,0.2,2018.0210);
	}
}

function int GetKeyBinding(str key)
{
	str k = strparam(k:key);

	// detect absent binding
	int lparen = instr(k, '(');
	int rparen = instr(k, ')');
	int questi = instr(k, '?');
	if (questi == 0 && lparen > 0 && rparen > lparen)
	{
		k = "--";
	}

	// more laconic " or " => "/"
	int _or_ = instr4(k, ' ','o','r',' ');
	if (_or_ > 0)
	{
		int cutoff = _or_;
		if(cutoff > 4) cutoff = 4;
		k = strparam(s:strmid(k,0,cutoff), s:"/", s:strmid(k,_or_+4,4));
	}

	// convert ~~updog~~ uparrow into ^
	// PS: doesn't work >_< I'll do something about that later.
	int upar = instr4(k, 'u','p','a','r');
	if (upar > -1)  { k = strparam(s:strmid(k,0,upar), s:"^", s:strmid(k,upar+4,4)); }
	int down = instr4(k, 'd','o','w','n');
	if (down > -1)  { k = strparam(s:strmid(k,0,down), s:"v", s:strmid(k,down+4,4)); }
	int righ = instr4(k, 'r','i','g','h');
	if (righ > -1)  { k = strparam(s:strmid(k,0,righ), s:">", s:strmid(k,righ+4,4)); }
	int left = instr4(k, 'l','e','f','t');
	if (left > -1)  { k = strparam(s:strmid(k,0,left), s:"<", s:strmid(k,left+4,4)); }

	return strparam(s:"\c[brite]", s:k);
}

function int instr(str string, int char)
{
	int i;
	for(i = 0; i < strlen(string); i++)
	{
		if(getchar(string,i) == char)
			return i;
	}
	return -1;
}

function int instr4(str string, int a, int b, int c, int d)
{
	int i;
	for(i = 0; i < strlen(string)-3; i++)
	{
		if( getchar(string,i  ) == a &&
			getchar(string,i+1) == b &&
			getchar(string,i+2) == c &&
			getchar(string,i+3) == d    )
			return i;
	}
	return -1;
}

#define MINIMUM_HINT_DELAY (35*60)
int last_hint_time = -MINIMUM_HINT_DELAY;
script "QCDE_EldersSoul_Hint" (void) CLIENTSIDE
{
	//log(s:"CPN = ", d:CPN(), s:", PN = ", d:PlayerNumber(), s:" Actid = ", d:ActivatorTID());
	if(!areEnemies(CPN(), PlayerNumber())) terminate;

	//log(s:"Timer cond = ", d:last_hint_time + MINIMUM_HINT_DELAY, s:", Timer = ", d:Timer());
	if(last_hint_time + MINIMUM_HINT_DELAY > Timer()) terminate;

	last_hint_time = Timer();

	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	HudMessageBold(s:"\c[brite]The enemy has the Soul.";
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_1,-1,  256.4, 80.0, 1.4,0.1,5.0);

	SetHUDSize(1024,768,1);
	SetFont("QCBGFONT");
	HudMessageBold(s:"\c[white]Kill the carrier for 10 frags.";
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_2,-1,  512.4,195.0, 1.4,1.0,5.0);

	SetHUDSize(2048,768*2,1);
	SetFont("DEMNCARY");
	HudMessageBold(s:"a";
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_3,-1,  1024.0,486.0, 2.4,0.1,5.0);
}

script "QCDE_Freezetag_Hint" (void) CLIENTSIDE
{
	if(CPN() != PlayerNumber()) terminate;

	delay(35);

	if(GetActorProperty(PlayerNumber() + 1000, APROP_Health) <= 0) terminate;
	if(CPN() != CheckPlayerCamera(PlayerNumber()) - 1000) terminate;

	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	str hint = "";
	str k1 = strparam(k:"spynext");
	str k2 = strparam(k:"spyprev");
	if(stricmp(k1, "??? (spynext)"))
		if(stricmp(k2, "??? (spyprev)"))
			hint = strparam(s:"Use ", s:k2, s:" or ", s:k1, s:" to watch your teammates.");
		else
			hint = strparam(s:"Use ", s:k1, s:" to watch your teammates.");

	HudMessage(s:"\c[LG]You are frozen!\n", s:hint;
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK,-1,  256.4,280.0, 2.4,0.4,5.0);
}

script "QCDE_Freezetag_HintThaw" (void) CLIENTSIDE
{
	if(CPN() != PlayerNumber()) terminate;

	if(CPN() == CheckPlayerCamera(PlayerNumber()) - 1000) terminate;

	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");

	HudMessage(s:"\c[HMG]You were thawed!";
		HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK,-1,  256.4,280.0, 0.4,0.1,1.0);
	ConsoleCommand("spycancel");
}

script "QCDE_TeamLMS_HintLast" (void) CLIENTSIDE
{
	if(CPN() != PlayerNumber()) terminate;

	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	if(CheckInventory("Freezetagged")) terminate;

	int id = ID_CHANGEWEAPON_UNDER;
	if(Timer() % 2) id = ID_CHANGEWEAPON_BACK;

	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	HudMessage(s:"Last survivor!";
		HUDMSG_FADEINOUT,id,-1,  256.4,100.0, 0.4,0.4,0.4);
}

script "QCDE_EldersSoul_HintKill" (int self)
{
	if(!self) SetActivatorToTarget(0);
	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	str s = "You killed the Soul Bearer! \c[RG]+10 frags!";
	if(self) s = "You died with Soul! \c[bludi]-10 frags!";
	HudMessage(s:s; HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK ,CR_WHITE,  256.0,280.0, 1.4,0.1,2.0);
}

script "QCDE_EldersSoul_HintDegeneration" (void)
{
	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	str s = "Your life burns faster!";
	HudMessage(s:s; HUDMSG_FADEINOUT,ID_CHANGEWEAPON_BACK ,CR_WHITE,  256.0,280.0, 1.4,0.1,2.0);
}

Script "QCDE_Handicap_Notification" (int value, int valid) CLIENTSIDE
{
	if(ConsolePlayerNumber() != CheckPlayerCamera(PlayerNumber()) - 1000) terminate;
	
	str msg, desc;
	
	if(valid) {
		msg = "Using handicap!";
		desc = StrParam(s:"Current setting: ", d:value);
	} else {
		msg = "Invalid handicap setting!";
		desc = "Reverting to default";
	}

	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	HudMessageBold(s:msg; HUDMSG_FADEINOUT|HUDMSG_LOG,ID_COOPTANK_1,CR_ORANGE, 256.0,280.0, 1.6,0.3,2.0);
	SetFont("SMALLFONT");
	HudMessageBold(s:desc; HUDMSG_FADEINOUT|HUDMSG_LOG,ID_COOPTANK_2,CR_UNTRANSLATED, 256.0,296.0, 1.8,0.4,2.0);
}



//=============================================================================
//
//		Skirmish in Doom1
//		OR
//		PVP damage scalar warning
//
//	Use same ids because coop and pvp are mutually exclusive modes.
//
//=============================================================================

script "QCDE_SkirmishDoom1Warning" (void)
{
	if(CheckQcdeModule("Paina1"))                 terminate;
	if(!isSkirmish())                             terminate;
	if(!(GetCvar("theme3") || GetCvar("theme4"))) terminate;
	delay(3);

	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	HudMessage(s:"\c[bludi]Warning!";
				HUDMSG_FADEINOUT|HUDMSG_LOG,ID_COOPTANK_1,-1, 256.0,100.0, 5.6,0.1,3.0);
	SetFont("SMALLFONT");
	HudMessage(s:"\c[bludi]Some enemies might flicker due to Doom 2 resources not loaded.";
				HUDMSG_FADEINOUT|HUDMSG_LOG,ID_COOPTANK_2,-1, 256.0,120.0, 5.8,0.2,3.8);
	HudMessage(s:"\c[bludi]Possible solutions: ",
				s:"\n  -  Add ''Doom2.wad'' as a mapset to add resources",
				s:"\n  -  Change monster themes to not include Doom and Doom 4",
				s:"\n  -  Play with Doom or Doom 4 monsters without Skirmish Rogue";
				HUDMSG_FADEINOUT|HUDMSG_LOG,ID_COOPTANK_3,-1, 256.0,130.1, 5.8,0.3,3.8);
}

script "QCDE_DamageScalarWarning" (void)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate;
	if(GameType() == GAME_TITLE_MAP) terminate;

	str title, desc1, desc2, hint;

	// This number is NOT cvar `skill`!
	// Instead, it's skill definition's `ACSReturn` in MapInfo.
	int skill = GameSkill();

	switch(skill)
	{
		// Normal damage: no warning
		case 1:
		case 2:
		case 3:
			terminate;

		// High damage: kill mode warning
		case 4:
		case 5:
		case 6:
			title = "\c[brite]Kill Mode Active!";
			desc1 = "Caution:  all weapons deal more damage than usual!";
			desc2 = "";
			break;

		// Super damage: abandon hope
		case 7:
			title = "\c[bludi]Abandon All Hope!!!";
			desc1 = "Caution: \c[bludi] all weapons deal tremendous damage!";
			desc2 = "";
			break;

		// Low damage: ez mode warning
		case -2:
		case -1:
		case 0:
			title = "\c[brite]Ez Mode Active!";
			desc1 = "\c[white] Note:  all weapons deal halved damage.";
			desc2 = "";
			break;
	}
	hint = strparam(s:"Skill == ", d:GetCvar("skill"), s:" > 2. \nIt is recommended to use skills from 0 to 2 for optimal weapon balance.");

	// Message to server log
	log(s:title);
	log(s:hint);

	// Message to players -- waits a bit for everyone to connect
	delay(70);
	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	HudMessageBold(s:title; HUDMSG_FADEINOUT,ID_COOPTANK_1,CR_UNTRANSLATED, 256.0,100.0, 1.6,0.3,3.0);
	SetFont("SMALLFONT");
	HudMessageBold(s:desc1; HUDMSG_FADEINOUT,ID_COOPTANK_2,CR_UNTRANSLATED, 256.0,120.0, 1.8,0.4,3.8);
	HudMessageBold(s:desc2; HUDMSG_FADEINOUT,ID_COOPTANK_3,CR_UNTRANSLATED, 256.0,130.0, 1.8,0.4,3.8);
}


//=============================================================================
//
//		Lootbox
//
//=============================================================================

script "QCDE_MonstersKilled_Hint" (int secretsfound)
{
	str message = "..:: Enemies Killed ::..\n";
	if(secretsfound)
		message = "...::: Congratulations! :::...\n:::: Map completed ::::\n";

	SetHudSize(640, 480, 1);
	SetFont("QCBGFONT");
	HudMessageBold(s:message; HUDMSG_TYPEON,ID_LOOTBOX_TEXT,CR_GRAY, 320.0,393.6, 3.0,0.005,1.0);

	if(secretsfound)
		LocalAmbientSound("Map/MonstersKilled",100);
	else
		AmbientSound("Map/MonstersKilled",100);
}

script "QCDE_SecretsKilled_Hint" (void) // Yes, secrets are also killed. Absolutely Killed.
{
	str message = "..:: All Secrets Found ::..\n";

	SetHudSize(640, 480, 1);
	SetFont("QCBGFONT");
	HudMessageBold(s:message; HUDMSG_TYPEON,ID_LOOTBOX_TEXT,CR_GRAY, 320.0,393.6, 3.0,0.005,1.0);

	AmbientSound("Map/SecretsFound",100);
}

// This graphic name could be generated programmatically, true.
str lootboxVisuals[3] = {
	"LOOTBOX1",
	"LOOTBOX2",
	"LOOTBOX3",
};

str LOOTBOX_NAMES[3] = {"Backpack", "Chest", "Reliquary"};

str lootboxHintBacks[3] = {
	"ModBacc1", // Backpack
	"ModBacc2", // Chest
	"ModBacc3", // Reliquary
};

script "QCDE_Lootbox_Hint" (int level, int grade) clientside
{
	// Helpful hint about what to do with it
	str hint = "you have received a lootbox!";
	if(level == 1) hint = "100% kills, 100% secrets -- lootbox!";
	else if(level < 4 && !GetCvar("cl_autoOpenLootboxes"))
	{
		str k = strparam(k:"invuse");
		if(stricmp(k, "??? (invuse)"))
			hint = strparam(s:"press ", s:k, s:" to open");
		else
			hint = strparam(s:"enter \"invuse\" in console to open");
	}

	SetHUDSize(1024,768,1);
	SetFont(lootboxHintBacks[grade]);	HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_BACK,CR_WHITE,512.0,188.0,2.00,2.00);
	SetFont("ModFront"             );	HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_OVER,CR_WHITE,512.0,188.0,0.03,0.07);

	SetHUDSize(640,480,1);
	SetFont("SMALLFONT");	HudMessage(s:hint                ;HUDMSG_FADEOUT,ID_LOOTBOX_DESC,CR_WHITE,320.0, 87.0,2.5,3.0);
	SetFont("QCBGFONT");		HudMessage(s:LOOTBOX_NAMES[grade];HUDMSG_FADEOUT,ID_LOOTBOX_TEXT,CR_GREY ,320.0,106.0,3.0,3.0);

	SetHUDSize(1280,960,1);
	SetFont(lootboxVisuals[grade]);
	HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_IMAGE,CR_WHITE,640.0,274.0,2.0,4.0);

	LocalAmbientSound("Map/Completionist/Acquire",115);
}

str lootboxSounds[3] = {
	"Map/Completionist/Backpack",	// Backpack
	"Map/Completionist/Chest",		// Chest
	"Map/Completionist/Reliquary",	// Reliquary
};

script "QCDE_Lootbox_PreShow" (int level, int grade)
{
	LocalAmbientSound(lootboxSounds[grade],115);

	SetHUDSize(1024,768,1);
	SetFont("ModOpen");		HudMessage(s:"A";HUDMSG_FADEINOUT,ID_LOOTBOX_FADE,CR_WHITE,512.0,188.0,1.0,1.5,1.0);

	SetHUDSize(640,480,1);
	SetFont("SMALLFONT");	HudMessage(s:"opening"           ;HUDMSG_FADEOUT,ID_LOOTBOX_DESC,CR_WHITE,320.0, 87.0,0.1,2.0);
	SetFont("QCBGFONT");		HudMessage(s:LOOTBOX_NAMES[grade];HUDMSG_FADEOUT,ID_LOOTBOX_TEXT,CR_GREY ,320.0,106.0,1.0,3.0);

	int ratio;
	int base = 320; int now = 320.0; int step = 8.0;
	SetFont(lootboxVisuals[grade]);

	while(CheckInventory("OpeningLootbox"))
	{
		now += step;
		ratio = now / base;
		SetHUDSize(now / 1.0, now / 1.3333, 1);

		HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_IMAGE,CR_WHITE,
					160*ratio >>16<< 16, 68*ratio >>16<< 16, 5.0, 3.0);
		delay(1);
	}
}

str lootboxBacks[3] = {
	"ModBack1", // Backpack
	"ModBack2", // Chest
	"ModBack3", // Reliquary
};

str rewardBacks[3] = {
	"RewBack1", // Backpack
	"RewBack2", // Chest
	"RewBack3", // Reliquary
};

script "QCDE_Lootbox_Show" (int level, int grade, int title, int icon)
{
	str hint = "congratulations!";
	if(isSkirmish() || (IsZandronum(true) && GetInvasionState() > 0)) hint = "good luck!";

	SetHUDSize(1024,768,1);
	SetFont(lootboxBacks[grade]);	HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_BACK,CR_WHITE, 512.0,188.0, 2.00,3.00 + grade * 0.40);
	SetFont("ModFront");			HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_OVER,CR_WHITE, 512.0,188.0, 0.02,0.07 + grade * 0.02);
	SetFont("ModFront");			HudMessage(s:"A";HUDMSG_FADEOUT,ID_LOOTBOX_FADE,CR_WHITE, 512.0,188.0, 0.02,0.07 + grade * 0.02);

	SetHUDSize(640,480,1);
	SetFont("SMALLFONT");	HudMessage(s:hint;HUDMSG_FADEOUT,ID_LOOTBOX_DESC,CR_WHITE, 320.0, 87.0, 2.5,3.0 + grade * 0.1);
	SetFont("QCBGFONT");		HudMessage(s:title;HUDMSG_FADEOUT,ID_LOOTBOX_TEXT,CR_GREY, 320.0,106.0, 3.0,2.5 + grade * 0.4);

	SetFont("BLINKGLD");
	SetHudSize(640,480,1);
	HudMessage(s:"A"; HUDMSG_FADEOUT, ID_LOOTBOX_IMAGE, CR_UNTRANSLATED,
				320.0, 136.0, 0.08, 0.20);
	LocalAmbientSound("Map/Completionist/Reveal",127);

	// Don't show frame and picture if picture is blank
	if(!stricmp("        ",icon)) terminate;

	delay(1);
	SetFont(rewardBacks[grade]);
	SetHudSize(1024,768,1);
	HudMessage(s:"A"; HUDMSG_FADEOUT, ID_LOOTBOX_UNDER, CR_UNTRANSLATED,
				512.0, 255.0, 3.0, 2.20);

	SetFont(icon);
	SetHudSize(1024,768,1);
	HudMessage(s:"A"; HUDMSG_FADEOUT, ID_LOOTBOX_IMAGE, CR_UNTRANSLATED,
				512.0, 255.0, 3.0, 2.20);
}


//=============================================================================
//
//		Loadout weapon listing (both for cheat or lootbox)
//
//=============================================================================

// These have had offsets removed.
script "QCDE_ShowWeapon" (int weapon, int position, int totalNumber)
{
	int fadeIn  = 0.1 * position;
	int stayOn  = 2.0 + totalNumber * 0.2 - fadeIn;
	int fadeOut = 0.5;

	int x = 200.0, side;
	int y = 120.2, row;
	if(totalNumber > 1)
	{
		side = (((position - 1) % 2) * 2 - 1);
		row = (position - 1) / 2;
		if(totalNumber == position && totalNumber % 2) side = 0;
		x += side * 51.0;
		y += row * 55.0;
	}

	// Picture
	SetHudSize(400,300,true);
	SetFont(getLootboxWeaponVisuals(weapon));
	HudMessage(s:"A"; HUDMSG_FADEINOUT, ID_WEAPON_FACE_BASE + position, CR_UNTRANSLATED, x, y, stayOn, fadeIn, fadeOut);

	// Label
	SetHudSize(800,600,true);
	x *= 2;
	y = (y >>16<< 16) * 2 + 8.1;
	SetFont("QCBGFONT");
	HudMessage(s:getLootboxWeaponNamings(weapon); HUDMSG_TYPEON, ID_WEAPON_TEXT_BASE + position, CR_WHITE, x, y, stayOn, 0.04, fadeOut);

	// Back
	SetHudSize(1600,1200,true);
	x *= 2;
	y = ((y >>16<< 16) - 8.0) * 2 - 80.0;
	SetFont("WPNBACK0");
	HudMessage(s:"A"; HUDMSG_FADEINOUT, ID_WEAPON_BACK_BASE + position, CR_UNTRANSLATED, x, y, stayOn, fadeIn, fadeOut);
}




//=============================================================================
//
//		Low ammo/health alert
//
//=============================================================================

script "QCDE_LowAmmoAlert_CLIENT" (int sound, int text, int noammo) CLIENTSIDE
{
	int cameraPlayer = CheckPlayerCamera(ConsolePlayerNumber());
	if (cameraPlayer >= ORBBDRON_TIDBASE)
		cameraPlayer -= ORBBDRON_TIDBASE;
	else
		cameraPlayer -= 1000;
	if (cameraPlayer != PlayerNumber()) terminate;

	if (CheckActorInventory(cameraPlayer + 1000, "NoLowEffects")) terminate;

	if(sound) AmbientSound("QC/UI/PlayerSounds/LowAmmoWarning", 127);

	if(!text || GetCvar("screenblocks") >= 12) terminate;

	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	str message = "\c[bludi]LOW AMMO";
	if(noammo) message = "\c[red]NO AMMO";

	HudMessage(s:message;
			HUDMSG_FADEOUT,ID_LOWAMMO_TEXT,CR_UNTRANSLATED, 256.0,70.0, 0,1.0);
}

script "QCDE_LowHealthAlert_CLIENT" (int sound, int text) CLIENTSIDE
{
	int cameraPlayer = CheckPlayerCamera(ConsolePlayerNumber());
	if (cameraPlayer >= ORBBDRON_TIDBASE)
		cameraPlayer -= ORBBDRON_TIDBASE;
	else
		cameraPlayer -= 1000;
	if (cameraPlayer != PlayerNumber()) terminate;

	if (CheckActorInventory(cameraPlayer + 1000, "NoLowEffects")) terminate;

	if(sound) AmbientSound("QC/UI/PlayerSounds/LowHealthWarning", 127);

	if(!text || GetCvar("screenblocks") >= 12) terminate;

	SetHUDSize(512,384,1);
	SetFont("QCBGFONT");
	str message = "\c[bludi]LOW HEALTH";

	HudMessage(s:message;
			HUDMSG_FADEOUT,ID_LOWHEALTH_TEXT,CR_UNTRANSLATED, 256.0,90.0, 0,0.5);
}





//=============================================================================
//
//		Grayson's shop visuals
//
//=============================================================================

script "QCDE_GraysonText" (int amount, int mode, int ammoicon)
{
	str message = strparam(s:"+", d:amount);

	SetHUDSize(1400,1050,1);
	SetFont("QCFNT100");
	HudMessage(s:message;
			HUDMSG_FADEOUT,ID_GRAYSON_PROMPT ,CR_UNTRANSLATED, 1140.2, 850.0, 1.0,1.0);

	if(ammoicon)
	{
		SetHUDSize(2800,2100,1);
		SetFont(getGraysonAmmoIcons(ammoicon));
		HudMessage(s:"A";
				HUDMSG_FADEOUT,ID_GRAYSON_ICON,CR_UNTRANSLATED, 2370.1, 1706.0, 1.0,1.0);
	}

	// armor cost
	SetHUDSize(1400,1050,1);
	SetFont("QCFNT100");
	HudMessage(s:"-25"; // hardcoded. we'll never ever change armor cost. yeah right. hahahaha
			HUDMSG_FADEOUT,ID_GRAYSON_PROMPT2,CR_UNTRANSLATED, 1140.2, 770.0, 1.0,1.0);
	SetFont("ICONSHLD");
	HudMessage(s:"A";
			HUDMSG_FADEOUT,ID_GRAYSON_ICON2,CR_UNTRANSLATED, 1183.1, 765.0, 1.0,1.0);

	// ingenious hack: use "minus" sign as rectangular background
	SetHUDSize(150,113,1);
	SetFont("QCFNT100");
	switch(mode)
	{
		case 0:
			PlaySound (0, "QC/Abilities/Grayson/PreBuy", 7, 1.0, false, 4.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH ,CR_ORANGE,138.2,93.0, 0,1.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH2,CR_ORANGE,138.2,84.0, 0,1.0);
			break;
		case 1:
			PlaySound (0, "QC/Abilities/Grayson/Buy", 7, 1.0, false, 4.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH ,CR_GREEN ,138.2,93.0, 0,1.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH2,CR_GREEN ,138.2,84.0, 0,1.0);
			break;
		case -1:
			PlaySound (0, "QC/Abilities/Grayson/CantBuy", 7, 1.0, false, 4.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH ,CR_ORANGE,138.2,93.0, 0,1.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH2,CR_RED   ,138.2,84.0, 0,1.0);
			break;
		case -2:
			PlaySound (0, "QC/Abilities/Grayson/CantBuy", 7, 1.0, false, 4.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH ,CR_RED   ,138.2,93.0, 0,1.0);
			HudMessage(s:"-"; HUDMSG_FADEOUT,ID_GRAYSON_FLASH2,CR_GREEN ,138.2,84.0, 0,1.0);
			break;
	}
}


//=============================================================================
//
//		Eradicator murderface visuals
//		(unused)
//
//=============================================================================



script "QCDE_EradicatorHint" (int percentage, int kills_more)
{

	SetHUDSize(1400,1050,1);
	SetFont("QCBGFONT");

	if(percentage > 0)
	{
		HudMessage(s:"\c[bludi]+", d:percentage, s:"% \c[brite]base damage";
				HUDMSG_FADEOUT,ID_ERADICATOR_PERC,CR_UNTRANSLATED, 1140.2, 968.0, 100.0,200.0);
	}

	HudMessage(s:"\c[white]", d:kills_more, s:" kills to buff";
			HUDMSG_FADEOUT,ID_ERADICATOR_MORE,CR_UNTRANSLATED, 1140.2, 988.0, 100.0,200.0);
}





//=============================================================================
//
//		Freeze speedometer
// reuses Starting Weapon ID
//
//=============================================================================



script "QCDE_FreezeIndicator_CLIENT" (int percentage) CLIENTSIDE
{
	if(percentage <= 0) terminate;
	if(percentage > 90) percentage = 90;

	int fadein = 0.2 - (percentage * 0.011);
	int stay = -0.2 + (percentage * 0.011);
	int fadeout = percentage * 0.022;

	if(fadein < 0) fadein = 0;
	if(stay < 0) stay = 0;

	SetHUDSize(1400 - percentage * 2,1050 - percentage * 2,1);
	SetFont("FLAKES01");

	HudMessage(s:"A";
			HUDMSG_FADEINOUT,ID_CHANGEWEAPON_OVER + percentage / 10,CR_UNTRANSLATED, 700.0 - percentage * 1.0, 616.0 - percentage * 2.0, stay,fadein,fadeout);
}


//=============================================================================
//
// Titlemap export
//
//=============================================================================

Script "QCDE_ShowVersionNumber" (void)
{
	SetHudSize(960,720,0);
	SetFont("SMALLFNT");
	HudMessageBold(s:"v3.1";HUDMSG_PLAIN,ID_TITLEMAP_VERSION,CR_WHITE, 955.0, 710.0, 0);
}



//=============================================================================
//
// Monster packs load indication
//
//=============================================================================

int currentPack = THEMES_BUILTIN;
Script "QCDE_ShowMonsterPack" (int packname)
{
	int packWas = currentPack++;

	SetHudSize(800,600,0);
	SetFont("SMALLFNT");
	HudMessageBold(s:"\c[brite]Registered custom monsters sets:";HUDMSG_FADEOUT,ID_TITLEMAP_THEMES,          -1, 0.1, 480.0,        0, 20.0);

	delay(packWas * 3);
	AmbientSound("menu/dismiss", 127);

	int yofs = (packWas - THEMES_BUILTIN) * 10.0;
	if(yofs > 80.0) yofs -= 550.0;
	HudMessageBold(s:"\c[brite]theme", d:packWas, s:": \ck",s:packname;HUDMSG_TYPEON,ID_TITLEMAP_THEMES + packWas,-1, 0.1, 500.0 + yofs, 0, 0.06, 20.0);
}



//=============================================================================
//
//		Weapon Upgrade
//
//=============================================================================

Script "QCDE_UpgradeAcquired" (int weapon, int upgrade)
{
	if(upgrade < 1 || upgrade > 3 || weapon < 0 || weapon >= NUMBER_OF_WEAPONS)
	{
		log(s:"QCDE Error: acquired undefined weapon ", d:weapon, s:" upgrade ", d:upgrade);
		terminate;
	}

	// Upgrade indices are 1-based, but array indices are 0-based
	upgrade--;

	SetHUDSize(1024,768,1);
	SetFont("UpgrdGot");            HudMessage(s:"A";HUDMSG_FADEINOUT,ID_UPGRADE_BACK,-1, 512.0,472.1, 4.0,0.1,3.0);

	// Name
	SetHUDSize(400,300,1);
	SetFont("ESFONTAA");
	str color = strparam(s:"\c[", s:weaponList[weapon], s:"]");
	HudMessage(s:color, s:weaponUpgrades[weapon][upgrade][WU_PROPERNAME], s:" \c[white]", s:weaponUpgrades[weapon][upgrade][WU_SUFFIX];
						HUDMSG_FADEINOUT,ID_UPGRADE_TEXT   ,-1, 135.1,200.1, 5.0,0.1,3.0);
	// Description
	SetHUDSize(400,300,1);
	SetFont("ESFONTAA");
	color = "\c[brite]";
	HudMessage(s:color, s:weaponUpgrades[weapon][upgrade][WU_DESC1], s:"\n", s:color, s:weaponUpgrades[weapon][upgrade][WU_DESC2], s:"\n", s:color, s:weaponUpgrades[weapon][upgrade][WU_DESC3];
						HUDMSG_FADEINOUT,ID_UPGRADE_DESC   ,-1, 135.1,215.1, 5.0,0.1,3.0);

	// Weapon outline
	SetHUDSize(800,600,1);
	if(CheckInventory(weaponList[weapon]))
		 SetFont(weaponUpgrades[weapon][upgrade][WU_WEAPONFULL]);
	else SetFont(weaponUpgrades[weapon][upgrade][WU_WEAPONICON]);
	HudMessage(s:"A"; 	HUDMSG_FADEINOUT,ID_UPGRADE_OUTLINE,-1, 100.0,429.0, 5.0,0.1,2.0);
	// Icon
	SetHUDSize(1600,1200,1);
	SetFont(weaponUpgrades[weapon][upgrade][WU_ICON]);
	HudMessage(s:"A"; 	HUDMSG_FADEINOUT,ID_UPGRADE_ICON   ,-1, 400.0,858.0, 5.0,0.1,2.0);

	LogTo(PlayerNumber(), strparam(s:"\c[red]Picked up an upgrade: \c[brite]", s:weaponUpgrades[weapon][upgrade][WU_PROPERNAME], s:" ", s:weaponUpgrades[weapon][upgrade][WU_SUFFIX], s:"\n",
		s:weaponUpgrades[weapon][upgrade][WU_DESC1], s:"\n",
		s:weaponUpgrades[weapon][upgrade][WU_DESC2], s:"\n",
		s:weaponUpgrades[weapon][upgrade][WU_DESC3]));
}



//=============================================================================
//
// Indicate Major ability charges
//
//=============================================================================

#define MAJOR_BOMB_X_GAP 60.0
#define MAJOR_BOMB_Y_GAP 70.0
#define MAJOR_BOMBS_IN_ROW  4
#define MAJOR_START_X     800.0 - (MAJOR_BOMB_X_GAP * 3 / 2)
#define MAJOR_START_Y     800.0
Script "QCDE_MajorCharges" (int charges, int consume)
{
	if(charges <  0) terminate;
	if(charges >  8) charges = 8;
	if(charges == 8) consume = false;

	SetHudSize(1600,1200,0);
	SetFont("ONE_BOMB");

	int hmid = HMID_CHARGES;
	int row, col;
	while(charges --> 0)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		HudMessage(s:"A";HUDMSG_PLAIN,hmid,-1, MAJOR_START_X + MAJOR_BOMB_X_GAP * col, MAJOR_START_Y + MAJOR_BOMB_Y_GAP * row, 4.0);
		SetNetworkReplicationFlags( 0 );

		col++;
		if(col >= MAJOR_BOMBS_IN_ROW) { col = 0; row++; }

		hmid++;
	}

	SetFont("GONEBOMB");
	if(consume)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		HudMessage(s:"A";HUDMSG_FADEOUT,hmid,-1, MAJOR_START_X + MAJOR_BOMB_X_GAP * col, MAJOR_START_Y + MAJOR_BOMB_Y_GAP * row, 0, 0.2);
		SetNetworkReplicationFlags( 0 );
	}

}




//=============================================================================
//
// Indicate Zedek fire level
//
//=============================================================================

#define ZEDEK_FIRE_X_GAP 48.0
#define ZEDEK_FIRE_MAX   6
#define ZEDEK_START_X  850.1
#define ZEDEK_START_Y 1100.0
Script "QCDE_ZedekFireLevel" (int level, int victimtid) clientside
{
	if(level < 0) terminate;
	if(level > ZEDEK_FIRE_MAX) level = ZEDEK_FIRE_MAX;
	if(victimtid != CheckPlayerCamera(CPN())) terminate;
	level *= 2;

	SetHudSize(1800,1400,0);

	int hmid = HMID_COW_GAS;
	int flags = HUDMSG_FADEOUT|HUDMSG_ADDBLEND|HUDMSG_ALPHA;
	SetActivator(victimtid);
	while(level --> 0)
	{
		str sprite = "ZEDKFIRE";
		SetFont(sprite);
		HudMessageBold(s:"A";flags,hmid,-1, ZEDEK_START_X + ((ZEDEK_FIRE_X_GAP * (level / 2 * 2 + 1)) * ((level % 2 * 2) - 1)), ZEDEK_START_Y, 1.1, 0.5);

		hmid++;
	}
}




//=============================================================================
//
// Indicate Postal cow gas level
//
//=============================================================================

#define POSTAL_GAS_X_GAP 30.0
#define POSTAL_GAS_MAX   13
#define POSTAL_START_X  850.1
#define POSTAL_START_Y 1100.0
Script "QCDE_CowGasLevel" (int level, int victimtid) clientside
{
	if(level < 0) terminate;
	if(level > POSTAL_GAS_MAX) level = POSTAL_GAS_MAX;
	if(victimtid != CheckPlayerCamera(CPN())) terminate;
	level *= 2;

	SetHudSize(1800,1400,0);

	int hmid = HMID_COW_GAS;
	int flags = HUDMSG_FADEOUT|HUDMSG_ADDBLEND|HUDMSG_ALPHA;
	SetActivator(victimtid);
	while(level --> 0)
	{
		str sprite = "POSTPOIS";
		SetFont(sprite);
		HudMessageBold(s:"A";flags,hmid,-1, POSTAL_START_X + ((POSTAL_GAS_X_GAP * (level / 2 * 2 + 1)) * ((level % 2 * 2) - 1)), POSTAL_START_Y, 1.1, 0.5);

		hmid++;
	}
}



//=============================================================================
//
//		Vormatur's Horror mask
//
//=============================================================================

Script "QCDE_Darkening_Start" (int duration, int fadein, int fadeout) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	AmbientSound("QC/Abilities/VorMatur/Darkened",1.0);
	SetFont("DARKNESS");
	int id = random(0,63);
	SetHudSize(640,480,true);
	HudMessageBold(s:"A"; HUDMSG_FADEINOUT, HMID_VORMATUR_DARKNESS+id, -1,
			320.0,240.0, duration, fadein, fadeout);
}

Script "QCDE_Darkening_Stop" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	int id;
	for(id=0; id<64; id++)
		HudMessageBold(s:" "; HUDMSG_PLAIN, HMID_VORMATUR_DARKNESS+id, -1,
			-400.0,-300.0, 0.0);
}


//=============================================================================
//
//		Painkiller's Black Tarot views
//
//=============================================================================

#define ARROW_XOFFS 125.0
#define TAROT_XOFFS 200.0
#define TAROT_TEXT_YOFFS 35.0

#define ARROW_Y 857.0
#define TAROT_Y 765.0

#define TAROT_PICKS_XOFFS 100.0
#define TAROT_PICKS_Y    1020.0

script "QCDE_Tarot_Hint" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	// Prepare messages (they can be quite wordy)
	str moveleft  = GetKeyBinding("+MoveLeft" );
	str forward   = GetKeyBinding("+Forward"  );
	str moveright = GetKeyBinding("+MoveRight");

	SetHUDSize(1440,1080,1);
	SetFont("CARDARRL"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_ARROW_L, -1, 1440.0/2-ARROW_XOFFS,943.0,   0,0.5,0.5);
	SetFont("CARDARRU"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_ARROW_U, -1, 1440.0/2            ,ARROW_Y, 0,0.5,0.5);
	SetFont("CARDARRR"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_ARROW_R, -1, 1440.0/2+ARROW_XOFFS,943.0,   0,0.5,0.5);

	SetFont("CARDDEFE"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_CARD_L , -1, 1440.0/2-TAROT_XOFFS,943.0,   1.1,0,0.1);
	SetFont("CARDATTA"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_CARD_U , -1, 1440.0/2            ,TAROT_Y, 1.1,0,0.1);
	SetFont("CARDSPEE"); HudMessageBold(s:"A"; HUDMSG_FADEINOUT,HMID_TAROT_CARD_R , -1, 1440.0/2+TAROT_XOFFS,943.0,   1.1,0,0.1);

	SetFont("QCBGFONT");
	HudMessageBold(s:moveleft;	HUDMSG_FADEOUT,HMID_TAROT_TEXT_L,-1, 1440.0/2-TAROT_XOFFS,TAROT_TEXT_YOFFS+943.0,   1.1,0,0.1);
	HudMessageBold(s:forward;	HUDMSG_FADEOUT,HMID_TAROT_TEXT_U,-1, 1440.0/2            ,TAROT_TEXT_YOFFS+TAROT_Y, 1.1,0,0.1);
	HudMessageBold(s:moveright;	HUDMSG_FADEOUT,HMID_TAROT_TEXT_R,-1, 1440.0/2+TAROT_XOFFS,TAROT_TEXT_YOFFS+943.0,   1.1,0,0.1);
}

script "QCDE_Tarot_Hint_Failure" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	AmbientSound("QC/Abilities/Painkiller/Failure", 127);
}

str tarot_success_sound[4] = { 0,
	"QC/Abilities/Painkiller/Defense",
	"QC/Abilities/Painkiller/Attack",
	"QC/Abilities/Painkiller/Speed",
};

str tarot_card_gfx[4] = { "CARDBLNK",
	"CARHDEFE",
	"CARHATTA",
	"CARHSPEE",
};

script "QCDE_Tarot_Hint_Success" (int which, int level, int pickorder) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	if(which < 1 || which > 3 || level < 1 || level > 3) printbold(n:0, s:" selects bad card ", d:which, s:" level ", d:level);

	AmbientSound(tarot_success_sound[which], 67 + 20 * level);

	SetHUDSize(1440,1080,1);
	int i;
	for(i =~- pickorder; i < 3; i++)
	{
		SetFont(tarot_card_gfx[which * (i < pickorder)]);
		HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_PICK_1 + i, -1, 1440.0/2 + ((i - 1) * TAROT_PICKS_XOFFS),TAROT_PICKS_Y, 10.0, 5.0);
	}

	int x,y;
	switch(which)
	{
		case 1: x = 1440.0/2-TAROT_XOFFS; y = 943.0; break;
		case 2: x = 1440.0/2          ; y = TAROT_Y; break;
		case 3: x = 1440.0/2+TAROT_XOFFS; y = 943.0; break;
	}
	for(i = 1; i <= 8; i++)
	{
		SetFont(strparam(s:"CARDGLW", d:i));
		HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_CARDGLW +~- pickorder, -1, x,y, 2.0/35, 0.1);
		delay(1);
	}

}

script "QCDE_Tarot_Hint_Apply" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	// nothing yet
}

script "QCDE_Tarot_Hint_End" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	SetHUDSize(1440,1080,1);
	SetFont(tarot_card_gfx[0]);
	HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_PICK_1, -1, 1440.0/2 + (-1 * TAROT_PICKS_XOFFS),TAROT_PICKS_Y, 0.1, 0.2);
	HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_PICK_2, -1, 1440.0/2 + ( 0 * TAROT_PICKS_XOFFS),TAROT_PICKS_Y, 0.1, 0.2);
	HudMessageBold(s:"A"; HUDMSG_FADEOUT,HMID_TAROT_PICK_3, -1, 1440.0/2 + ( 1 * TAROT_PICKS_XOFFS),TAROT_PICKS_Y, 0.1, 0.2);
}






//=============================================================================
//
//		Intruder's Morale Boost
//
//=============================================================================

Script "QCDE_IntruderMoraleBoost" (void) clientside
{
	if(IsZandronum(true)  &&  PlayerNumber() != CheckPlayerCamera(CPN()) - 1000) terminate;

	//AmbientSound("QC/Abilities/VorMatur/Darkened",1.0);
	SetHudSize(1024, 768, 1);
	SetFont("QCBGFONT");
	HudMessageBold(s:"\c[RG]Morale Boost!"; HUDMSG_FADEOUT,0,-1, 222.0,737.0, 1.0,2.0);
}


//=============================================================================
//
//		Map Introduction
//
//=============================================================================

Script "QCDE_ShowMapIntroduction" (int mapName, int mapTitle, int mapAuthor, int mapSource)
{
	if(GetCvar("screenblocks") >= 12) terminate;

	SetHudSize(640, 480, 1);
	SetFont("QCBGFONT");
	HudMessage(s:mapName, s:" \c[brite]", s:mapTitle,
		s:"\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"; // this helps placing the text box properly
		HUDMSG_FADEINOUT, 0, CR_RED, 245.0, 272.0, 2.5, 0.7, 1.0);

	str originalString = "\n \c[yellow]Original: \c[brite]";

	if (!strcmp(mapSource, ""))
		originalString = "";

	SetHudSize(640, 480, 1);
	SetFont("QCSMFONT");
	HudMessage(s:" \c[yellow]Mapped by: \c[brite]", s:mapAuthor, s:originalString, s:mapSource,
		s:"\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
		s:"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"; // this helps placing the text box properly
		HUDMSG_FADEINOUT, 0, CR_RED, 272.0, 296.0, 2.3, 0.9, 1.0);
}
