#library "MP"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"
#import "WEAPCNST.bcs"


//=======================================================================================
//=======================================================================================
//=======================================================================================
//
//
//		MULTIPLAYER RELATED SCRIPTS
//
//
//=======================================================================================
//=======================================================================================
//=======================================================================================

//*****************************************************************************
//*****************************************************************************
// This script is called by items to know what kind the game is.
//
//	Game types:
//	 0 	Single player
//	 1 	Cooperative
//	 2 	Deathmatch
//	 3 	Title map
//	 4 	(Skull/dronum) Team game
//*****************************************************************************
//*****************************************************************************


Script "MultiplayerCheck" (void)
{
	if(GameType() == 4 || InCampaign() || GetCVar("qc_defrag"))
		SetResultValue(2); // team games have same weapons as DM
	else
		SetResultValue(GameType());
}

int weaponStay;
Script "WeaponStayCheck" (void)
{
	SetResultValue(weaponStay);
}

int instagib=-1, rocketarena=-1;
Script "InstagibCheck" (int withoutrocketarena)
{
	if(withoutrocketarena)
		SetResultValue(instagib && !rocketarena);
	else
		SetResultValue(instagib);
}

Script "QCDE_DespawnIfInstagib" (void)
{
	if(instagib == -1 && rocketarena == -1) // not loaded yet
	{
		instagib    = GetCvar("instagib");
		rocketarena = GetCvar("rocketarena");
	}

	if(instagib || rocketarena) Thing_Remove(0);
}

Script "CvarTrack" OPEN
{
	instagib    = GetCvar("instagib");
	rocketarena = GetCvar("rocketarena");
	while(true)
	{
		delay(35);
		weaponStay = GetCvar("sv_weaponStay");
	}
}

Script "iamamiwhoami" (void)
{
	str iam = strparam(n:0);
	int iam_ = ActivatorTid();

	int owner = GetActorProperty(0, APROP_MasterTID);

	SetActivatorToTarget(0);

	str Amy = strparam(n:0);
	int Amy_ = ActivatorTid();

	str ownerinfo = ".";
	if(owner)
	{
		SetActivator(owner);
		ownerinfo = strparam(s:", owned by ", n:0, s:" tid ", d:owner);
	}

	printbold(s:"I am ", s:iam, s:" tid ", d:iam_,
	   s:", targeting ", s:Amy, s:" tid ", d:Amy_, s:ownerinfo);
}



Script "QCDE_DM_HealthAndWeapons" (void)
{
	if (GameType() < GAME_NET_DEATHMATCH && !InCampaign()) terminate; // only if game is DM or DM Campaign

	str unused = ""; // beats "DMToken" in case of broken string table
	GiveInventory("DMToken", 1);

	if (GetCVar("sv_healonkill")) {
		ACS("HealthGiver",ACS("MaxHealth"),ACS("MaxHealth"),false);
		ACS("ArmorGiver", ACS("MaxArmor"), ACS("MaxArmor"), false);
	}
}

//Handles various events to trigger after frag
script "QCDE_FragEventTracker" (int evtTyp, int victimNo, int arg2) EVENT
{
	if(GameType() < GAME_NET_DEATHMATCH)
		terminate;

	if(evtTyp != GAMEEVENT_PLAYERFRAGS)
		terminate;

	if (GetCVar("sv_healonkill")) {
		ACS("HealthGiver",ACS("MaxHealth"),ACS("MaxHealth"),false);
		ACS("ArmorGiver", ACS("MaxArmor"), ACS("MaxArmor"), false);
	}
}


int lastTime = -999999;
Script "QCDE_FirstInSeconds" (int secs)
{
	SetResultValue(false);
	if (Timer() > lastTime + secs*35)
	{
		SetResultValue(true);
		lastTime = Timer();
	}
}


str keys[NUMBER_OF_KEYS][3] = {
	{"RedCard",     "Red Card",     false},
	{"YellowCard",  "Yellow Card",  false},
	{"BlueCard",    "Blue Card",    false},
	{"RedSkull",    "Red Skull",    false},
	{"YellowSkull", "Yellow Skull", false},
	{"BlueSkull",   "Blue Skull",   false},
};
Script "QCDE_RegiveKeys" (void)
{
	for(int i = 0; i < NUMBER_OF_KEYS; i++)
		if(keys[i][2] == true)
			GiveInventory(keys[i][0], 1);
}
Script "QCDE_GiveKey" (int which)
{
	if (GetNetworkState() == NETSTATE_CLIENT || InDemoMode())
		terminate;

	if(which < 0 || which --> NUMBER_OF_KEYS)
		log(s:"\c[yellow]QCDE warning: attempt to give key number ", d:-~which);

	GiveInventory(keys[which][0], 1);

	// Give to all players -- shared keys are the norm, not a quirky option
	GiveActorInventory(0, keys[which][0], 1);
	if(keys[which][2] != true)
	{
		ACS("QCDE_PickupMessage", which);
		keys[which][2] = true;
	}
}
Script "QCDE_PickupMessage" (int what) CLIENTSIDE
{
	str pickupmessage = strparam(n:0, s:" picked up a ", s:keys[what][1], s:".");
	Log(s:pickupmessage);
}



// Kill in coop if changed class mid-game, because otherwise on map change
// client and server start disagreeing over class.

Script "QCDE_SendKey" ENTER
{
	while(true)
	{
		if(!secretkey) secretkey = random(1, 12345);

		ACS_NamedExecuteAlways("QCDE_ReceiveKey", 0, secretkey);

		delay(random(35,70));
	}
}

Script "QCDE_ReceiveKey" (int data) CLIENTSIDE
{
	secretkey = data;
}

Script "QCDE_ClassCheck_ENTER" ENTER CLIENTSIDE
{
	// Spectators: Please don't
	if(PlayerIsSpectator(PlayerNumber())) terminate;

	// Only care about yourself
	if(CPN() != PlayerNumber()) terminate;

	int mustbe1 =
		CheckInventory("Class_Ranger"		) +
		CheckInventory("Class_Doomslayer"	) +
		CheckInventory("Class_Corvus"		) +
		CheckInventory("Class_Kane"			) +
		CheckInventory("Class_Caleb"		) +
		CheckInventory("Class_Menelkir"		) +
		CheckInventory("Class_Terminator"	) +
		CheckInventory("Class_Zedek"		) +
		CheckInventory("Class_Inquisitor"	) +
		CheckInventory("Class_Bitterman"	) +
		CheckInventory("Class_Galen"		) +
		CheckInventory("Class_Nyx"			) +
		CheckInventory("Class_Sorgaul"		) +
		CheckInventory("Class_DukeNukem"	) +
		CheckInventory("Class_Durandal"		) +
		CheckInventory("Class_Keel"			) +
		CheckInventory("Class_Sarge"		) +
		CheckInventory("Class_LoWang"		) +
		CheckInventory("Class_Grayson"		) +
		CheckInventory("Class_Eradicator"	) +
		CheckInventory("Class_Blazkowicz"	) +
		CheckInventory("Class_Freeman"		) +
		CheckInventory("Class_VorMatur"		) +
		CheckInventory("Class_Eleena"		) +
		CheckInventory("Class_Lucienne"		) +
		CheckInventory("Class_Major"		) +
		CheckInventory("Class_Hunter"		) +
		CheckInventory("Class_Sam"			) +
		CheckInventory("Class_Postal"		) +
		CheckInventory("Class_Painkiller"	) +
		CheckInventory("Class_Intruder"		) +
		CheckInventory("Class_Orbb"			) +
		CheckInventory("Class_Brock"		);
	// ^ insert more classes here

	if(mustbe1 > 1)
		while(!NamedRequestScriptPuke("QCDE_KMP", GetCvar("playerclass"), secretkey));
}

Script "QCDE_KMP" (int to, int security) NET
{
	int plr = PlayerNumber();

	if(security == secretkey)
		if(!SetPlayerLivesLeft(plr, GetPlayerLivesLeft(plr) + 1))
			log(s:"\c[red]QCDE ERROR: Failed to reimburse life to player ", n:0, s:" \c[red]killed by class switch.");

	DamageThing(0,0);
	ACS_NamedExecuteAlways("QCDE_ChangeClass_Hint", 0, to);
}



// Activator: Player
script "QCDE_InitLMS" (void)
{
	if(!(GetCvar("lastmanstanding") || GetCvar("teamlms"))) terminate;

	int overheal = 75;
	int maxArmor = ACS("MaxArmor");

	if(CheckInventory("Class_Sarge"))	{	overheal += 25;	maxArmor += 25;	}
	if(CheckInventory("Class_Postal"))	{	overheal += 25;					}
	if(CheckInventory("Class_Lucienne")){	maxArmor += 25;					}
	if(CheckInventory("Class_Brock"))	{	overheal += 24;	maxArmor -= 25;	}

	ACS("HealthGiver", ACS("MaxHealth"), 200, overheal);
	ACS("ArmorGiver", maxArmor, 200, true);
}



// Activator: Player
script "QCDE_UpdateLives" (void)
{
	if(!(
		getcvar("lastmanstanding") ||
		getcvar("teamlms") ||
		getcvar("survival") ||
		(getcvar("invasion") && getcvar("sv_maxlives") > 0)
	)) terminate;

	SetInventory("LifeToken", GetPlayerLivesLeft(PlayerNumber()) + 1);
}

script "AddLives" (int how_many, int plr)
{
	int a = 0, b = 63;
	if(plr) { a = plr; b = plr; }
	if(!how_many) { how_many = 1; }
	for(int i = a; i <= b; i++)
	{
		SetActivatorToPlayer(i);
		SetPlayerLivesLeft(i, GetPlayerLivesLeft(i) + how_many);
		ACS("QCDE_UpdateLives");
	}
}

// Activator: Player
script "QCDE_ReduceLife" DEATH
{
	if(!(getcvar("lastmanstanding") || getcvar("teamlms") || getcvar("survival"))) terminate;

	TakeInventory("LifeToken", 1);
}



Script "QCDE_UndropDuringInit" (void)
{
	if(Timer()) terminate;

	GiveInventory("UndroppedProc", 1);
}



Script "QCDE_DM_PlayerCollision" (void)
{
	if (GameType() < GAME_NET_DEATHMATCH) terminate; // only if game is DM

	GiveInventory("EnablePlayerCollisionProc", 1);
}



Script "QCDE_DM_ReplaceWeapons" (void)
{
	if (GameType() < GAME_NET_DEATHMATCH) terminate; // only if game is DM

	if(CheckInventory("QCMachinegun"		)) 	{ TakeInventory("QCMachinegun"		,1);	QCDE_Store("QCBulletAmmo");	GiveInventory("QCMachinegunDM"		,1); QCDE_Restore("QCBulletAmmo");	}
	if(CheckInventory("QCShotgun"			)) 	{ TakeInventory("QCShotgun"			,1);	QCDE_Store("QCShellAmmo");	GiveInventory("QCShotgunDM"			,1); QCDE_Restore("QCShellAmmo"	);	}
	if(CheckInventory("QCNailgun"			)) 	{ TakeInventory("QCNailgun"			,1);	QCDE_Store("QCNailAmmo"	);	GiveInventory("QCNailgunDM"			,1); QCDE_Restore("QCNailAmmo"	);	}
	if(CheckInventory("QCHeavyMachinegun"	)) 	{ TakeInventory("QCHeavyMachinegun"	,1);	QCDE_Store("QCBulletAmmo");	GiveInventory("QCHeavyMachinegunDM"	,1); QCDE_Restore("QCBulletAmmo");	}
	if(CheckInventory("QCSuperShotgun"		)) 	{ TakeInventory("QCSuperShotgun"	,1);	QCDE_Store("QCShellAmmo");	GiveInventory("QCSuperShotgunDM"	,1); QCDE_Restore("QCShellAmmo"	);	}
	if(CheckInventory("QCSuperNailgun"		)) 	{ TakeInventory("QCSuperNailgun"	,1);	QCDE_Store("QCNailAmmo"	);	GiveInventory("QCSuperNailgunDM"	,1); QCDE_Restore("QCNailAmmo"	);	}
	if(CheckInventory("QCTribolt"			))	{ TakeInventory("QCTribolt"			,1);	QCDE_Store("QCBoltAmmo"	);	GiveInventory("QCTriboltDM"			,1); QCDE_Restore("QCBoltAmmo"	);	}
	if(CheckInventory("QCRocketLauncher"	))	{ TakeInventory("QCRocketLauncher"	,1);	QCDE_Store("QCRocketAmmo");	GiveInventory("QCRocketLauncherDM"	,1); QCDE_Restore("QCRocketAmmo");	}
	if(CheckInventory("QCLightningGun"		)) 	{ TakeInventory("QCLightningGun"	,1);	QCDE_Store("QCCoilAmmo"	);	GiveInventory("QCLightningGunDM"	,1); QCDE_Restore("QCCoilAmmo"	);	}
	if(CheckInventory("QCRailgun"			)) 	{ TakeInventory("QCRailgun"			,1);	QCDE_Store("QCSlugAmmo"	);	GiveInventory("QCRailgunDM"			,1); QCDE_Restore("QCSlugAmmo"	);	}
	if(CheckInventory("QCBFG"				)) 	{ TakeInventory("QCBFG"				,1);	QCDE_Store("QCBFGAmmo"	);	GiveInventory("QCBFGDM"				,1); QCDE_Restore("QCBFGAmmo"	);	}
}
int store;
function void QCDE_Store(str what)
{
	store = CheckInventory(what);
}
function void QCDE_Restore(str what)
{
	SetInventory(what,store);
}


//This script dropped shards on player's death (called by a "Death"script)
//but due to lag+sv_forcerespawn, player would die, immediately respawn, and
//in the respawn point the script would barely take place, and player would
//get +15 armor free on respawn thanks to these shards.
//Now shards are spawned by the corpse actor itself.
/*Script "QCDE_DM_DropShards" (void)
{
	if (GameType() < GAME_NET_DEATHMATCH) terminate; // only if game is DM
	SpawnForced("QCPlayerArmorDrop",GetActorX(0),GetActorY(0),GetActorZ(0));
}*/



// Activator: victim
Script "QCDE_DM_FragBeep" (void) clientside
{
	if (GameType() < GAME_NET_DEATHMATCH) terminate;      // only if game is DM
	if (!GetActorProperty(0, APROP_TargetTID)) terminate; // only if killer has TID

	SetActivatorToTarget(0);
	// Activator: killer

	if(CheckPlayerCamera(ConsolePlayerNumber()) != PlayerNumber() + 1000) terminate;
	if(CheckInventory("DisableColor")) terminate;
	AmbientSound("QC/UI/FragBeep",127);
}


// Make players slower or faster depending on server settings

Script "QCDE_CalculatePlayerSpeed" (void)
{
	int sv_PlayerSpeed = GetCvar("sv_PlayerSpeed");

	if (sv_PlayerSpeed == 0 || InCampaign() || GetCVar("qc_defrag"))
	{
		if (InCampaign() || GetCVar("qc_defrag") || GetCvar("deathmatch") || GetCvar("ctf") || GetCvar("oneflagctf") || GetCvar("skulltag") || GetCvar("domination") || GetCvar("customteamgame"))
			sv_PlayerSpeed = 80;
		else
			sv_PlayerSpeed = 100;
	}

	sv_PlayerSpeed = sv_PlayerSpeed / 5 * 5; // floor to multiple of 5
	if(sv_PlayerSpeed <  70) sv_PlayerSpeed =  70;
	if(sv_PlayerSpeed > 130) sv_PlayerSpeed = 130;

	SetResultValue(sv_PlayerSpeed);
}

Script "QCDE_PlayerSpeed" (void)
{
	int sv_PlayerSpeed = ACS_NamedExecuteWithResult("QCDE_CalculatePlayerSpeed", 0);

	str power = strparam(s:"PlayerSpeed", d:sv_PlayerSpeed);
	GiveInventory(power, 1);
}


Script "StackLeft" (int evtTyp, int victimNo, int arg2) EVENT
{
	if(!GetCVar("sv_showstackleft")) terminate;
	if(GameType() < GAME_NET_DEATHMATCH || GetGameModeState() < GAMESTATE_INPROGRESS) terminate;

	if(evtTyp == 0) {
		Delay(5); //leave time for QCDE scripts to run

		int hp = GetActorProperty(0, APROP_Health);
		int ap = CheckInventory("BasicArmor");

		ACS_NamedExecuteAlways("StackLeft_Clientside", 0, 1000 + victimNo, hp, ap);
	}
}

Script "StackLeft_Clientside" (int victimTid, int hp, int ap) clientside
{
	if (victimTid == CheckPlayerCamera(ConsolePlayerNumber()))
	{
		SetFont("SMALLFNT");
		HudMessageBold(s:"\cgStack left: \cv", d:hp, s:"\cj/\cd", d:ap; HUDMSG_FADEOUT, 1, CR_RED, 0.5, 0.40, 2.5, 0.5, 1);
	}
}

Script "QCDE_Handicap" (void)
{
	int handicap = GetUserCvar(PlayerNumber(), "cl_qcHandicap");
		
	// Default setting, nothing to do
	if(handicap == 100) terminate;

	// Toss any value, that's out of bounds.
	if(handicap < 50 || handicap > 100)
	{
		ACS_NamedExecuteAlways("QCDE_Handicap_UpdateCVar", 0, 100);
		ACS_NamedExecuteAlways("QCDE_Handicap_UpdateCVar_Client", 0, 100);
		ACS_NamedExecuteAlways("QCDE_Handicap_Notification", 0, 0, false);
		terminate;
	}
	
	// Floor any value not divisible by 5 and rewrite CVar
	if(handicap % 5 != 0) {
		handicap = handicap / 5 * 5;
		ACS_NamedExecuteAlways("QCDE_Handicap_UpdateCVar", 0, handicap);
		ACS_NamedExecuteAlways("QCDE_Handicap_UpdateCVar_Client", 0, handicap);
	}
	
	str handiPWR = StrParam(s:"Handicap", d:handicap);
	GiveInventory(handiPWR, 1);
	
	ACS_NamedExecuteAlways("QCDE_Handicap_Notification", 0, handicap, true);
}

Script "QCDE_Handicap_UpdateCVar" (int value) 
{
	SetUserCvar(PlayerNumber(), "cl_qcHandicap", value);
}

Script "QCDE_Handicap_UpdateCVar_Client" (int value) CLIENTSIDE
{
	SetUserCvar(ConsolePlayerNumber(), "cl_qcHandicap", value);
}

// For effects tracking items that might respawn, additional condition to
// finish animation.
// Spawner is expected to be target.
Script "QCDE_EffectMustDie" (void)
{
	SetActivatorToTarget(0);
	SetResultValue(CheckFlag(0, "INVISIBLE"));
}

// For effects tracking players who might die, condition to disappear.
// Player is expected to be target.
Script "QCDE_AbilityFXMustDie" (void)
{
	SetActivatorToTarget(0);
	bool result = false;
	result |= GetActorProperty(0,APROP_HEALTH) <= 0;
	result |= GetActorProperty(0,APROP_HEALTH) > 0 && GetActorProperty(0,APROP_HEIGHT) == 0;
	result |= PlayerIsSpectator(PlayerNumber());
	result |= CheckInventory("PowerGhostTint") || CheckInventory("PowerWendigoTint");
	SetResultValue(result);
}

// For effects that follow players affected by powerup, condition to finish
// animation.
// For indicator XyzIndicator, powerup is expected to be named PowerXyz.
// Affected player is expected to be target.
// removes powerup indicator as well. Used by Nyx's Ghostwalk.
Script "QCDE_PowerupIndicatorMustDie" (void)
{
	str indicatorName = strparam(n:0);
	int nameLength = strlen(indicatorName) - 9; // 9 = "indicator"
	str powerName = strparam(s:"Power", s:strmid(indicatorName,0,nameLength));

	SetActivatorToTarget(0);
	bool expired = !GetActorPowerupTics(0,powerName);

	SetResultValue(expired);
}

// For effects that follow players affected by powerup, condition to hide
// animation.
Script "QCDE_PowerupIndicatorMustDisappear" (void)
{
	SetActivatorToTarget(0);
	bool sneaky = CheckInventory("PowerGhostTint") || CheckInventory("PowerWendigoTint");

	SetResultValue(sneaky);
}

Script "QCDE_RemoveIfNoPowerups" (int noRestore)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate;
	if(GetCvar("qc_elderssoul")) terminate; // sic!
	if(GetCvar("duel")) Thing_Remove(0);
	if(!GetCvar("sv_QCDEPowerups")) Thing_Remove(0);
}

Script "QCDE_RemoveIfNoBfg" (int noRestore)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate;
	if(GetCvar("qc_elderssoul")) terminate; // sic!
	if(GetCvar("duel")) Thing_Remove(0);
	if(!GetCvar("sv_QCDEBFG")) Thing_Remove(0);
}

script "QCDE_RemoveIfDuel" (int noRestore)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate;
	if(GetCvar("duel")) Thing_Remove(0);
}

// Prevent Dave & Merlin from farming too many frags on bots.
// Not too much, because Merlin's own kills on bots also hurt his Dave.
#define DAVE_BOT_PENALTY 40 //+ slight randomization
Script "QCDE_DM_HurtDave" (void)
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate;
	if(!PlayerIsBot(PlayerNumber())) terminate;

	SetActivatorToTarget(0);
	if(!CheckActorClass(0,"QCMenelkir")) terminate;

	Thing_Damage(PlayerNumber() + MAULOTAUR_TIDBASE, -DAVE_BOT_PENALTY+random(-5,0), MOD_UNKNOWN);
}

// Automatically spectate players if you're a spectator.
// Useful when DBT is AFK on stream.
// https://twitch.tv/dbthanatos <- RT for a free ipod! Limited offer!
Script "QCDE_AutoSpyNext" OPEN CLIENTSIDE
{
	while(true)
	{
		delay(35);

		if(!GetCvar("cl_autoSpecDelay")) continue;

		if(PlayerIsSpectator(ConsolePlayerNumber()))
		{
			ConsoleCommand("spynext");

			// Failed to acquire watchable target?
			delay(1);
			int tid = CheckPlayerCamera(ConsolePlayerNumber());
			if(tid < 1000) continue;

			int time = GetCvar("cl_autoSpecDelay");
			log(s:"Automatically spectating ", n:tid - 999, s:" for ", d:time, s:" seconds...");
			Delay(time * 35);
		}
	}
}


//*****************************************************************************
//*****************************************************************************
// These scripts check if there are fewer players than `sv_minplayers` and
// tries to add bots. Removes bots if people connect.
//*****************************************************************************
//*****************************************************************************
Script "QCDE_Players=0" OPEN
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate; // only in DM
	if(GameType() == GAME_TITLE_MAP) terminate;
	if(InCampaign() || GetCVar("qc_defrag")) terminate;

	if (!GetCvar("sv_minplayers") && GetCVar("skirm_botscount") && GetNetworkState() != NETSTATE_SERVER)
	{
		int maxBots = GetCVar("skirm_botscount");
		if (maxBots > 32)
			maxBots = 32;
		int botCount = 0;
		int i;
		if (GetGameModeState() < GAMESTATE_INPROGRESS)
			ConsoleCommand("removebots");
		for (i = 0; i < 64; i++)
			if(PlayerIsBot(i))
				botCount++;
		for (i = botCount; i < maxBots; i++)
		{
			delay(35);
			ConsoleCommand("addbot");
		}
		terminate;
	}

	int max =~- GetCvar("sv_maxplayers");
	if(GetCvar("duel")) max = 2;
	int min = clamp(GetCvar("sv_minplayers"), 0, max);

	if(GetCvar("sv_minPlayers") && GetGameModeState() <= 2)
	{
		if(GetCvar("sv_shuffleBots") == 1)
		{
			ConsoleCommand("removebots");
		}
		if(GetCvar("sv_shuffleBots") == 2)
		{
			ConsoleCommand("removebot");
		}
	}

	while(true)
	{
		if(!GetCvar("sv_minplayers")) terminate;
		//log(s:"Prefill. ", d:PlayerCount(), s:" >= ", d:min, s:"? ", s:btos[PlayerCount() >= min]);
		if(PlayerCount() >= min) terminate;
		addOrRemoveBot(-1);
		delay(35);

		// Special case for `removebots`: don't restore them immediately
		if(thereAreNoBots()) terminate;
	}
}
Script "QCDE_Players++" ENTER
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate; // only in DM
	if(GameType() == GAME_TITLE_MAP) terminate;
	if(!GetCvar("sv_minplayers")) terminate;

	int plr = PlayerNumber();
	if(PlayerIsBot(plr)) terminate; // allow overprovising bots

	delay(1);

	addOrRemoveBot(plr);
}
Script "QCDE_Players--" (int plr) DISCONNECT
{
	if(GameType() < GAME_NET_DEATHMATCH) terminate; // only in DM
	if(GameType() == GAME_TITLE_MAP) terminate;
	if(!GetCvar("sv_minplayers")) terminate;

	delay(1);

	addOrRemoveBot(plr);
}

function int thereAreNoBots(void)
{
	int i;
	for(i = 0; i < 64; i++)
	{
		if(!ClassifyActor(1000 + i)) continue; // absent in any form? can't judge
		if(PlayerIsBot(i))
		{
			//log(n:i + 1, s:" is present and a bot, so there are bots.");
			return false;
		}
	}
	//log(s:"No bots in sight.");
	return true;
}

function void addOrRemoveBot(int plr)
{
	int max =~- GetCvar("sv_maxplayers");
	if(GetCvar("duel")) max = 2;
	int min = clamp(GetCvar("sv_minplayers"), 0, max);
	int now = PlayerCount();

	if(now > min)
	{
		//log(n:plr + 1, s:" -- There are ", d:now, s:" players, and minimum is set at ", d:min, s:", so one bot is kicked.");
		ConsoleCommand("removebot");
	}
	else if(now < min)
	{
		if(GetCvar("lastmanstanding") || GetCvar("teamlms"))
			if(GetGameModeState() >= 3) // GAMESTATE_INPROGRESS
				return; // not in LMS in progress
		//log(n:plr + 1, s:" ++ There are ", d:now, s:" players, and minimum is set at ", d:min, s:", so one bot is added.");
		ConsoleCommand("addbot");
	}
}





//*****************************************************************************
//*****************************************************************************
// Maps
//*****************************************************************************
//*****************************************************************************

Script "QCDE_StartSkirmish" (void) NET CLIENTSIDE
{
	if (GetNetworkState() == NETSTATE_CLIENT || GetNetworkState() == NETSTATE_SERVER)
	{
		Log(s:"You can't start an offline skirmish while in online game");
	}
	else
	{
		setupGamemode();
		setupModifier();
		ConsoleCommand("sv_minPlayers 0");
		ConsoleCommand("skill 2");
		clearBots();

		int category = 0;
		switch(GetCVar("skirm_skirmishgamemode"))
		{
		case 0:  category = 0;	break;	// Cooperative
		case 1:  category = 0;	break;	// Survival
		case 2:  category = 3;	break;	// Invasion
		case 3:  category = 1;	break;	// Deathmatch
		case 4:  category = 1;	break;	// Team Deathmatch
		case 5:  category = 1;	break;	// Duel
		case 6:  category = 1;	break;	// Last Man Standing
		case 7:  category = 1;	break;	// Team Last Man Standing
		case 8:  category = 1;	break;	// Freeze Tag
		case 9:  category = 1;	break;	// Elder's Soul
		case 10: category = 1;	break;	// Team Elder's Soul
		case 11: category = 2;	break;	// Capture The Flag
		case 12: category = 2;	break;	// One flag CTF
		case 13: category = 4;	break;	// Domination
		case 14: category = 5;	break;	// Defrag
		}
		ConsoleCommand(strparam(s:"menu_startskirmish customgamemode ", d:category));
	}
}

function void clearBots()
{
	int i;
	for (i = 0; i < 16; i++)
	{
		ConsoleCommand(strparam(s:"menu_botspawn",	d:i, s:" -1"));
	}
	for (i = 0; i < 80; i++)
	{
		ConsoleCommand(strparam(s:"menu_teambotspawn",	d:i, s:" -1"));
	}
}

function void setupGamemode()
{
	int gamemode = GetCVar("skirm_skirmishgamemode");
	int menu_skirmishgamemode = 0; // default to coop
	int menu_timelimit = 0;
	int qc_elderssoul = 0;
	int qc_freezetag = 0;
	int qc_defrag = 0;

	switch (gamemode) {
	case 0:  menu_skirmishgamemode = 0;							break;	// Cooperative
	case 1:  menu_skirmishgamemode = 1;							break;	// Survival
	case 2:  menu_skirmishgamemode = 2;							break;	// Invasion
	case 3:  menu_skirmishgamemode = 3;							break;	// Deathmatch
	case 4:  menu_skirmishgamemode = 4;							break;	// Team Deathmatch
	case 5:  menu_skirmishgamemode = 5;							break;	// Duel
	case 6:  menu_skirmishgamemode = 7;							break;	// Last Man Standing
	case 7:  menu_skirmishgamemode = 8;							break;	// Team Last Man Standing
	case 8:  menu_skirmishgamemode = 8; qc_freezetag = 1;		break;	// Freeze Tag
	case 9:  menu_skirmishgamemode = 3; qc_elderssoul = 1;		break;	// Elder's Soul
	case 10: menu_skirmishgamemode = 4;	qc_elderssoul = 1;		break;	// Team Elder's Soul
	case 11: menu_skirmishgamemode = 12;						break;	// Capture The Flag
	case 12: menu_skirmishgamemode = 13;						break;	// One Flag CTF
	case 13: menu_skirmishgamemode = 15;						break;	// Domination
	case 14: menu_skirmishgamemode = 0;	qc_defrag = 1;			break;	// Defrag
	}

	// If PvP, use timelimit
	if (gamemode >= 3 && gamemode <= 13) {
		menu_timelimit = GetCVar("skirm_timelimit");
	}

	ConsoleCommand(strparam(s:"sv_showItemTimers ",			d:GetCVar("skirm_showItemTimers")));
	ConsoleCommand(strparam(s:"sv_showStackLeft ",			d:GetCVar("skirm_showStackLeft")));
	ConsoleCommand(strparam(s:"sv_QCDEPowerups ",			d:GetCVar("skirm_QCDEPowerups")));
	ConsoleCommand(strparam(s:"menu_skirmishgamemode ",		d:menu_skirmishgamemode));
	ConsoleCommand(strparam(s:"menu_skirmishtimelimit ",	d:menu_timelimit));
	ConsoleCommand(strparam(s:"qc_freezetag ",				d:qc_freezetag));
	ConsoleCommand(strparam(s:"qc_elderssoul ",				d:qc_elderssoul));
	ConsoleCommand(strparam(s:"qc_defrag ",					d:qc_defrag));
	ConsoleCommand(strparam(s:"sv_maxlives ",				d:GetCVar("skirm_maxlives")));
}

function void setupModifier()
{
	int gamemode = GetCVar("skirm_skirmishgamemode");
	int modifier = GetCVar("skirm_skirmishmodifier");
	int menu_skirmishmodifier = 0;
	int rocketarena = 0;

	if (gamemode != 14) // Defrag
	{
		switch (modifier)
		{
		case 1: menu_skirmishmodifier = 1;		break;	// Instagib
		case 2: rocketarena = 1;				break;	// Rocket Arena
		case 3: rocketarena = 3;				break;	// Unholy Trinity
		case 4: rocketarena = 2;				break;	// Buckshot
		case 5: rocketarena = 4;				break;	// Lightning Storm
		case 6: rocketarena = 6;				break;	// Random Weapons
		case 7: {										// Custom Weapons
			if (GetCVar("skirm_heavymachinegun"))	rocketarena += 0000000001;
			if (GetCVar("skirm_supershotgun"))		rocketarena += 0000000010;
			if (GetCVar("skirm_supernailgun"))		rocketarena += 0000000100;
			if (GetCVar("skirm_tribolt"))			rocketarena += 0000001000;
			if (GetCVar("skirm_rocketlauncher"))	rocketarena += 0000010000;
			if (GetCVar("skirm_lightninggun"))		rocketarena += 0000100000;
			if (GetCVar("skirm_railgun"))			rocketarena += 0001000000;
			if (GetCVar("skirm_bfg"))				rocketarena += 0010000000;
			break;
		}
		}
	}

	ConsoleCommand(strparam(s:"allstarterweapons ", d:GetCVar("skirm_starterweap")));
	ConsoleCommand(strparam(s:"menu_skirmishmodifier ",		d:menu_skirmishmodifier));
	ConsoleCommand(strparam(s:"rocketarena ",	d:rocketarena));
	ConsoleCommand(strparam(s:"sv_QCDEBFG ",	d:GetCVar("skirm_QCDEBFG")));
}


//*****************************************************************************
//*****************************************************************************
// Pings
//*****************************************************************************
//*****************************************************************************

// TBD
