#library "MUZAK"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"
#import "MUZAKCST.acs"

#define NUMBER_OF_SONGS 31
#define JUKEBOX_TID 46290

int servers_suggestion = -1;
Script "QCDE_Music" OPEN CLIENTSIDE
{
	if(GameType() == GAME_TITLE_MAP) terminate;

	int randomness = GetUserCvar(CPN(), "snd_randommus");
	if (GetNetworkState() != NETSTATE_SERVER && randomness == 3) terminate;

	if((GetGameModeState() == 0 && (GetCvar("survival") || GetCvar("invasion") || GetCvar("duel") || GetCvar("lastmanstanding") || GetCvar("teamlms") || GetCvar("possession") || GetCvar("teampossession") || GetCvar("teamgame"))) ||
		GetGameModeState() == 1) // GAMESTATE_WAITFORPLAYERS in countdown modes or just GAMESTATE_COUNTDOWN
	{
		SetMusic("SILENCIO");
		terminate;
	}

	if(CheckQcdeModule("QCDE-OST") == false) terminate;
	delay(1);

	int sel = -1;
	// Play song through QCDE jukebox if it's present, but not if RANDOM mode is enabled
	if(IsTidUsed(JUKEBOX_TID) && (randomness < 2))
	{
		SetActorState(JUKEBOX_TID, "Play");
		terminate;
	}

	int i;
	if(randomness == 1)
	{
		SetMusic("SILENCIO");
		//log(s:TimeNow(), s:": requesting suggestions");
		if(IsZandronum(true))
			NamedRequestScriptPuke("QCDE_PickRandomSong", CPN());
		else
			ACS("QCDE_PickRandomSong", CPN());
		while(servers_suggestion == -1)
		{
			delay(1);
			if(Timer() % 7 == 0)
			{
				//log(s:TimeNow(), s:": requesting suggestions again");
				NamedRequestScriptPuke("QCDE_PickRandomSong", CPN(), true);
			}
		}
		sel = servers_suggestion;
	}
	else if(randomness == 2)
		while(sel == -1 || sel == GetUserCvar(CPN(), "_previousSong"))
			sel = random(i++, NUMBER_OF_SONGS - 1);
	else
		sel = GetLevelInfo(LEVELINFO_LEVELNUM) % NUMBER_OF_SONGS;

	PlaySong(sel);
	delay(145);
	PrintSongName(sel);
}


Script "QCDE_Jukebox" (int x) NET CLIENTSIDE
{
	if(CheckQcdeModule("QCDE-OST") == false) terminate;

	int randomness = GetUserCvar(CPN(), "snd_randommus");
	if (GetNetworkState() != NETSTATE_SERVER && randomness == 3) terminate;

	//log(s:"Jukes: Playing map-defined ", d:x);
	PlaySong(x);
	delay(145);
	PrintSongName(x);
}

Script "QCDE_PickRandomSong" (int asker, int repeated) NET
{
	//log(s:TimeNow(), s:": ", n:asker+1, s:" asking for music (repeat? ", s:btos[repeated], s:")");
	if(servers_suggestion == -1)
	{
		servers_suggestion = makeSuggestion();
	}
	ACS("QCDE_RandomSongPicked", servers_suggestion);
}

// Suggestion data is put into existing global array enabled_themes, using 400..499 cells
// Think this is ugly? I agree
function int makeSuggestion(void)
{
	//log(s:"400th == ", d:enabled_themes[400]);
	if(!enabled_themes[400] || enabled_themes[400] == NUMBER_OF_SONGS)
	{
		// pre-fill
		int i;
		for(i = 1; i <= NUMBER_OF_SONGS; i++)
			enabled_themes[400 + i] = i;

		// shuffle
		for(i = 1; i <= NUMBER_OF_SONGS; i++)
		{
			int j = random(1, NUMBER_OF_SONGS);
			if(i != j)
				enabled_themes[400 + i] ^= enabled_themes[400 + j] ^= enabled_themes[400 + i] ^= enabled_themes[400 + j];
		}


		enabled_themes[400] = 0;
	}

	//str s = "playlist data: ";
	//for(i = 0; i <= NUMBER_OF_SONGS; i++)
	//	s = strparam(s:s, s:"  ", d:enabled_themes[400 + i] -!! i);
	//printbold(s:s);


	return enabled_themes[+400+ ++enabled_themes[400]]-1;
}

Script "QCDE_RandomSongPicked" (int which) CLIENTSIDE
{
	servers_suggestion = which;
}

Script "QCDE_SetMusicNumber" (int musicNumber)
{
	if (SpawnForced("QCDE OST", 0, 0, 0, JUKEBOX_TID))
		SetThingSpecial(JUKEBOX_TID, 0, musicNumber);
}

function int GetTune(int x)
{
	return strparam(s:"a", d:x/1000000%10, d:x/100000%10, d:x/10000%10, d:x/1000%10, d:x/100%10, d:x/10%10, d:x%10);
}

function void PlaySong(int x)
{
	SetMusic(GetTune(x),0,1);
	SetUserCvar(CPN(), "_previousSong", x);
	SetActivator(1000 + ConsolePlayerNumber());
}

function void PrintSongName(int x)
{
	if (GetCvar("screenblocks") >= 12) return;

	SetHudSize(640, 480, 1);
	SetFont("QCSMFONT");
	HudMessage(s:" \c[yellow]Music: \c[brite]", s:getMusicName(x), s:"\n \c[yellow]Author: \c[brite]", s:getMusicAuthor(x),
		s:"\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
		s:"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"; // this helps placing the text box properly
		HUDMSG_FADEINOUT, 0, CR_RED, 272.0, 296.0, 2.3, 0.9, 1.0);
}
