#library "WEAPONS"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"
#import "WEAPCNST.bcs"
#include "../BotSource/headers/TDBots.h.bcs"

int weaponSpawned[NUMBER_OF_WEAPONS];

Script "QCDE_WeaponSpawned" (int type, int arg4)
{
	// Weapon-centric modes
	if(GetCvar("instagib") || GetCvar("rocketarena"))
	{
		//log(s:"Weapon removed: ", s:weaponList[type]);
		Thing_Remove(0);
		terminate;
	}

	if(arg4 == 234)
	{
		//log(s:"Weapon spawns its smoke: ", s:weaponList[type]);
		str smonk = "WeaponSpawnPointBase";
		switch(type)
		{
		case  8: smonk = "SpawnPoint_HMG"; break;
		case 10: smonk = "SpawnPoint_SSG"; break;
		case 12: smonk = "SpawnPoint_SNG"; break;
		case 14: smonk = "SpawnPoint_TB" ; break;
		case 16: smonk = "SpawnPoint_RL" ; break;
		case 18: smonk = "SpawnPoint_LG" ; break;
		case 20: smonk = "SpawnPoint_RG" ; break;
		case 22: smonk = "SpawnPoint_BFG"; break;
		case 3: case 7: case 9: case 11: case 13: case 15: case 17: case 19: case 21: smonk = "FX"; break;
		default: log(s:"QCDE Warning: Unexpected weapon type spawning smoke: ", d:type); break;
		}

		int x = GetActorX(0);
		int y = GetActorY(0);
		int z = GetActorZ(0);
		SpawnForced(smonk, x,y,z);
	}

	//log(s:"Weapon trying to spawn: ", s:weaponList[type]);

	SetTidIfHadNone(WEAPON_TIDBASE, WEAPON_TIDLAST);

	weaponSpawned[type] = true;
	//log(s:"Weapon ", d:type, s:" spawns successfully ", s:weaponList[type], s:", tid = ", d:tid);
}

Script "QCDE_IsWeaponOnMap" (int type)
{
	if(type >= 0 && type < NUMBER_OF_WEAPONS)
		SetResultValue(weaponSpawned[type]);
	else
		log(s:"QCDE WARNING: Weapon ", d:type, s:" is queried. Timer: ", d:Timer());
}

// Activator: weapon pickup
Script "QCDE_SetWeaponRespawnTics" (void)
{
	int result;
	if (!GetCvar("sv_itemrespawn"))
		result = 0x7FFFFFFF;
	else if (GetCvar("sv_weaponrespawn"))
		result = (GetCvar("sv_weaponrespawn") - 1) * 35; // + 1 second from Decorate
	else if(GetCvar("duel"))
		result = 4 * 35; // + 1 second from Decorate
	else // all non-duel games with items set to respawn
		result = 0 * 35; // + 1 second from Decorate
	//PrintBold(n:0, s:" result: ", d:result);
	SetResultValue(result);
}


//=============================================================================
//
//		Rocket whoosh
//
//=============================================================================

// Activator: noisy projectile in flight
script "QCDE_AttachWhoosh" (void) CLIENTSIDE
{
	// remember rocket
	int tid = ActivatorTid();
	if(!tid)
	{
		tid = UniqueTid();
		Thing_ChangeTid(0,tid);
	}

	// don't whoosh if your own rocket
	SetActivatorToTarget(0);
	if(ConsolePlayerNumber() == PlayerNumber()) terminate;

	// if rocket isn't moving, then it has exploded already. So no whoosh
	if (GetActorVelX(tid) || GetActorVelY(tid) || GetActorVelZ(tid))
		PlaySound(tid, "QC/Weapons/RocketLauncher/Fly",CHAN_5,0.5,true,1.0); // whoosh!
}


//----------------------------------------------------------------------
// Script for controlled rocket
#DEFINE SPEED    13
#DEFINE TURNSPEED 0.017
int greymask[64];

// Activator: controlled rocket
Script "QCDE_RocketControl" (void)
{
	int tid = GUIDEDROCK_TIDBASE + GetActorProperty(0, APROP_TargetTID) - 1000;
	int plrtid = GetActorProperty(0, APROP_TargetTID);
	int plr = plrtid - 1000;
	//printbold(s:"rocket flying with tid ", d:tid, s:", from ", n:plr + 1);

	Thing_ChangeTID(0, tid);

	SetActivator(plrtid);
	// Activator: rocket owner

	delay(1);

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	ChangeCamera(tid, false, false);
	SetNetworkReplicationFlags( 0 );
	SetActivator(tid);
	// Activator: controlled rocket

	greymask[plr] = true;
	int origa = GetActorAngle(plrtid), a = origa;
	int origp = GetActorPitch(plrtid), p = origp;
	while(!CheckInventory("ImDead"))
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );

		Thing_Stop(tid);

		int ip = -GetPlayerInput(plr, INPUT_PITCH);
		if(ip >  TURNSPEED) ip =  TURNSPEED;
		if(ip < -TURNSPEED) ip = -TURNSPEED;
		p += ip;
		if(p >  0.25) p =  0.25;
		if(p < -0.25) p = -0.25;

		int spd_ver = (-sin(p) * SPEED) >> 14;
		ThrustThingZ(tid, spd_ver, 0, 0);

		int ia = GetPlayerInput(plr, INPUT_YAW);
		if(ia >  TURNSPEED) ia =  TURNSPEED;
		if(ia < -TURNSPEED) ia = -TURNSPEED;
		a += ia;

		int spd_hor = (cos(p) * SPEED) >> 16;
		ThrustThing(a>>8, spd_hor, 1, tid);
		SetActorAngle(tid, a);
		SetActorPitch(tid, p);

		SetNetworkReplicationFlags( 0 );

		delay(1);

		int triggers = GetPlayerInput(plr, INPUT_BUTTONS) & ~GetPlayerInput(plr, INPUT_OLDBUTTONS);
		if(triggers & (BT_ATTACK | BT_ALTATTACK))
			GiveInventory("ImDead",1);
	}
	greymask[plr] = false;
	while(IsTidUsed(tid))
	{
		delay(1);
	}
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetActorAngle(plrtid, origa);
	SetActorPitch(plrtid, origP);
	SetNetworkReplicationFlags( 0 );

	SetActivator(plrtid);
	SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
	TakeInventory("PowerControllerProtection",1);
}

//this is the dark screen effect, will loop until the projectile terminates it manually
Script "QCDE_TunnelVision" (void)
{
	if (GetNetworkState() == NETSTATE_SERVER)
		terminate;

	delay(2); // time for rocket to initialize
	int plrtid = GetActorProperty(0, APROP_TargetTID);
	int plr = plrtid - 1000;
	SetActivator(plrtid);
	SetHudSize(320,240,1);
	int hmid = HMID_TUNNEL_VISION;
	SetFont("GREYMASK");
	while(greymask[plr])
	{
		HudMessage(s:"A";HUDMSG_FADEINOUT,hmid++,-1, 160.0,120.0, 0.4,0.2,0.4);
		if(hmid >= HMID_TUNNEL_VISION + 64) hmid = HMID_TUNNEL_VISION;
		delay(random(20,25));
	}
}

Script "QCDE_ResetRocketFov" (void)
{
	int tid = GUIDEDROCK_TIDBASE + GetActorProperty(0, APROP_TargetTID) - 1000;
	SetCameraToTexture(tid, "CAMERT", 90);
}


//------------------------------------------------
// Weapon alt fire modifier messages

script "QCDE_ModSelectedText" (int weapon, int upgrade)
{
	//SetHUDSize(800,600,1);
	SetHUDSize(400,300,1);
	SetFont("ESFONTAA");
	str color = strparam(s:"\c[", s:GetWeapon(), s:"]");
	HudMessage(s:color, s:WeaponUpgrades[weapon][1][WU_PROPERNAME], s:" engaged";HUDMSG_PLAIN,101,-1,200.0,240.0,0);

	while(checkinventory("WeaponZoomedToken"))
	{
		Delay(2);
	}

	ACS_NamedExecuteAlways("RemoveModText",0,0);
}

script "RemoveModText" (void)
{
	HudMessage(s:" ";HUDMSG_PLAIN,101,"SkyBlue",0.75,1.0,0.1);
}


//------------------------------------------------
// Weapon hitmarker

script "QCDE_HitMark" (void) clientside
{
	if(IsZandronum(true))
		if(ActivatorTid() != CheckPlayerCamera(ConsolePlayerNumber()))
			terminate;

	SetHUDSize(1200,900,1);
	SetFont("HITMED");
	HudMessageBold(s:"a";HUDMSG_FADEOUT,-234,-1,600.0,450.0,0.0,0.15);
}

Script "QCDE_ConfigureBotWeapons" (void)
{
	// Define ability weapons with max priority and infinite range, to prevent bots from switching to other weapons
	TDB_Weapon_New(		"BlazkoAkimbo",			10);
	TDB_Weapon_New(		"CalebDoll",			10);
	TDB_Weapon_New(		"SlayerBFG",			10);
	TDB_Weapon_New(		"Shieldquisitor",		10);
	TDB_Weapon_New(		"PostalCowHead",		10);
	TDB_Weapon_New(		"SorgaulFists",			10);

	// Setup fire modes
	//					Name					Ammo Class		Ammo Use	Proj Speed	Min Dist	Max Dist	Flags								Alt Fire chance
	TDB_Weapon_Pri(		"BlazkoAkimbo",			"",					0,		25.0,		0.0,		MAX_RANGE,	TDB_CW_PROJECTILE);
	TDB_Weapon_Alt(		"BlazkoAkimbo",			"",					0,		0.0,		0.0,		MAX_RANGE,	0,									0.5);
	TDB_Weapon_Pri(		"CalebDoll",			"",					0,		0.0,		0.0,		MAX_RANGE,	0);
	TDB_Weapon_Pri(		"SlayerBFG",			"",					0,		25.0,		0.0,		MAX_RANGE,	TDB_CW_PROJECTILE);
	TDB_Weapon_Pri(		"Shieldquisitor",		"",					0,		0.0,		0.0,		MAX_RANGE,	0);
	TDB_Weapon_Pri(		"PostalCowHead",		"",					0,		14.0,		0.0,		MAX_RANGE,	TDB_CW_PROJECTILE);
	TDB_Weapon_Pri(		"SorgaulFists",			"",					0,		0.0,		0.0,		MAX_RANGE,	TDB_CW_MELEE);

	// Define normal weapons
	//					Name				Priority
	TDB_Weapon_New(		"DukeFreezeThrower",	4);
	TDB_Weapon_New(		"SamMinigun",			3);
	TDB_Weapon_New(		"QCGauntlet",			0);
	TDB_Weapon_New(		"QCMachinegunDM",		1);
	TDB_Weapon_New(		"QCHeavyMachinegunDM",	1);
	TDB_Weapon_New(		"QCShotgunDM",			1);
	TDB_Weapon_New(		"QCSuperShotgunDM",		1);
	TDB_Weapon_New(		"QCNailgunDM",			1);
	TDB_Weapon_New(		"QCSuperNailgunDM",		1);
	TDB_Weapon_New(		"QCTriboltDM",			2);
	TDB_Weapon_New(		"QCRocketLauncherDM",	3);
	TDB_Weapon_New(		"QCLightningGunDM",		3);
	TDB_Weapon_New(		"QCRailgunDM",			3);
	TDB_Weapon_New(		"QCBFGDM",				4);

	// Setup fire modes
	//					Name					Ammo Class		Ammo Use	Proj Speed	Min Dist	Max Dist	Flags								Alt Fire chance
	// Abilities
	TDB_Weapon_Pri(		"DukeFreezeThrower",	"DukeAmmo",			1,		25.0,		0.0,		400.0,		TDB_CW_PROJECTILE);
	TDB_Weapon_Alt(		"DukeFreezeThrower",	"DukeAmmo",			0,		0.0,		0.0,		128.0,		0,									0.5);
	TDB_Weapon_Pri(		"SamMinigun",			"SeriousBullets",	1,		0.0,		0.0,		700.0,		0);
	TDB_Weapon_Alt(		"SamMinigun",			"SeriousBullets",	1,		0.0,		0.0,		400.0,		0,									0.5);

	//					Name					Ammo Class		Ammo Use	Proj Speed	Min Dist	Max Dist	Flags	Alt Fire chance
	// Starter weapons + upgrades
	TDB_Weapon_Pri(		"QCGauntlet",			"",					0,		0.0,		0.0,		55.0,		TDB_CW_MELEE);
	TDB_Weapon_Pri(		"QCMachinegunDM",		"QCBulletAmmo",		1,		0.0,		300.0,		MAX_RANGE,	0);
	TDB_Weapon_Pri(		"QCHeavyMachinegunDM",	"QCBulletAmmo",		1,		0.0,		300.0,		MAX_RANGE,	0);
	TDB_Weapon_Pri(		"QCShotgunDM",			"QCShellAmmo",		1,		0.0,		0.0,		400.0,		0);
	TDB_Weapon_Pri(		"QCSuperShotgunDM",		"QCShellAmmo",		1,		0.0,		0.0,		400.0,		0);
	TDB_Weapon_Pri(		"QCNailgunDM",			"QCNailAmmo",		1,		52.0,		0.0,		700.0,		TDB_CW_PROJECTILE);
	TDB_Weapon_Pri(		"QCSuperNailgunDM",		"QCNailAmmo",		1,		52.0,		0.0,		700.0,		TDB_CW_PROJECTILE);

	//					Name					Ammo Class		Ammo Use	Proj Speed	Min Dist	Max Dist	Flags	Alt Fire chance
	// Strong weapons
	TDB_Weapon_Pri(		"QCTriboltDM",			"QCBoltAmmo",		1,		37.0,		0.0,		700.0,		TDB_CW_PROJECTILE|TDB_CW_EXPLOSIVE);
	TDB_Weapon_Pri(		"QCRocketLauncherDM",	"QCRocketAmmo",		1,		34.0,		0.0,		400.0,		TDB_CW_PROJECTILE|TDB_CW_EXPLOSIVE);
	TDB_Weapon_Pri(		"QCLightningGunDM",		"QCCoilAmmo",		1,		0.0,		300.0,		700.0,		0);
	TDB_Weapon_Pri(		"QCRailgunDM",			"QCSlugAmmo",		1,		0.0,		600.0,		MAX_RANGE,	0);
	TDB_Weapon_Pri(		"QCBFGDM",				"QCBFGAmmo",		1,		45.0,		0.0,		700.0,		TDB_CW_PROJECTILE|TDB_CW_EXPLOSIVE);
}

// Freeman PvE Ammo Box passive. Placing the script here for weapon addons to override
// Activator: dying victim
Script "QCDE_MonsterKill_QCFreeman" (void)
{
	if(CheckInventory("MonsterBig") || CheckInventory("MonsterBoss"))
	{
		int itemAmount = 0;
		itemAmount |= (random(0, 5) & 0xFF); // Slugs
		itemAmount <<= 8;
		itemAmount |= (random(0, 5) & 0xFF); // Rockets
		itemAmount <<= 8;
		itemAmount |= (random(0, 30) & 0xFF); // Nails
		itemAmount <<= 8;
		itemAmount |= (random(0, 30) & 0xFF); // Bullets

		if (itemAmount > 0)
			DropItem(0, "FreemanWeaponBox1", itemAmount, 256);

		itemAmount = 0;
		itemAmount |= (random(0, 3) & 0xFF); // BFG
		itemAmount <<= 8;
		itemAmount |= (random(0, 30) & 0xFF); // Coils
		itemAmount <<= 8;
		itemAmount |= (random(0, 5) & 0xFF); // Bolts
		itemAmount <<= 8;
		itemAmount |= (random(0, 10) & 0xFF); // Shells

		if (itemAmount > 0)
			DropItem(0, "FreemanWeaponBox2", itemAmount, 256);
	}
}

//------------------------------------------------
// Give Tribolt on map03
// or after 30 minutes on one map

Script "QCDE_MapsPlayed" OPEN
{
	GiveActorInventory(0,"MapsPlayed",1);
}

Script "QCDE_FreeTribolt" (void)
{
	if(GameType() >= GAME_NET_DEATHMATCH) terminate;
	if(CheckInventory("QCTribolt")) terminate;

	if(CheckInventory("MapsPlayed") != 2 + (GameType() == GAME_SINGLE_PLAYER))
		delay(30 * 60 * 35);

	SpawnForced("QCTribolt", GetActorX(0),GetActorY(0),GetActorZ(0));
}

Script "QCDE_LgShouldGoPurple" (void)
{
	SetResultValue(CheckInventory("LG_UG_Static") && CheckInventory("WeaponZoomedToken"));
}

Script "QCDE_SNGShouldGoFire" (void)
{
	SetResultValue(CheckInventory("SNG_UG_Seeker") && CheckInventory("WeaponZoomedToken"));
}

function void QCDE_SetWeaponZoom (int zoomed, int unzoomsound)
{
	if (zoomed)
	{
		int zoom = 1.0;
		if (CheckWeapon("QCGauntlet"))
		{
			// gauntlet zooms only in DM, but not for Painkiller
			if (GameType() == GAME_NET_DEATHMATCH && !CheckInventory("Class_Painkiller"))
				zoom = 1.8;
		}
		else if (CheckWeapon("QCHeavyMachinegun") || CheckWeapon("QCHeavyMachinegunDM"))
		{
			// both heavy machineguns zoom to 1.8
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			switch (CheckInventory("QCHMachinegunSkin"))
			{
				case 4: // Quake 4
					PlaySound(0,"QC/Weapons/HeavyMachinegun/ZoomIn_Quake4",CHAN_7,1.0,false,0.5);
					break;
				case 5: // ET: QW
					PlaySound(0,"QC/Weapons/HeavyMachinegun/ZoomIn_ETQW",CHAN_7,1.0,false,0.5);
					break;
				Default:
					PlaySound(0,"QC/Weapons/HeavyMachinegun/ZoomIn_Default",CHAN_7,1.0,false,0.5);
					break;
			}
			SetNetworkReplicationFlags( 0 );
			zoom = GetCVar("cl_hmgZoom");
			if (zoom < 1.1)
				zoom = 1.1;
		}
		else if (CheckWeapon("QCShotgun"))
		{
			// coop shotgun zoom if second upgrade was picked up
			if (CheckInventory("SG_UG_Explosive"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"QC/Weapons/Upgrade/SGBeep",CHAN_7);
				SetNetworkReplicationFlags( 0 );
				zoom = 1.1;
			}
		}
		else if (CheckWeapon("QCSuperShotgun"))
		{
			// coop super shotgun zoom if second upgrade was picked up
			if (CheckInventory("SSG_UG_Flame"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"QC/Weapons/Upgrade/SSGBeep",CHAN_7);
				SetNetworkReplicationFlags( 0 );
				zoom = 1.1;
			}
		}
		else if (CheckWeapon("QCSuperNailgun"))
		{
			// coop super nailgun zoom if second upgrade was picked up
			if (CheckInventory("SNG_UG_Seeker"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"QC/Weapons/Upgrade/SNGBeep",CHAN_7);
				SetNetworkReplicationFlags( 0 );
				zoom = 1.1;
			}
		}
		else if (CheckWeapon("QCTribolt"))
		{
			// coop tribolt zoom if second upgrade was picked up
			if (CheckInventory("TB_UG_Grenade"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"QC/Weapons/Upgrade/TBBeep",CHAN_7);
				SetNetworkReplicationFlags( 0 );
				zoom = 1.1;
			}
		}
		else if (CheckWeapon("QCRocketLauncher"))
		{
			// coop rocket launcher zoom if second upgrade was picked up
			if (CheckInventory("RL_UG_Control"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"QC/Weapons/Upgrade/RLBeep",CHAN_7);
				SetNetworkReplicationFlags( 0 );
				zoom = 1.1;
			}
		}
		else if (CheckWeapon("QCLightningGun"))
		{
			// coop lightning gun zoom if second upgrade was picked up
			if (CheckInventory("LG_UG_Static"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"QC/Weapons/Upgrade/LGBeep",CHAN_7);
				SetNetworkReplicationFlags( 0 );
				zoom = 1.1;
			}
		}
		else if (CheckWeapon("QCLightningGunDM"))
		{
			zoom = GetCVar("cl_lgZoom");
			if (zoom < 1.1)
				zoom = 1.1;
		}
		else if (CheckWeapon("QCRailgun") || CheckWeapon("QCRailgunDM"))
		{
			// both railguns zoom to 2.5
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			switch (CheckInventory("QCRailgunSkin"))
			{
				case 4: // Quake 4
					PlaySound(0,"QC/Weapons/Railgun/ZoomIn_Quake4",CHAN_7,1.0,false);
					break;
				case 5: // ET: QW
					PlaySound(0,"QC/Weapons/Railgun/ZoomIn_ETQW",CHAN_7,1.0,false);
					break;
				Default:
					PlaySound(0,"QC/Weapons/Railgun/ZoomIn_Default",CHAN_7,1.0,false);
					break;
			}
			SetNetworkReplicationFlags( 0 );
			zoom = GetCVar("cl_railgunZoom");
			if (zoom < 1.1)
				zoom = 1.1;
		}
		else if (CheckWeapon("QCBFG"))
		{
			// coop BFG zoom if second upgrade was picked up
			if (CheckInventory("BFG_UG_Charge"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"QC/Weapons/Upgrade/BFGBeep",CHAN_7);
				SetNetworkReplicationFlags( 0 );
				zoom = 1.1;
			}
		}
		else if (CheckWeapon("QCMachinegunDM") || CheckWeapon("QCBFGDM")
				|| CheckWeapon("QCShotgunDM") || CheckWeapon("QCSuperShotgunDM")
				|| CheckWeapon("QCNailgunDM") || CheckWeapon("QCSuperNailgunDM")
				|| CheckWeapon("QCTriboltDM") || CheckWeapon("QCRocketLauncherDM"))
        {
			// all other weapons zoom to 1.8
			zoom = GetCVar("cl_otherZoom");
			if (zoom < 1.1)
				zoom = 1.1;
        }

		if (zoom != 1.0)
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			SetPlayerWeaponZoomFactor(PlayerNumber(), zoom);
			SetNetworkReplicationFlags( 0 );
		}
	}
	else
	{
		if (unzoomsound)
		{
			if (CheckWeapon("QCHeavyMachinegun") || CheckWeapon("QCHeavyMachinegunDM"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				switch (CheckInventory("QCHMachinegunSkin"))
				{
					case 4: // Quake 4
						PlaySound(0,"QC/Weapons/HeavyMachinegun/ZoomOut_Quake4",CHAN_7,1.0,false,0.5);
						break;
					case 5: // ET: QW
						PlaySound(0,"QC/Weapons/HeavyMachinegun/ZoomOut_ETQW",CHAN_7,1.0,false,0.5);
						break;
					Default:
						PlaySound(0,"QC/Weapons/HeavyMachinegun/ZoomOut_Default",CHAN_7,1.0,false,0.5);
						break;
				}
				SetNetworkReplicationFlags( 0 );
			}
			else if (CheckWeapon("QCRailgun") || CheckWeapon("QCRailgunDM"))
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				switch (CheckInventory("QCRailgunSkin"))
				{
					case 4: // Quake 4
						PlaySound(0,"QC/Weapons/Railgun/ZoomOut_Quake4",CHAN_7,1.0,false);
						break;
					case 5: // ET: QW
						PlaySound(0,"QC/Weapons/Railgun/ZoomOut_ETQW",CHAN_7,1.0,false);
						break;
					Default:
						PlaySound(0,"QC/Weapons/Railgun/ZoomOut_Default",CHAN_7,1.0,false);
						break;
				}
				SetNetworkReplicationFlags( 0 );
			}
		}

		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		SetPlayerWeaponZoomFactor(PlayerNumber(), 1.0);
		SetNetworkReplicationFlags( 0 );
	}
}

Script "QCDE_ZoomCheckSelect" (void)
{
	if (CheckInventory("WeaponZoomedToken"))
	{
		QCDE_SetWeaponZoom(true, false);
	}
	else
	{
		QCDE_SetWeaponZoom(false, false);
	}
}

Script "QCDE_ZoomControl" (int predicting, int justPressed, int justReleased, int buttons)
{
	// Players only have the gauntlet and railgun in instagib, so just disable zoom for them
	if (!predicting && !CheckInventory("Instagib"))
	{
		bool shouldZoomIn = !CheckInventory("WeaponZoomedToken") && justPressed;
		bool shouldZoomOut = CheckInventory("WeaponZoomedToken") && GetCVar("cl_holdZoom") ? justReleased : justPressed;

		if (shouldZoomIn)
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			SetInventory("WeaponZoomedToken", 1);
			SetNetworkReplicationFlags( 0 );
			QCDE_SetWeaponZoom(true, true);
		}
		else if (shouldZoomOut)
		{
			SetNetworkReplicationFlags( NETREP_SKIPOWNER );
			SetInventory("WeaponZoomedToken", 0);
			SetNetworkReplicationFlags( 0 );
			QCDE_SetWeaponZoom(false, true);
		}
	}
}